Хотфикс 3864: Исправление некорректной логики механизма прав
VodovozOrganization/Vodovoz pull request #1143
Opened 2021-12-09 14:43 UTC by Art8m

Добавлена возможно открывать карточку сущности только для просмотра при наличии права на просмотр, редактирование сущности разрешено только при наличии права на изменение.

Доработаны следующие журналы:

1. Журнал сотрудников
2. Журнал рекламаций. Оставить возможность переключать вкладки подключенных отделов и скроллинг комментариев, если много текста. Плюс возможность скачивать файлы из обсуждения и справа
3. Журнал МЛ и Работа кассы с МЛ
3.1 Диалог создания МЛ. Оставить возможность скроллинга и кнопки "Распечатать" и "Время печати МЛ" (поправить ее работу)
3.2 Диалог ведения МЛ. Оставить возможность скроллинга
3.3 Диалог разбора МЛ. Оставить возможность скроллинга
3.4 Диалог проверки километража. Оставить возможность скроллинга
3.5 Диалог закрытия. Оставить возможность скроллинга и кнопку "Распечатка". Информация о МЛ в развернутом виде. Можно развернуть панель "Возвраты/Недовозы"

2021-12-10 07:35 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/EmployeesJournalViewModel.cs
> +		}
Так сделал потому что метод из базового класса приватный? Я его уже сделал protected, исправь

2021-12-10 07:36 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/EmployeesJournalViewModel.cs
> +		}
Да, ок исправлю

2021-12-14 14:12 UTC, ShubArseniy commented on Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
>  										&& RouteListUoW.Root.Status != RouteListStatus.MileageCheck;
А почему не заменить на (PermissionResult.CanCreate || PermissionResult.CanUpdate && RouteListUoW.Root.id == 0). Сохранили и всё, редактировать не могу

2021-12-14 14:12 UTC, ShubArseniy commented on Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
>  			}
CanEditRows вызывается бесконечное число раз. Надо проверять такое

2021-12-16 07:20 UTC, Druchik commented on Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
>  										&& RouteListUoW.Root.Status != RouteListStatus.MileageCheck;
Так у них же сейчас есть возможность редактировать МЛ согласно этому условию, поэтому здесь только добавляем проверку на создание или редактирование, чтобы логика не менялась.

2021-12-17 08:02 UTC, Druchik commented on Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
> +			btnCancel.Clicked += OnCancelClicked;
А отписаться от базового метода?

2021-12-17 08:05 UTC, ShubArseniy commented on Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
> +			btnCancel.Clicked += OnCancelClicked;
Я кнопку переименовал, он подписыватся по названию

2021-12-17 08:10 UTC, Druchik commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			_orderPermissionResult = ServicesConfig.CommonServices.CurrentPermissionService.ValidateEntityPermission(typeof(Order));
В базе же уже есть permissionResult

2021-12-17 08:17 UTC, Druchik commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
>  		private void SetSensetivity(bool isSensetive)
Очепятка Sensitive

2021-12-17 08:17 UTC, ShubArseniy commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			_orderPermissionResult = ServicesConfig.CommonServices.CurrentPermissionService.ValidateEntityPermission(typeof(Order));
Исправил

2021-12-17 08:27 UTC, Druchik commented on Vodovoz/ViewModels/Logistic/RouteListAnalysisViewModel.cs
> +		private readonly IPermissionResult _routeListPermissionSet;
ТОже есть в базовом классе

2021-12-17 08:44 UTC, Druchik requested changes

2021-12-17 08:44 UTC, Druchik commented on VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
> +		private readonly IPermissionResult _complaintPermissionResult;
Аналогично

2021-12-17 08:44 UTC, Druchik commented on VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
> +		private bool _canCloseComplaintsPermissionResult;
Мелочь, но можно readonly воткнуть

2021-12-17 08:45 UTC, Druchik commented on Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
> +			btnCancel.Clicked += OnCancelClicked;
Ага, увидел позже))

2021-12-17 09:43 UTC, ShubArseniy commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
>  		private void SetSensetivity(bool isSensetive)
Исправил

2021-12-17 09:44 UTC, ShubArseniy commented on Vodovoz/ViewModels/Logistic/RouteListAnalysisViewModel.cs
> +		private readonly IPermissionResult _routeListPermissionSet;
Исправил

2021-12-17 09:45 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
> +		private readonly IPermissionResult _complaintPermissionResult;
Тут проверяется и Complaint и ComplaintDiscussion. В базовом только ComplaintDiscussion

2021-12-17 09:45 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
> +		private bool _canCloseComplaintsPermissionResult;
Исправил

2021-12-17 09:46 UTC, Druchik commented on VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
> +		private readonly IPermissionResult _complaintPermissionResult;
Сам дурак, увидел)

2021-12-17 09:47 UTC, Druchik approved these changes

2022-01-12 08:03 UTC, merged