Создана модель клонирования заказов
VodovozOrganization/Vodovoz pull request #1159
Opened 2021-12-21 13:19 UTC by Enzogord

2021-12-21 14:30 UTC, Druchik commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			OrderCopyModel orderCopyModel = new OrderCopyModel(nomenclatureParameterProvider, flyerRepository);
ParametersProvider и fyerRepository вроде бы есть уже

2021-12-21 14:33 UTC, Druchik commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			var flyerRepository = new FlyerRepository();
Аналогично

2021-12-21 14:37 UTC, Druchik commented on VodovozBusiness/Domain/Orders/Order.cs
> +				orderItem.RecalculatePrice();
Не уверен на 100%, но вроде for ставился из-за некорректной работы foreach из-за кучи подписок. Хотя могу ошибаться

2021-12-21 14:40 UTC, Enzogord commented on VodovozBusiness/Domain/Orders/Order.cs
> +				orderItem.RecalculatePrice();
скорее потому что foreach для observable приводил var к object, подписки тут никакие не дергаются.

2021-12-21 14:54 UTC, Druchik commented on VodovozBusiness/Domain/Orders/Order.cs
> +				orderItem.RecalculatePrice();
Я про то, что этот метод дергается и при изменении количества и при удалении строки заказа. Но, скорее всего ты прав - проблема в observable

2021-12-22 06:15 UTC, Druchik requested changes

2021-12-22 06:15 UTC, Druchik commented on VodovozBusiness/Models/Orders/CopyingOrder.cs
> +
Лишняя строка

2021-12-22 06:15 UTC, Druchik commented on VodovozBusiness/Models/Orders/CopyingOrder.cs
> +			}
А разве нужна такая грядка условий? Не проще делать так: если есть original ставить его, иначе - обычный. Ведь, насколько я помню, при восстановлении скидки original ставится в null

2021-12-22 06:16 UTC, Druchik commented
И еще, может упустил, но что будет если копировать заказ со скидкой по акции бутыль, она перенесется на новый заказ?

2021-12-22 06:28 UTC, Enzogord commented
> И еще, может упустил, но что будет если копировать заказ со скидкой по акции бутыль, она перенесется на новый заказ?

Не должно переносится, она только для первого заказа

2021-12-22 06:32 UTC, Druchik commented
Лучше проверь. Она же добавляется в discount. Просто не перенесутся сами данные о ней скидка по акции, количество бутылей и т.д.. Т.е. была скидка на воду 5% а с акцией стала 15% и она перелетит в новый заказ. Но может это и не так критично

2021-12-24 05:28 UTC, Druchik approved these changes

2021-12-27 13:43 UTC, merged