Реализована доставка за час
VodovozOrganization/Vodovoz pull request #1290
Opened 2022-03-05 08:21 UTC by ShubArseniy

2022-03-05 13:41 UTC, Druchik requested changes

2022-03-05 13:41 UTC, Druchik commented on Vodovoz/ViewWidgets/Logistics/AdditionalLoadingItemsView.cs
> +		}
А зачем эти лютые танцы? У тебя логика работы кнопок меняется?

2022-03-05 13:41 UTC, Druchik commented on Vodovoz/Views/Goods/AdditionalLoadingSettingsView.cs
> +		public bool AskSaveOnClose => ViewModel.CanEdit;
А чего не во вью модели?

2022-03-05 13:41 UTC, Druchik commented on Vodovoz/Views/Goods/NomenclatureView.cs
> +				.AddBinding(ViewModel.Entity, e => e.Weight, w => w.Value, new DecimalToDoubleConverter())
А зачем конвертер? У тебя же свойство децимал, если я не ошибаюсь. Выставляешь у спина valueAsDecimal если надо и все вроде

2022-03-05 13:41 UTC, Druchik commented on VodovozBusiness/Domain/Documents/CarUnloadDocument.cs
> +						|| nomenclature.Height == default))
Дженкинс собирает? Раньше у меня падал, если не укажешь конкретику(default)

2022-03-05 13:41 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Goods/NomenclatureRepository.cs
> +		public Nomenclature Nomenclature { get; set; }
Тогда Id можно было выкинуть

2022-03-05 13:45 UTC, ShubArseniy commented on VodovozBusiness/EntityRepositories/Goods/NomenclatureRepository.cs
> +		public Nomenclature Nomenclature { get; set; }
Это общая нода, много где используется. Где-то нужен только Id, где-то вся номенклатура

2022-03-05 13:46 UTC, ShubArseniy commented on VodovozBusiness/Domain/Documents/CarUnloadDocument.cs
> +						|| nomenclature.Height == default))
Вроде собирает

2022-03-05 15:27 UTC, ShubArseniy commented on Vodovoz/ViewWidgets/Logistics/AdditionalLoadingItemsView.cs
> +		}
Танцы убрал

2022-03-05 15:27 UTC, ShubArseniy commented on Vodovoz/Views/Goods/AdditionalLoadingSettingsView.cs
> +		public bool AskSaveOnClose => ViewModel.CanEdit;
Переместил

2022-03-05 15:27 UTC, ShubArseniy commented on Vodovoz/Views/Goods/NomenclatureView.cs
> +				.AddBinding(ViewModel.Entity, e => e.Weight, w => w.Value, new DecimalToDoubleConverter())
Исправил

2022-03-09 06:01 UTC, Druchik approved these changes

2022-03-09 06:08 UTC, merged