Предупреждение о фиксе
VodovozOrganization/Vodovoz pull request #1352
Opened 2022-04-01 14:59 UTC by EnergyDead

2022-04-01 15:07 UTC, Enzogord requested changes

2022-04-01 15:07 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +			using(var uow = UnitOfWorkFactory.CreateWithoutRoot($"[ES]Получение списка адресов имеющих фиксированную цену"))
[ES] Убери, оно тут не нужно. Это сокращенное обозначение программы, где был запущен.

2022-04-01 15:07 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +					.Select(dp => deliveryPoint.CompiledAddress)
Давай тут лучше загрузим CompiledAddressShort

2022-04-01 15:07 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +				NomenclatureFixedPrice fixedPrice = null;
К алиасам у нас принятно приписывать в конце Alias. Добавь пожалуйста

2022-04-02 09:34 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +			using(var uow = UnitOfWorkFactory.CreateWithoutRoot($"[ES]Получение списка адресов имеющих фиксированную цену"))
Понял

2022-04-02 09:35 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +					.Select(dp => deliveryPoint.CompiledAddress)
CompiledAddressShort не нашел, использовал ShortAddress

2022-04-02 09:36 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +				NomenclatureFixedPrice fixedPrice = null;
Понял

2022-04-12 15:49 UTC, closed without merging