3947 Предупреждение о фиксе
VodovozOrganization/Vodovoz pull request #1369
Opened 2022-04-12 15:48 UTC by EnergyDead

2022-04-13 07:55 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +		public IList<string> GetAddressesWithFixedPrices(int counterpartyId)
Не критичено, но просто на будущее, если не предусмотрено редактирование списка, лучше возвращать просто IEnumerable<>.

2022-04-13 08:00 UTC, Enzogord requested changes

2022-04-13 08:00 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +					.SelectList( list => list.SelectGroup( dp => deliveryPointAlias.ShortAddress ) )
А вот тут лучше исправить на один из вариантов написания лямбды. Думаю могут возникнуть проблемы с большими запросами если привыкнуть к такому.
Если запрос начинает использовать алиасы то все лямбды в запросе лучше использовать на алиасах: () => alias.SomeProperty
А если без алиасов то все в запросе писать x => x.SomeProperty

2022-04-15 14:05 UTC, Art8m approved these changes

2022-04-15 14:23 UTC, Enzogord approved these changes

2022-04-15 14:55 UTC, merged