relocate add route  button
VodovozOrganization/Vodovoz pull request #1370
Opened 2022-04-12 15:58 UTC by EnergyDead

2022-04-13 07:49 UTC, Enzogord requested changes

2022-04-13 07:49 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
> -                    <property name="Label">Экспедиторы на работе</property>
Почему он удаляется?

2022-04-13 07:51 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
> -                    <property name="Label">Экспедиторы на работе</property>
Если видишь что какие-то изменения не касаются твоей задачи, откати их в гите и пересобери еще раз без них. Бывает что он при редактировании UI начинает влиять на соседние компоненты, и не всегда эти влияния безвредны.

2022-04-13 17:02 UTC, EnergyDead commented on Vodovoz/gtk-gui/gui.stetic
> -                    <property name="Label">Экспедиторы на работе</property>
Понял

2022-04-15 13:53 UTC, Art8m approved these changes

2022-04-15 14:14 UTC, Enzogord submitted a review, later dismissed

2022-04-15 14:43 UTC, Art8m requested changes

2022-04-15 14:43 UTC, Art8m commented on Vodovoz/gtk-gui/Vodovoz.Views.Logistic.RouteListsOnDayView.cs
> +		private global::Gamma.GtkWidgets.yButton buttonAutoCreate;
На 81 строке она уже есть, надо одну убрать

2022-04-15 15:02 UTC, Art8m approved these changes

2022-04-15 15:03 UTC, merged