3969 Дополнения в отчет по опозданиям
VodovozOrganization/Vodovoz pull request #1383
Opened 2022-04-18 18:38 UTC by EnergyDead

2022-04-19 08:55 UTC, Enzogord requested changes

2022-04-19 08:55 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
> +                        <property name="Sensitive">False</property>
Опять же, меняется то что не надо. Делай ревью изменений

2022-04-19 08:55 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
> -                    <property name="Label">Экспедиторы на работе</property>
Так же

2022-04-19 08:55 UTC, Enzogord commented on VodovozReports/Reports/Logistic/DeliveriesLate.rdl
> +    	TIMEDIFF(TIME(route_list_addresses.creation_date + INTERVAL 1 HOUR), delivery_schedule.to_time),
Не реализована загрузка времени из параметров

2022-04-19 08:55 UTC, Enzogord commented on VodovozReports/Reports/Logistic/DeliveriesLate.rdl
> +AND (@select_mode = 'All' OR ((@select_mode = 'WithoutDeliveryInAnHour' OR is_fast_delivery = 1) AND (@select_mode = 'DeliveryInAnHour' OR is_fast_delivery = 0)))
Сложно понимаемое условие.
Попробуй прочитать это по русски нормально.
Мне кажется во второй части надо заменть OR на AND и надоборот, тогда сразу будут видны 3 разных условия отбора заказов.

2022-04-19 08:58 UTC, Enzogord commented on VodovozReports/Reports/Logistic/DeliveriesLate.rdl
> +AND (@select_mode = 'All' OR ((@select_mode = 'WithoutDeliveryInAnHour' OR is_fast_delivery = 1) AND (@select_mode = 'DeliveryInAnHour' OR is_fast_delivery = 0)))
Может я ошибаюсь и не понял условие, тогда объясни обратное

2022-04-19 14:13 UTC, Enzogord requested changes

2022-04-19 14:56 UTC, Enzogord approved these changes

2022-04-20 13:59 UTC, Art8m approved these changes

2022-04-20 14:11 UTC, merged