3970 Дополнения в проверку на халявщиков
VodovozOrganization/Vodovoz pull request #1406
Opened 2022-04-26 20:39 UTC by EnergyDead

2022-04-26 21:58 UTC, EnergyDead commented
Форматирование поправлю

2022-04-27 06:25 UTC, Druchik requested changes

2022-04-27 06:25 UTC, Druchik commented on Vodovoz/Views/Orders/PromotionalSetView.cs
> +			ycheckForTheFirstOrderOnlyToTheAddress.Binding.AddBinding( ViewModel, vm => vm.CanUpdate, w => w.Sensitive ).InitializeFromSource();
Не нужно два раза инициализировать биндинг для одного и того же виджета.
Можно просто накидать
Widget.AddBinding
           .AddBinding.InitializeFromSource()
Посмотри как в EmployeeView сделано и желательно остальные привести к этому виду

2022-04-27 06:25 UTC, Druchik commented on Vodovoz/Views/Orders/PromotionalSetView.cs
> +			SetSensitivityByPermission( "can_change_the_type_of_promo_set", ycheckForTheFirstOrderOnlyToTheAddress );
Такие вещи лучше выносить во вью модель, если она имеется.

2022-04-27 06:25 UTC, Druchik commented on VodovozBusiness/Domain/Orders/PromotionalSet.cs
> +		[Display(Name = "Только для первого заказа на адресс")]
с лишняя

2022-04-27 06:25 UTC, Druchik commented on VodovozBusiness/Domain/Orders/PromotionalSet.cs
> +			set => SetField(ref forTheFirstOrderOnlyToTheAddress, value, () => ForTheFirstOrderOnlyToTheAddress);
лямбду убери, она лишняя () => ForTheFirstOrderOnlyToTheAddress

2022-04-27 06:25 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +											   && counterpartyAlias.PersonType == PersonType.legal
"И" можно через .And оформить, но можно и так оставить

2022-04-27 06:25 UTC, Druchik commented on VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
> +				}
Не совсем корректный вопрос, в точке доставки создается точка доставки, а не клиент

2022-04-27 06:36 UTC, Enzogord requested changes

2022-04-27 06:36 UTC, Enzogord commented on VodovozBusiness/Domain/Orders/PromotionalSet.cs
> +		bool forTheFirstOrderOnlyToTheAddress;
у нас для IDE определены правила форматирования в которых локальные переменные должны начинаться с "_". Эти правила автоматически цепляются IDE. Она должна была подсказывать, перепроверь

2022-04-27 06:36 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +											   && deliveryPointAlias.Street.IsLike( deliveryPoint.Street, MatchMode.Anywhere )
Зачастую проще и красивее написать несколько Where подряд вместо &&, Where по умолчанию соединяет как AND все условия. Не обязательно исправлять, это так небольшая подсказка.

2022-04-27 06:36 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +		public bool AddressVerification( IUnitOfWork uow, DeliveryPoint deliveryPoint )
Название метода не понятное, лучше придумать что-то поточнее, что будет говорить о совершаемых действиях.

2022-04-27 06:36 UTC, Enzogord commented on Vodovoz/Views/Orders/PromotionalSetView.cs
> +		private bool SetSensitivityByPermission( string permission, Widget widget )
Так лучше не делать. У тебя есть ViewModel в этом классе, такие значения должны определяться в ней. 
Во View должна оставаться только логика зависимая только от View, и биндинги на ViewModel, ну в крайних случаях подписка на события.

2022-04-27 08:21 UTC, EnergyDead commented on Vodovoz/Views/Orders/PromotionalSetView.cs
> +			ycheckForTheFirstOrderOnlyToTheAddress.Binding.AddBinding( ViewModel, vm => vm.CanUpdate, w => w.Sensitive ).InitializeFromSource();
Переделал
Делал по аналогии

2022-04-27 08:29 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +											   && counterpartyAlias.PersonType == PersonType.legal
оставил так

2022-04-27 08:31 UTC, EnergyDead commented on VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
> +				}
изменил на

>  "Уточните с клиентом: по данному адресу находится юр.лицо. Вы уверены, что хотите создается точку доставки?"

2022-04-27 08:31 UTC, EnergyDead commented on VodovozBusiness/Domain/Orders/PromotionalSet.cs
> +		bool forTheFirstOrderOnlyToTheAddress;
поправил. Так же для всего документа. В классе все переменные были без "_", по аналогии делал.

2022-04-27 09:17 UTC, EnergyDead commented on Vodovoz/Views/Orders/PromotionalSetView.cs
> +		private bool SetSensitivityByPermission( string permission, Widget widget )
Вынес в ViewModel

2022-04-27 09:17 UTC, EnergyDead commented on Vodovoz/Views/Orders/PromotionalSetView.cs
> +			SetSensitivityByPermission( "can_change_the_type_of_promo_set", ycheckForTheFirstOrderOnlyToTheAddress );
Вынес в ViewModel

2022-04-27 09:23 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
> +		public bool AddressVerification( IUnitOfWork uow, DeliveryPoint deliveryPoint )
AddressVerification -> CheckingAnAddressForDeliveryForNewCustomers

2022-04-27 14:32 UTC, Druchik requested changes

2022-04-27 14:32 UTC, Druchik commented on Vodovoz/ViewModels/Orders/PromotionalSetViewModel.cs
> +			_canChangeTheTypeOfPromoSet = commonServices.CurrentPermissionService.ValidatePresetPermission( "can_change_the_type_of_promo_set" );
Зачем тебе лишнее поле? Сделай CanChangeType get свойством и инициализируй его в конструкторе
CanChangeType = commonServices.CurrentPermissionService.ValidatePresetPermission( "can_change_the_type_of_promo_set" );
public bool CanChangeType { get; }

2022-04-27 14:32 UTC, Druchik commented on VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
> +					ShowInfoMessage( $"Уточните с клиентом: по данному адресу находится юр.лицо. Вы уверены, что хотите создается точку доставки?" );
создается -> создать

2022-04-27 15:53 UTC, EnergyDead commented on Vodovoz/ViewModels/Orders/PromotionalSetViewModel.cs
> +			_canChangeTheTypeOfPromoSet = commonServices.CurrentPermissionService.ValidatePresetPermission( "can_change_the_type_of_promo_set" );
Согласен, сразу не подумал

2022-04-27 15:53 UTC, EnergyDead commented on VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
> +					ShowInfoMessage( $"Уточните с клиентом: по данному адресу находится юр.лицо. Вы уверены, что хотите создается точку доставки?" );
+

2022-04-28 06:04 UTC, Druchik approved these changes

2022-04-29 09:14 UTC, Enzogord approved these changes

2022-06-30 11:02 UTC, merged