3985 Доп.фильтры в отчет по первичным клиентам
VodovozOrganization/Vodovoz pull request #1412
Opened 2022-04-28 09:56 UTC by EnergyDead

2022-04-28 10:23 UTC, Druchik requested changes

2022-04-28 10:23 UTC, Druchik commented on Vodovoz/ReportsParameters/Orders/FirstClientsReport.cs
> +			};
Зачем этот винегрет? Так не пойдет, а если перечисление изменится?
Есть же специальный виджет под enum yEnumComboBox, вроде. Можешь глянуть в том же OrderDlg enumPaymentType

2022-04-28 10:23 UTC, Druchik commented on Vodovoz/ReportsParameters/Orders/FirstClientsReport.cs
> +		}
Тогда и это не понадобится

2022-04-28 10:23 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
Это что ты рассчитываешь?

2022-04-28 10:23 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +  AND (@type_of_payment = 'All' OR (o.payment_type  = @type_of_payment) )
А чего не @payment_type?

2022-04-29 20:08 UTC, EnergyDead commented on Vodovoz/ReportsParameters/Orders/FirstClientsReport.cs
> +			};
передеалал на yEnumComboBox

2022-04-29 20:26 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
название не верно. 
sum_to_receive -> price

2022-04-29 20:26 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +  AND (@type_of_payment = 'All' OR (o.payment_type  = @type_of_payment) )
сделал @payment_type

2022-05-04 06:18 UTC, Druchik requested changes

2022-05-04 06:18 UTC, Druchik commented on Vodovoz/gtk-gui/gui.stetic
> -            <property name="Active">True</property>
Похоже на мусор

2022-05-04 06:18 UTC, Druchik commented on Vodovoz/gtk-gui/gui.stetic
> -                    <signal name="Toggled" handler="OnHideForwadersToggled" />
И это

2022-05-04 06:18 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
Ты так и не ответил, что это за расчеты?

2022-05-04 18:14 UTC, EnergyDead commented on Vodovoz/gtk-gui/gui.stetic
> -            <property name="Active">True</property>
откатил

2022-05-04 18:16 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
price - Сумма заказа
count_19_bottles - количество 19л бутылей.

2022-05-05 07:13 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
Сумма заказа рассчитывается по другому: sum(Ifnull(oi.actual_count, oi.count) * oi.price - oi.discount_money) есть примеры в других отчетах. Скорее всего нужно еще будет округление

2022-05-05 07:15 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
Количество 19л бутылей если это бутылей с водой, то надо еще добавлять категорию вода иначе он может подтягивать простые пустые 19л бутыли

2022-05-05 12:03 UTC, Enzogord approved these changes

2022-05-05 12:05 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    COUNT(nomenclature.tare_volume = 'Vol19L') as count_19_bottles,
Поправил

2022-05-16 06:07 UTC, Druchik requested changes

2022-05-16 06:07 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    SUM(ROUND(IFNULL(i.actual_count, i.count) * i.price - i.discount_money, 0)) AS price,
Почему округление до 0 знаков после запятой? Товар же может быть с копейками, округляй до 2

2022-05-16 06:07 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +          <DataField>price</DataField>
Тогда уж order_sum, если это сумма заказа, а не "цена"

2022-05-16 06:07 UTC, Druchik commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +          <DataField>count_19_bottles</DataField>
Тут тоже можно поправить название на 19l_water_count или count_19l_water, так будет точнее, т.к. ты же не считаешь пустые бутыли

2022-05-16 12:54 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +    SUM(ROUND(IFNULL(i.actual_count, i.count) * i.price - i.discount_money, 0)) AS price,
Да, точно! Округлил до 2.

2022-05-16 13:00 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +          <DataField>price</DataField>
price -> order_sum

2022-05-16 13:00 UTC, EnergyDead commented on VodovozReports/Reports/Orders/FirstClients.rdl
> +          <DataField>count_19_bottles</DataField>
count_19_bottles -> count_19l_water

2022-05-16 14:05 UTC, Druchik approved these changes

2022-05-16 14:21 UTC, merged