3889 Добавление нашей платежной страницы
VodovozOrganization/Vodovoz pull request #1423
Opened 2022-05-04 09:46 UTC by Druchik

2022-05-04 09:51 UTC, Druchik commented
Должен собираться после мержа предыдущего ПР 1422, т.к. там есть необходимые изменения главной сущности

2022-05-05 06:59 UTC, Enzogord requested changes

2022-05-05 06:59 UTC, Enzogord commented on Services/WebApi/PayPageAPI/Controllers/IPayViewModelFactory.cs
> +﻿using PayPageAPI.Models;
Это же часть FastPayment. Зачем неймспейс новый создан?

2022-05-05 07:02 UTC, Druchik commented on Services/WebApi/PayPageAPI/Controllers/IPayViewModelFactory.cs
> +﻿using PayPageAPI.Models;
Это же отдельный сервис на отдельном домене

2022-05-05 07:14 UTC, Enzogord approved these changes

2022-05-05 09:17 UTC, merged