4012 Исключаем платные дороги
VodovozOrganization/Vodovoz pull request #1472
Opened 2022-05-23 16:47 UTC by EnergyDead

2022-05-24 07:20 UTC, Art8m requested changes

2022-05-24 07:20 UTC, Art8m commented on VodovozBusiness/Parameters/GlobalSettings.cs
> +		public bool ExcludeToll =>  _parametersProvider.GetBoolValue("osrm_exclide_toll");
Опечатка: osrm_exclUde_toll

2022-05-24 07:26 UTC, Art8m requested changes

2022-05-24 07:26 UTC, Art8m commented on VodovozBusiness/Domain/Logistic/RouteList.cs
> +		readonly IGlobalSettings _globalSettings = new GlobalSettings(new ParametersProvider());
Модификатор доступа в некоторых местах отсутствует.

2022-05-25 06:32 UTC, Art8m approved these changes

2022-05-31 08:22 UTC, EnergyDead commented
До включения:
![image (29)](https://user-images.githubusercontent.com/96041711/171127208-80ee89cf-e68c-416b-8ee5-698d09a39a60.png)
После:
![image (30)](https://user-images.githubusercontent.com/96041711/171127198-4a5268b2-2fc8-465a-bf28-d9b2b05a1a9d.png)

2022-05-31 09:49 UTC, merged