3986 Затраты при эксплуатации ТС
VodovozOrganization/Vodovoz pull request #1475
Opened 2022-05-25 03:03 UTC by EnergyDead

2022-05-25 03:09 UTC, EnergyDead commented
Как сделать выборку по типу:

> `WhereRestrictionOn(e => e.Car.CarModel.CarTypeOfUse).IsIn(carTypeOfUse.ToList())`

выдает ошибку:
  

> _variable 'e' of type 'Vodovoz.Domain.Logistic.CarEvent' referenced from scope '', but it is not defined_

2022-05-25 06:49 UTC, Druchik requested changes

2022-05-25 06:49 UTC, Druchik commented on VodovozBusiness/Domain/Logistic/Cars/CarEvent.cs
> +		}
Так и назвал бы стоимость ремонта, а не price, может это стоимость страховки. RepairCost возможно

2022-05-25 06:49 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Logistic/CarRepository.cs
> +		}
А это куда, зачем?

2022-05-25 06:49 UTC, Druchik commented on Vodovoz/Views/Reports/CostCarExploitationReportView.cs
> +				.InitializeFromSource();
Ближе по смыслу Selected, а не Restricted я думаю

2022-05-25 06:56 UTC, Druchik commented on VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
> +		More
Other - иное, другое

2022-05-26 06:49 UTC, Druchik requested changes

2022-05-26 06:49 UTC, Druchik commented on Vodovoz/Views/Reports/CostCarExploitationReportView.cs
> +				.AddColumn("Стоимость").SetDataProperty(ev => ev.Price)
Это старый вариант. Вместо SetDataProperty используй напрямую AddTextRenderer

2022-05-26 06:49 UTC, Druchik commented on VodovozBusiness/Domain/Logistic/Cars/CarEvent.cs
> +		Ssago,
А с этим что?

2022-05-26 06:49 UTC, Druchik commented on VodovozBusiness/HibernateMapping/Logistic/Cars/CarEventMap.cs
> +			Map(x => x.Price).Column( "price" );
А это почему не поменял? И в модели не забудь, если ее заливал

2022-05-30 09:41 UTC, Druchik requested changes

2022-05-30 09:41 UTC, Druchik commented on Vodovoz/Views/Reports/CostCarExploitationReportView.cs
> +			ytreeviewSubjectTypes.ItemsDataSource = ViewModel.CarEventTypeNodes;
Почему Тип адреса? Забыл поправить?

2022-05-30 09:41 UTC, Druchik commented on Vodovoz/Views/Reports/CostCarExploitationReportView.cs
> +				});
Здесь нормально с ошибкой отрабатывает?

2022-05-30 09:41 UTC, Druchik commented on Vodovoz/gtk-gui/gui.stetic
> +                        <property name="Sensitive">False</property>
Мусор опять по затягивал. Оставь только свои изменения

2022-05-30 09:41 UTC, Druchik commented on VodovozBusiness/VodovozBusiness.csproj
> -    <Folder Include="HibernateMapping\Chat\" />
Зачем грохнул?

2022-05-30 09:41 UTC, Druchik commented on VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
> +	}
А почему не использовать GetEnumTitle() из GammaBinding или GammaUtils, если я не ошибаюсь

2022-05-30 09:41 UTC, Druchik commented on VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
> +		}
Это дубли или у меня глюки?)

2022-06-01 06:16 UTC, Druchik approved these changes

2022-06-01 06:54 UTC, merged