Логирование ошибок сохранения в журнале экспресс-доставок и рефакторинг
VodovozOrganization/Vodovoz pull request #1538
Opened 2022-06-17 14:32 UTC by Art8m

2022-06-17 14:50 UTC, Druchik requested changes

2022-06-17 14:50 UTC, Druchik commented on Vodovoz/toolbars/ToolbarActions.cs
> +		ILogger logger = LogManager.GetCurrentClassLogger();
А ничего что логгер для другого класса создается?

2022-06-17 14:50 UTC, Druchik commented on VodovozBusiness/Domain/Logistic/FastDelivery/FastDeliveryAvailabilityHistory.cs
Лишняя строка

2022-06-17 15:46 UTC, Art8m commented on Vodovoz/toolbars/ToolbarActions.cs
> +		ILogger logger = LogManager.GetCurrentClassLogger();
Исправил

2022-06-20 05:55 UTC, Druchik approved these changes

2022-06-20 06:17 UTC, merged