4041 Обновление всплывающих окон
VodovozOrganization/Vodovoz pull request #1562
Opened 2022-07-06 03:55 UTC by EnergyDead

2022-07-06 06:34 UTC, Druchik requested changes

2022-07-06 06:34 UTC, Druchik commented on Vodovoz/Dialogs/CastomMessageDlg.cs
> +			label1.Visible = label2.Visible = GtkScrolledWindow.Visible = false;
Выключаешь прокрутку, но нигде ее не включаешь или я что пропустил?

2022-07-11 02:58 UTC, EnergyDead commented on Vodovoz/Dialogs/CastomMessageDlg.cs
> +			label1.Visible = label2.Visible = GtkScrolledWindow.Visible = false;
включил

2022-07-11 02:58 UTC, EnergyDead commented on Vodovoz/Dialogs/CastomMessageDlg.cs
> +		public CastomMessageDlg(Window parent_window, DialogFlags flags, MessageType type, ButtonsType bt, string format = null, bool useMarkup = false)
изменил

2022-07-11 10:22 UTC, Druchik commented on Vodovoz/ServiceDialogs/CastomInteractiveService.cs
> +		private readonly CastomQuestion _question = new CastomQuestion();
Обычные классы, не завязанные на гтк, можно было и переименовать

2022-07-11 10:23 UTC, Druchik commented
Главное мусор из стетика убери, остальное по желанию, если есть время

2022-07-14 09:20 UTC, Druchik approved these changes

2022-07-14 11:08 UTC, merged