4042 costs of operating vehicles
VodovozOrganization/Vodovoz pull request #1563
Opened 2022-07-06 06:35 UTC by EnergyDead

2022-07-06 12:52 UTC, Enzogord requested changes

2022-07-06 12:52 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
> +                        <property name="Sensitive">False</property>
и тут

2022-07-06 12:52 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/CarEventViewModel.cs
> +		public IList<FineItem> FineItems => Entity.Fines.SelectMany(x => x.Items).OrderByDescending(x => x.Id).ToList();
При каждом обращении будет проходить по всем строкам и сортировать их еще. Думаю можно сделать лучше.

2022-07-06 12:52 UTC, Enzogord commented on Vodovoz/Views/Logistic/CarEventView.cs
> +			buttonAddFine.Clicked += (sender, e) => { ViewModel.AddFineCommand.Execute(this.Tab); };
Не нужно. Проследи, что такое this.Tab

2022-07-13 08:49 UTC, EnergyDead commented on Vodovoz/Views/Logistic/CarEventView.cs
> +			buttonAddFine.Clicked += (sender, e) => { ViewModel.AddFineCommand.Execute(this.Tab); };
понял

2022-07-14 08:39 UTC, Enzogord requested changes

2022-07-14 08:39 UTC, Enzogord commented on Vodovoz/MainWindow.cs
>  		var uowFactory = autofacScope.Resolve<IUnitOfWorkFactory>();
watcher тоже можно получить из скоупа

2022-07-14 08:39 UTC, Enzogord commented on Vodovoz/Views/Reports/CostCarExploitationReportView.cs
> +			ViewModel.PropertyChanged += ReloadReport;
ReloadReport не очень подходит на роль метода обработки событий изменения свойств. Лучше сделай обычный обработчик, а ReloadReport представь в виде void ReloadReport(). Так будет читаться логичнее, и не придется передавать не нужные аргументы во всех вызовах.
И главное, ты хочешь перезагружать отчет на изменение абсолютно любого свойства вью модели? Если нет тогда, проверяй какое свойство поменялось.

2022-07-14 08:39 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/CarEventViewModel.cs
> +			FineItems = Entity.Fines.SelectMany(x => x.Items).OrderByDescending(x => x.Id).ToList();
Ниже уже тебя точно такая же строка, объедини их в метод

2022-07-14 08:39 UTC, Enzogord commented on VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
> +			IEntityAutocompleteSelectorFactory carSelectorFactory, // создать журнал для car
И где он?)

2022-07-14 08:39 UTC, Enzogord commented on Vodovoz/Views/Reports/CostCarExploitationReportView.cs
> +			var filechooser = new FileChooserDialog("Сохранить отчет...", // IFileDialogeService
IFileDialogeService

2022-07-14 08:39 UTC, Enzogord commented on VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
> +			Index = i;
Через конструктор устанавливать единожды индекс не очень хорошо, если начнут меняться элементы коллекции то индекс собьется. 
Предлагаю сделать подписку на изменение коллекции, и пересчитывать индекс на этом событии для всех элементов.

2022-07-14 08:39 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/CarEventViewModel.cs
> +					TabParent.AddSlaveTab(this, fineJournalViewModel);
Очень много тут всего происходит, предлагаю завернуть в отдельный метод, чтобы было удобнее читать код создания команды.

2022-07-14 08:39 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/CarEventViewModel.cs
> +					TabParent.AddSlaveTab(this, fineViewModel);
И тут тоже желательно в метод

2022-07-14 10:57 UTC, EnergyDead commented on VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
> +			Index = i;
У меня после изменения обьекта, пересобирается отчет, так что индексы тоже пересоберуться. Думаю можно было оставить, но я вынес в функцию. Если в будущем понадобиться, можно будет подписаться.

2022-07-14 13:13 UTC, Enzogord requested changes

2022-07-14 13:13 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
>                    </widget>
Это запланировано?

2022-07-14 13:14 UTC, Enzogord approved these changes

2022-07-14 13:15 UTC, merged