4058 Добавить нового виновника в недовозах
VodovozOrganization/Vodovoz pull request #1580
Opened 2022-07-20 04:45 UTC by EnergyDead

2022-07-20 14:56 UTC, Druchik submitted a review, later dismissed

2022-07-20 14:56 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Undeliveries/UndeliveredOrdersRepository.cs
> +													  "GROUP_CONCAT(CASE ?1 WHEN 'Department' THEN IFNULL(CONCAT('Отд: ', ?2), 'Отдел ВВ') WHEN 'Client' THEN 'Клиент' WHEN 'Driver' THEN 'Водитель' WHEN 'ServiceMan' THEN 'Мастер СЦ' WHEN '
Здесь лучше использовать интерполяцию строк и вставить значения виновных через nameof, как в том же UndeliveredJournalsViewModel. Чтобы можно было отследить использование этого перечисления.

2022-07-25 07:56 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/Undeliveries/UndeliveredOrdersRepository.cs
> +													  "GROUP_CONCAT(CASE ?1 WHEN 'Department' THEN IFNULL(CONCAT('Отд: ', ?2), 'Отдел ВВ') WHEN 'Client' THEN 'Клиент' WHEN 'Driver' THEN 'Водитель' WHEN 'ServiceMan' THEN 'Мастер СЦ' WHEN '
отрефакторил

2022-07-25 08:15 UTC, Art8m requested changes

2022-07-25 08:15 UTC, Art8m commented on Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.UndeliveredOrdersFilterView.cs
> +			this.ylabelGuilty.LabelProp = global::Mono.Unix.Catalog.GetString("Ответственные:");
"Ответственный" в единственном числе.

2022-07-25 08:17 UTC, Art8m commented on Vodovoz/SidePanel/InfoViews/UndeliveredOrdersPanelView.cs
> +			lblCaption.Markup = "<u><b>Сводка по недовозам\nСписок Ответственных:</b></u>";
Со строчной (маленькой) буквы.

2022-07-25 08:19 UTC, Art8m commented on VodovozReports/Reports/Logistic/AnalyticsForUndelivery.rdl
> +                      <Value>Ответственных:</Value>
Здесь тоже было с маленькой буквы.

2022-07-25 08:19 UTC, Art8m commented on VodovozReports/Reports/Logistic/AnalyticsForUndelivery.rdl
> +                      <Value>Ответственных:</Value>
и здесь

2022-07-25 08:21 UTC, Art8m approved these changes

2022-07-25 13:07 UTC, merged