4035 Отписка от массовой рассылки
VodovozOrganization/Vodovoz pull request #1582
Opened 2022-07-21 11:29 UTC by Art8m

- Добавлен справочник причин отписки от рассылки
- В механизме массовой рассылки из задачи 3886 внесены дополнение в текст письма, в том числе добавлена ссылка на отписку, которая содержит GUID записи в stored_emails для идентификации клиента на странице отписки
- Добавлен шаблон страницы отписки
В момент перехода на ссылку с отпиской добавляется запись в журнал событий рассылки
- В справочник клиента добавлено поле "дата отписки от почтовых рассылок" и кнопки "Отписать" и "Вернуть в рассылку"
- Добавлен отчет об отписке от рассылки
- Внесены дополнения на форму массовой рассылки
Возможность добавления в рассылку клиентов, которые отписались ранее, чем <N> месяцев назад. N - поле для ввода целого положительного числа
​

2022-07-25 08:05 UTC, Enzogord requested changes

2022-07-25 08:05 UTC, Enzogord commented on Services/WebApp/UnsubscribePage/Startup.cs
> +			services.AddSingleton<IEmailRepository, EmailRepository>();
Лучше бы Autofac. Чтобы потом не пришлось менять, например если захотим подключить настроенный через autofac модуль.
Пример настройки для Autofac можешь глянуть тут 
https://github.com/VodovozOrganization/Vodovoz/blob/master/RoboAtsService/Startup.cs

2022-07-25 08:07 UTC, Enzogord commented on Services/WebApp/UnsubscribePage/Startup.cs
> +			services.AddSingleton<IEmailRepository, EmailRepository>();
Еще в Program.cs есть настройка обязательная

2022-07-25 09:07 UTC, Art8m commented on VodovozViewModels/ViewModels/Reports/BulkEmailEventReportViewModel.cs
> +		private string GenerateSelectedFiltersString()
Мы же вроде договаривались сначала приватные писать, потом публичные.

2022-07-26 11:27 UTC, Art8m commented on VodovozViewModels/ViewModels/Counterparty/BulkEmailEventReasonViewModel.cs
> +	public class BulekEmailEventReasonViewModel : EntityTabViewModelBase<BulkEmailEventReason>
исправил

2022-07-26 11:27 UTC, Art8m commented on VodovozViewModels/ViewModels/Reports/BulkEmailEventReportViewModel.cs
> +			if(!IsHasDates)
переименовал

2022-07-26 11:27 UTC, Art8m commented on VodovozViewModels/ViewModels/Reports/BulkEmailEventReportViewModel.cs
> +	public class BulkEmailEventReport
вынес

2022-07-26 11:27 UTC, Art8m commented on Services/WebApp/UnsubscribePage/Startup.cs
> +			services.AddSingleton<IEmailRepository, EmailRepository>();
сделал

2022-07-26 11:28 UTC, Art8m commented on Services/WebApp/UnsubscribePage/Models/UnsubscribeViewModel.cs
> +		public int CounterpartyId { get; set; }
перенёс

2022-07-26 14:19 UTC, Enzogord approved these changes

2022-07-26 14:34 UTC, merged