4038 Введение периода действия ключевых реквизитов наших организаций
VodovozOrganization/Vodovoz pull request #1597
Opened 2022-08-04 09:10 UTC by Art8m

1. Создан виджет для версионирования 4 полей нашей организации
- Руководитель
- Главный бухгалтер
- Адрес
- Юр.адрес
2. Исправлены все места в программе для использования версий полей организации.

2022-08-08 08:58 UTC, Druchik requested changes

2022-08-08 08:58 UTC, Druchik commented on VodovozReports/Reports/Documents/ShetFactura.rdl
> +    LEFT JOIN employees leader ON leader.id = organizations.id
LEFT JOIN employees leader ON leader.id = ov.leader_id

2022-08-08 08:58 UTC, Druchik commented on VodovozViewModels/Widgets/OrganizationVersionsViewModel.cs
> +		public bool IsEditVisible { get => _isEditVisible; set => SetField(ref _isEditVisible, value); }
Чего решил все в одну строчку записать?

2022-08-08 09:00 UTC, Druchik commented
Смотрел эти отчеты (гарантия на кулер, накладная по контракту и т.д.) на момент наличия там прописанного директора или бухгалтера?

2022-08-08 11:36 UTC, Art8m commented on Vodovoz/Dialogs/Employees/M2ProxyDlg.cs
> +
Могу сделать так, но мне кажется читаемость ухудшится:
`			templatewidget.CanOpenDocument = false;

			var organizationVersion = Entity.Organization.OrganizationVersionOnDate(Entity.Date);

			if(organizationVersion == null)
			{
				MessageDialogHelper.RunErrorDialog($"На дату доверенности {Entity.Date.ToString("G")} отсутствует версия организации. Создайте версию организации.");
				return;
			}

			if(organizationVersion.Leader == null)
			{
				MessageDialogHelper.RunErrorDialog($"Не выбран руководитель в версии №{organizationVersion.Id} организации \"{Entity.Organization.Name}\"");
				return;
			}

			if(organizationVersion.Accountant == null)
			{
				MessageDialogHelper.RunErrorDialog($"Не выбран бухгалтер в версии №{organizationVersion.Id} организации \"{Entity.Organization.Name}\"");
				return;
			}

			templatewidget.CanOpenDocument = true;`

2022-08-08 11:43 UTC, Art8m commented on Vodovoz/Views/Organization/OrganizationVersionsView.cs
> +					.AddSetter((c, n) => c.BackgroundGdk = n.Id == 0 ? _greenColor : _whiteColor)
Не понял в какую функцию вынести? Если имеешь в виду во view model, то не получится, это же gdk.

2022-08-08 11:45 UTC, Art8m commented on VodovozBusiness/Domain/Organizations/OrganizationVersion.cs
> +		NominativePlural = "версии организации")]
Насколько я вижу - да

2022-08-08 14:57 UTC, Art8m commented
> Смотрел эти отчеты (гарантия на кулер, накладная по контракту и т.д.) на момент наличия там прописанного директора или бухгалтера?

Посмотрел, обсудили с Николаем, поправил вручную вбитого Сосновцева в шаблонах и отчётах.

2022-08-09 06:13 UTC, Druchik approved these changes

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Contracts/FizIPContract.rdl
> +        <Value>=")ДОГОВОР №" + {?contract_id}</Value>
Это не косяк, скобка перед договором?

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Contracts/JurIPContract.rdl
> ++{leader_last_name} + " " + {leader_name} + "." + {leader_patronymic}+ "."</Value>
Здесь все нормально? Нет переноса на новую строку?

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Contracts/JurVVContract.rdl
> +        <Value>="(ДОГОВОР №" + {?contract_id}</Value>
Здесь тот же вопрос

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Contracts/JurVVContract.rdl
> +{leader_last_name} + " " + {leader_name} + "." + {leader_patronymic}+ "."</Value>
И здесь

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Documents/EquipmentReturn.rdl
> ++{leader_last_name} + " " + {leader_name} + "." + {leader_patronymic}+ "./
Оно же

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Documents/InvoiceBarter.rdl
> ++{leader_last_name} + " " + {leader_name} + "." + {leader_patronymic}+ "./"</Value>
Так же

2022-08-09 06:13 UTC, Druchik commented on VodovozReports/Reports/Documents/InvoiceContractDoc.rdl
> +</Value>
И это

2022-08-09 07:06 UTC, EnergyDead approved these changes

2022-08-10 08:53 UTC, merged