2322 Архивация мониторинга
VodovozOrganization/Vodovoz pull request #1600
Opened 2022-08-09 08:21 UTC by Druchik

Добавлен воркер для архивации мониторинга, точек трека и удаления лишнего кэша расстояний

2022-08-09 10:58 UTC, Druchik commented
Ф Форс пуш был изменения названия коммита, ошибся в номере задачи

2022-08-09 11:03 UTC, Enzogord commented
Не обязательно писать номер задачи в коммите

2022-08-09 11:13 UTC, Druchik commented
Так удобнее смотреть из IDE и видеть сразу по какой задаче был коммит, не переходя дополнительно никуда

2022-08-09 12:26 UTC, Enzogord requested changes

2022-08-09 12:26 UTC, Enzogord commented on Services/Workers/MonitoringArchivingWorker/MonitoringArchivingWorker.cs
> +	public class MonitoringArchivingWorker : BackgroundService
А если надо запустить архивацию откуда-нибудь еще? Нет класса отвечающего за процесс архивации от и до.
Текущий класс это просто планировщик

2022-08-09 12:26 UTC, Enzogord commented on Services/Workers/MonitoringArchivingWorker/MonitoringArchivingWorker.cs
> +					_deleteDistanceCache = DateTime.Today;
Очень не удобно читаемая логика этих кэшей даты. Установка через ref тут тоже осложняет чтение.
Лучше бы было вернуть просто результат с нужными данными и с ним работать. Где каждые данные были бы подписаны по их назначению и легко читались.
Еще по имени _deleteDistanceCache не понятно что это дата.

2022-08-10 06:18 UTC, Druchik commented on Services/Workers/MonitoringArchivingWorker/MonitoringArchivingWorker.cs
> +			if(!_archiveMonitoring.HasValue || DateTime.Today > _archiveMonitoring)
Инвертировал if

2022-08-10 06:21 UTC, Druchik commented on VodovozBusiness/Domain/Logistic/TrackPointBase.cs
> +	public class TrackPointBase : PropertyChangedBase, IDomainObject
сделал

2022-08-10 06:22 UTC, Druchik commented on VodovozBusiness/EntityRepositories/HistoryChanges/OldHistoryChangesRepository.cs
> +		#endregion
лучше оставить, вдруг будут косяки и надо будет прогнать тестово архивацию

2022-08-10 06:36 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Logistic/CachedDistanceRepository.cs
> +		public static void DeleteCachedDistance(IUnitOfWork uow, DateTime dateFrom, DateTime dateTo)
убрал

2022-08-10 06:36 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Logistic/IOldTrackPointRepository.cs
> +		void TrackPointsArchiving(IUnitOfWork uow, DateTime dateTimeFrom, DateTime dateTimeTo);
переименовал

2022-08-10 06:41 UTC, Druchik commented on Services/Workers/MonitoringArchivingWorker/Program.cs
> +					services.AddHostedService<MonitoringArchivingWorker>();
Не согласен. Автофак можно и нужно использовать там где нет стоковых контейнеров, как в нашем водовозе. А в асп думаю лучше использовать дефолтную систему внедрения зависимостей, чтобы не плодить лишних ссылок на нугет пакеты и потом их поддерживать и обновлять

2022-08-10 06:48 UTC, Enzogord commented on Services/Workers/MonitoringArchivingWorker/Program.cs
> +					services.AddHostedService<MonitoringArchivingWorker>();
Очень слабая причина для того, чтобы заставлять разработчиков разбираться в 2-х системах делающих одно и тоже. Если уж начали использовать autofac, надо использовать во всем проекте

2022-08-10 07:21 UTC, Enzogord commented on Services/Workers/MonitoringArchivingWorker/Program.cs
> +					services.AddHostedService<MonitoringArchivingWorker>();
Еще у нас в некоторых библиотеках уже используются модули от автофака, которые надо будет подключать. И их будет все больше, особенно при увеличении модульности проекта. Думаю веские причины не поддерживать 2 разных фреймворка.

2022-08-10 11:05 UTC, Druchik commented on Services/Workers/MonitoringArchivingWorker/MonitoringArchivingWorker.cs
> +					_deleteDistanceCache = DateTime.Today;
Переделал

2022-08-10 11:05 UTC, Druchik commented on Services/Workers/MonitoringArchivingWorker/MonitoringArchivingWorker.cs
> +	public class MonitoringArchivingWorker : BackgroundService
добавил класс

2022-08-10 11:43 UTC, Druchik commented on Services/Workers/MonitoringArchivingWorker/Program.cs
> +					services.AddHostedService<MonitoringArchivingWorker>();
поставил автофак

2022-08-10 11:46 UTC, Druchik commented on VodovozBusiness/EntityRepositories/HistoryChanges/OldHistoryChangesRepository.cs
> +	public class OldHistoryChangesRepository : IOldHistoryChangesRepository
Репозиторий это просто работа с базой и общие методы. Выше, где ты его используешь там и реализуешь необходимый тебе алгоритм действий: архивировать без удаления/с удалением либо просто удалять данные. Если я правильно понял тебя)

2022-08-10 12:55 UTC, Druchik commented on VodovozBusiness/EntityRepositories/HistoryChanges/OldHistoryChangesRepository.cs
> +		private const string _fieldChangeAlias = "hc";
переделал

2022-08-11 07:59 UTC, Enzogord requested changes

2022-08-11 07:59 UTC, Enzogord commented on VodovozBusiness/Domain/HistoryChanges/ArchiveChangeSet.cs
> +	public class ArchiveChangeSet : ChangeSetBase
Надо ArchivedChangeSet, чтобы получилось архивированный набор изменений. С остальными сущностями так же.

2022-08-11 07:59 UTC, Enzogord commented on VodovozBusiness/VodovozBusiness.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Скорее всего кодировка сломалась

2022-08-11 08:22 UTC, Druchik commented on VodovozBusiness/Domain/HistoryChanges/ArchiveChangeSet.cs
> +	public class ArchiveChangeSet : ChangeSetBase
Поправил

2022-08-11 08:22 UTC, Druchik commented on VodovozBusiness/VodovozBusiness.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
все нормуль, там было crlf я комvитнул в lf

2022-08-11 08:41 UTC, Enzogord approved these changes

2022-08-17 05:57 UTC, merged