4037 Оповещение о перемещениях
VodovozOrganization/Vodovoz pull request #1607
Opened 2022-08-11 14:58 UTC by Druchik

2022-08-12 13:24 UTC, EnergyDead requested changes

2022-08-12 13:24 UTC, EnergyDead commented on Vodovoz/MainWindow.cs
> +	private readonly IMovementDocumentsNotificationsController _movementsNotificationsController;
может к единому стилю приведем?

2022-08-12 13:26 UTC, EnergyDead commented on VodovozBusiness/HibernateMapping/Store/WarehouseMap.cs
> +				.Column("movement_documents_notifications_subdivision_recipient_id");
какое-то очень длинное и не очевидное название

2022-08-12 13:39 UTC, Druchik commented on VodovozBusiness/HibernateMapping/Store/WarehouseMap.cs
> +				.Column("movement_documents_notifications_subdivision_recipient_id");
Я открыт для предложений)

2022-08-12 13:40 UTC, Druchik commented on Vodovoz/MainWindow.cs
> +	private readonly IMovementDocumentsNotificationsController _movementsNotificationsController;
К какому?

2022-08-12 18:44 UTC, EnergyDead commented on Vodovoz/MainWindow.cs
> +	private readonly IMovementDocumentsNotificationsController _movementsNotificationsController;
все private readonly начать с _

2022-08-15 07:02 UTC, EnergyDead approved these changes

2022-08-15 07:23 UTC, EnergyDead commented on VodovozBusiness/HibernateMapping/Store/WarehouseMap.cs
> +				.Column("movement_documents_notifications_subdivision_recipient_id");
давай оставим)

2022-08-15 07:31 UTC, Enzogord commented on Vodovoz/Dialogs/Store/WarehouseDlg.cs
>  	public partial class WarehouseDlg : QS.Dialog.Gtk.EntityDialogBase<Warehouse>
У нас уже есть WarehouseView. Может поменять на него везде, где WarehouseDlg используется и не менять старый не нужный диалог, если позволяет время.

2022-08-15 07:41 UTC, Druchik commented on Vodovoz/Dialogs/Store/WarehouseDlg.cs
>  	public partial class WarehouseDlg : QS.Dialog.Gtk.EntityDialogBase<Warehouse>
Время не позволяет, это лучше делать отдельной задачей, т.к. придется UI старые энтри заменять на минимум entityviewmodelentry

2022-08-16 07:02 UTC, merged