Feature/autocreate empty route lists
VodovozOrganization/Vodovoz pull request #1610
Opened 2022-08-16 06:57 UTC by Enzogord

2022-08-23 06:42 UTC, Druchik requested changes

2022-08-23 06:42 UTC, Druchik commented on VodovozBusiness/Models/GeoGroupVersionsModel.cs
> +				throw new InvalidOperationException($"Можно закрывать только данных части города в статусе {VersionStatus.Active.GetEnumTitle()}");
данных? Пропущено версию?

2022-08-23 06:43 UTC, Druchik commented
Последние файлы пробежал с телефона, мог чего и пропустить

2022-09-07 08:37 UTC, Enzogord commented on Vodovoz/JournalViewModels/CarJournalViewModel.cs
> +					var commonServices = ServicesConfig.CommonServices;
Там нет его

2022-09-07 08:38 UTC, Enzogord commented on Vodovoz/JournalViewModels/CarJournalViewModel.cs
> +					var commonServices = ServicesConfig.CommonServices;
Там нет его

2022-09-07 09:47 UTC, Art8m approved these changes

2022-09-07 09:59 UTC, merged