4088 Рентабельность. Точный километраж
VodovozOrganization/Vodovoz pull request #1616
Opened 2022-08-19 13:44 UTC by Art8m

1. Переделан диалог проверки километража на mvvm.
2. Добавлена форма разноса фактического километража по МЛ водителя.
3. Добавлен виджет показаний одометра для фиксирования показаний реального пробега.
4. В отчёт "Аналитика эксплуатации ТС" добавлен новый показатель "Одометр/Расхождения"

2022-08-22 08:37 UTC, Druchik requested changes

2022-08-22 08:37 UTC, Druchik commented on Vodovoz/Views/Logistic/RouteListMileageDistributionView.cs
> +			};
А что мешает Rows положить в ObservableList, чтобы не подписываться на их изменение и не обновлять модель тривьюхи?

2022-08-22 08:37 UTC, Druchik commented on Vodovoz/gtk-gui/gui.stetic
> +              <widget class="QSOrmProject.RepresentationTreeView" id="treeRouteLists">
RepresentationTreeView она там нужна? Может можно обойтись yTreeView?

2022-08-22 08:37 UTC, Druchik commented on VodovozBusiness/HibernateMapping/Logistic/Cars/CarMap.cs
> +				.OrderBy("start_date DESC");
Индекс есть на эту колонку? Скорее всего потом начнет тормозить, при большом количестве записей без него

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/CarViewModel.cs
> +			                            ?? throw new ArgumentNullException(nameof(odometerReadingsViewModelFactory));
Так два раза идет проверка на нулл. Арсений тогда не захотел менять, можешь тоже оставить, если хочешь
Вот верный вариант: (geographicGroupParametersProvider ?? throw new ArgumentNullException(nameof(geographicGroupParametersProvider)))
				.EastGeographicGroupId

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +											   throw new ArgumentNullException(nameof(deliveryRulesParametersProvider));
Если вылезает, то лучше все что дальше знака = перенести на след строку с отступом в 1 tab. Но это такое)

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +				CommonServices.InteractiveService.ShowMessage(ImportanceLevel.Warning, "Не достаточно прав. Обратитесь к руководителю.");
Вроде можно пользоваться стоковыми методами вывода сообщений

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +				OnPropertyChanged(nameof(IsAcceptAvailable));
Может стоит оповещать при изменении значения? Т.е убрать это в if?

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +					_gtkTabsOpener.OpenTrackOnMapWnd(Entity.Id);
Через навигатор же можно открывать старые диалоги

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +					_gtkTabsOpener.OpenFineDlg(this, fineReason, Entity);
Так же

2022-08-22 08:37 UTC, Druchik commented on VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
> +					newRow.Days = await ProcessOdometerDays(daysInMonth, /*odometerRouteLists,*/ carItem, startDate);
удали закомменченный код, если не нужен

2022-08-22 08:46 UTC, Enzogord requested changes

2022-08-22 08:46 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/RouteListKeepingNode.cs
> +				if(maybeLastUpdate.HasValue)
Это условие лучше инвертировать. Лестница из отступов большая уже.

2022-08-22 08:46 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +		#region Поля
Не делай пожалуйста регионы по модификаторам доступа и полям/методам/свойствам. Это бессмысленно. Чтобы изменить один аспект надо будет открыть несколько регионов. Лучше группировать по смыслу, чтобы открыть один регион и видеть все что к нему относится. Все поля наверх перед конструктором, а все мемберы в регион по смыслу.

2022-08-22 08:46 UTC, Enzogord commented on VodovozViewModels/Widgets/Cars/OdometerReadingViewModel.cs
> +
У команд нет подписок на изменение свойств от которых зависит их состояние

2022-08-22 08:48 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +				CommonServices.InteractiveService.ShowMessage(ImportanceLevel.Warning, "Не достаточно прав. Обратитесь к руководителю.");
А это какой?

2022-08-22 08:50 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/CarViewModel.cs
> +			                            ?? throw new ArgumentNullException(nameof(odometerReadingsViewModelFactory));
Я бы лучше заменил на отдельные проверки.

2022-08-22 08:51 UTC, Enzogord commented on Vodovoz/gtk-gui/gui.stetic
> +              <widget class="QSOrmProject.RepresentationTreeView" id="treeRouteLists">
Нужно yTreeView. Не надо использовать виджеты из QSOrmProject, надо наоборот менять уже имеющиеся.

2022-08-22 08:53 UTC, Enzogord commented on Vodovoz/Dialogs/OrderWidgets/GtkTabsOpener.cs
> +		}
Логика должна быть такая же. Просто диалог еще не везде удалили

2022-08-22 08:58 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +				CommonServices.InteractiveService.ShowMessage(ImportanceLevel.Warning, "Не достаточно прав. Обратитесь к руководителю.");
Были методы в каком-то из базовых классов: ShowMessage, AskQuestion, но может не здесь)

2022-08-22 12:13 UTC, Art8m commented on Vodovoz/gtk-gui/gui.stetic
> +              <widget class="QSOrmProject.RepresentationTreeView" id="treeRouteLists">
Это же вью старого журнала контроля за километражем, я его не трогал.

2022-08-22 12:13 UTC, Art8m commented on Vodovoz/JournalViewModels/RouteListJournalViewModel.cs
> +						MainClass.MainWin.NavigationManager.OpenViewModel<RouteListMileageCheckViewModel, IEntityUoWBuilder>(this, EntityUoWBuilder.ForOpen(selectedNode.Id), OpenPageOptions.AsSlave);
Так ПР не принят же ещё?

2022-08-22 12:14 UTC, Art8m commented on Vodovoz/Dialogs/OrderWidgets/GtkTabsOpener.cs
> +		}
Заменил на вьюмодель

2022-08-22 12:14 UTC, Art8m commented on Vodovoz/JournalViewers/RouteListMileageCheckView.cs
> +using Vodovoz.ViewModels.TempAdapters;
Убрал

2022-08-22 12:15 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/CarViewModel.cs
> +			                            ?? throw new ArgumentNullException(nameof(odometerReadingsViewModelFactory));
Поправил свою и Арсения

2022-08-22 12:16 UTC, Art8m commented on VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
> +					newRow.Days = await ProcessOdometerDays(daysInMonth, /*odometerRouteLists,*/ carItem, startDate);
Убрал

2022-08-22 12:16 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/RouteListKeepingNode.cs
> +				if(maybeLastUpdate.HasValue)
Инвертировал

2022-08-22 12:21 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +		#region Поля
Группировать по модификаторам/полям/методам/свойствам - согласен, не очень. Просто так сделано во многих местах по коду. Плюс помню обсуждали по мемберам как-то и приняли, что приватные наверх и т.д.  (независимо от региона), может надо бы ещё раз обсудить эти моменты, чтобы все мемберы размещать в регион по смыслу.?

2022-08-22 12:21 UTC, Art8m commented on VodovozViewModels/Widgets/Cars/OdometerReadingViewModel.cs
> +
Убрал

2022-08-22 12:49 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +					_gtkTabsOpener.OpenFineDlg(this, fineReason, Entity);
Переделал на view viewmodel

2022-08-22 12:49 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +					_gtkTabsOpener.OpenTrackOnMapWnd(Entity.Id);
В проектах с вью моделями не получится gtk диалог открыть

2022-08-22 13:27 UTC, Enzogord commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +				CommonServices.InteractiveService.ShowMessage(ImportanceLevel.Warning, "Не достаточно прав. Обратитесь к руководителю.");
Не, их уже удалили вроде, даже если не удалили, они не нужны и пользоваться ими не стоит. Тянем не всегда нужную зависимость во все классы. Лучше добавить зависимость когда нужна.

2022-08-22 14:21 UTC, Art8m commented on VodovozBusiness/HibernateMapping/Logistic/Cars/CarMap.cs
> +				.OrderBy("start_date DESC");
Добавил индекс

2022-08-22 14:21 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +				OnPropertyChanged(nameof(IsAcceptAvailable));
Сделал

2022-08-23 07:28 UTC, Druchik approved these changes

2022-08-23 07:28 UTC, Druchik commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +			LogisticianSelectorFactory = employeeJournalFactory ?.CreateWorkingEmployeeAutocompleteSelectorFactory();
А зачем здесь тернарный оператор? Ты же выше проверил на null

2022-08-23 14:43 UTC, Enzogord approved these changes

2022-09-05 06:57 UTC, Art8m commented on VodovozViewModels/ViewModels/Logistic/RouteListMileageCheckViewModel.cs
> +			LogisticianSelectorFactory = employeeJournalFactory ?.CreateWorkingEmployeeAutocompleteSelectorFactory();
Убрал

2022-09-07 19:33 UTC, merged