4098 Версионирование изображения подписи
VodovozOrganization/Vodovoz pull request #1618
Opened 2022-08-23 18:54 UTC by EnergyDead

2022-08-26 10:45 UTC, Druchik submitted a review, later dismissed
А где изменения документов? Чтобы подтягивались правильные подписи?

2022-09-01 01:11 UTC, EnergyDead commented on VodovozBusiness/Domain/StoredResources/StoredResource.cs
> +		private ImageType imageType;
весь документ без префикса, решил оставить в единой стилистике, как было

2022-09-01 01:12 UTC, EnergyDead commented on VodovozBusiness/EntityRepositories/StoredResource/StoredResourceRepository.cs
> +			return result;
Там ведь нет своего uow? Я не разобрался как свой передать

2022-09-05 13:50 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/StoredResource/StoredResourceRepository.cs
> +			return result;
Можно так грузить, но нужно понимать что когда эти сущности будут использоваться в другом UoW, надо быть уверенным что UoW из которого они были загружены должен быть закрыт. Эта схема не очень распространена у нас, у нас все обычно в одном открытом uow загружено, и может быть путаница, но у данной схемы есть много преимуществ.

2022-09-05 13:51 UTC, Art8m requested changes

2022-09-05 13:51 UTC, Art8m commented on VodovozReports/Reports/Documents/UPD.rdl
> +select * from organization_versions ov WHERE ov.id = 22
Это так нужно (id=22?)

2022-09-21 14:41 UTC, merged