4092 Сумма штрафов
VodovozOrganization/Vodovoz pull request #1669
Opened 2022-09-15 16:17 UTC by EnergyDead

2022-09-16 07:17 UTC, Art8m requested changes

2022-09-16 07:17 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/FinesJournalViewModel.cs
> +			var total = Items.Cast<FineJournalNode>().Sum(node => node.FineSumm);
Здесь посчитает только для 100 загруженных, если будет больше 100 по фильтрам.

2022-09-16 08:09 UTC, Druchik requested changes

2022-09-16 08:09 UTC, Druchik commented on VodovozViewModels/VodovozViewModels.csproj
> +    </ProjectReference>
От этой либы мы наоборот везде избавляемся. Если она прилетела из-за CurrencyWorks.GetShortCurrencyString(total), то посмотри где этот класс еще находится, его вроде переносили отдельно, может QS.Utilities

2022-09-18 18:02 UTC, EnergyDead commented on VodovozViewModels/Journals/JournalViewModels/Employees/FinesJournalViewModel.cs
> +			var total = Items.Cast<FineJournalNode>().Sum(node => node.FineSumm);
Будет подсчет только по первым 100. Он не подгружает больше, при прокрудке подгружает и пересчитывается

2022-09-19 06:16 UTC, Druchik approved these changes

2022-09-20 05:03 UTC, merged