Добавления словаря должностей и уровня квалификации в карточку сотрудника
VodovozOrganization/Vodovoz pull request #169
Opened 2021-03-05 05:47 UTC by Iamposox

2021-03-05 06:32 UTC, ShubArseniy commented on Vodovoz/CreateProjectParam.cs
>                  ;
Положи выше, у нас отдельно идут RegisterWidgetForWidgetViewModel и RegisterWidgetForTabViewModel

2021-03-05 06:37 UTC, ShubArseniy commented on Vodovoz/Dialogs/Employees/EmployeeDlg.cs
Я так понимаю здесь просто идёт выбор от 0 до 5? Лучше тогда заменить энтри на комбобокс

2021-03-05 06:39 UTC, ShubArseniy commented on Vodovoz/Dialogs/Employees/EmployeeDlg.cs
> +            }
Почему валидация не в сущности? Видел в Employee метод Validate?

2021-03-05 06:42 UTC, ShubArseniy commented on VodovozBusiness/Domain/Employees/EmployeePost.cs
> +        }
Так Name же пустой, зачем ты его показываешь? Неверное здесь должна быть запятая а не +

2021-03-05 06:44 UTC, ShubArseniy commented on VodovozBusiness/HibernateMapping/Employees/EmployeePostMap.cs
> +
employee_posts. У нас другие таблицы похожим образом называются

2021-03-05 06:47 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/EmployeePostsJournalViewModel.cs
> +        );
Должен быть EntityUoWBuilder.ForOpen(), глянь другие журналы

2021-03-05 06:49 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Employees/EmployeePostViewModel.cs
> +        }
Эта штука работает без PropertyChanged, так и должно быть?

2021-03-05 13:42 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Employees/EmployeePostViewModel.cs
> +            }
Сюда надо название свойства (nameof), а не значение

2021-03-10 08:38 UTC, efimov90 requested changes
Конфликт с другой фичей

2021-03-10 08:38 UTC, efimov90 commented on Vodovoz/Reports/Documents/UPD.rdl
> -    <DataSet Name="Stamp">
зачем это было удалено?

2021-03-10 09:01 UTC, ShubArseniy commented
Ну ты намутил тут конечно, мне кажется лучше сделать новую ветку, куда вручную снова накидать изменения. А то это прям ужас

2021-03-10 13:09 UTC, closed without merging