Дополнения по Roboats
VodovozOrganization/Vodovoz pull request #1693
Opened 2022-09-23 11:43 UTC by Enzogord

Добавлены уникальные идентификаторы звонков
Добавлен базовый класс сервиса для воркеров
Перенос комментария точки доставки в заказ

2022-09-30 12:19 UTC, Druchik requested changes

2022-09-30 12:19 UTC, Druchik commented on Services/WebApi/RoboAtsService/Monitoring/RoboatsCallRegistrator.cs
> +				.List();
Хреново, когда идет такое смешение слоев. Обращение к базе должно быть отдельно, тем более у нас под это есть репозитории и проект позволяет нормально прокинуть зависимости

2022-09-30 12:19 UTC, Druchik commented on Services/WebApi/RoboAtsService/Monitoring/RoboatsCallRegistrator.cs
> +				};
А чего не в фабрике?

2022-09-30 12:19 UTC, Druchik commented on VodovozBusiness/Domain/Roboats/RoboatsCall.cs
> +		[Display(Name = "Уникальный идентифкатор звонка")]
идентифИкатор

2022-09-30 12:19 UTC, Druchik commented on VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
> +		public int ExpressDeliveryNomenclatureId => _parametersProvider.GetIntValue("express_delivery_nomenclature_id");
А это что такое? Если быстрая доставка, то она ниже FastDeliveryNomenclatureId

2022-09-30 22:56 UTC, Enzogord commented on Services/WebApi/RoboAtsService/Monitoring/RoboatsCallRegistrator.cs
> +				};
Что должно быть в фабрике?

2022-10-03 00:10 UTC, Enzogord commented on Services/WebApi/RoboAtsService/Monitoring/RoboatsCallRegistrator.cs
> +				};
RoboatsCallDetail обычная сущность которая полностью управляется родительской сущностью, это не внешняя зависимость. Для нее фабрика не очень нужна.

2022-10-03 00:10 UTC, Enzogord commented on Services/WebApi/RoboAtsService/Monitoring/RoboatsCallRegistrator.cs
> +				.List();
Исправил

2022-10-03 00:12 UTC, Enzogord commented on VodovozBusiness/Domain/Roboats/RoboatsCall.cs
> +		[Display(Name = "Уникальный идентифкатор звонка")]
Исправлено

2022-10-03 00:14 UTC, Enzogord commented on VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
> +		public int ExpressDeliveryNomenclatureId => _parametersProvider.GetIntValue("express_delivery_nomenclature_id");
Исправил

2022-10-03 11:52 UTC, Druchik approved these changes

2022-10-03 11:52 UTC, Druchik commented on Services/WebApi/RoboAtsService/Monitoring/RoboatsCallRegistrator.cs
> +				};
Для тестов удобнее использовать фабрику, правда и тесты мы пишем редко)) Если есть желание можно это через фабрику делать, тем более, что я уже ее делал RoboatsCallFactory

2022-10-03 14:55 UTC, merged