Перевод службы правил доставки на ASP
VodovozOrganization/Vodovoz pull request #1695
Opened 2022-09-23 12:41 UTC by Enzogord

2022-09-23 13:18 UTC, Druchik requested changes

2022-09-23 13:18 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/Startup.cs
> +		}
Опять форматирование. И 53 строка не совсем не совсем понимаю зачем это, у нас свойства и так паскаль кейсом идут и он вроде там по умолчанию

2022-09-23 13:18 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/Startup.cs
> +			HistoryMain.Enable();
Я думаю это лишнее. Зачем здесь пользователь и тем более запись в историю изменений?

2022-09-23 13:18 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/Workers/DistrictCacheWorker.cs
> +		private Timer _timer;
А почему не через бэкграунд сервис? Зачем этот старый вариант? и где try catch? А если интернет закончится или база будет недоступна?

2022-09-23 13:18 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/.config/dotnet-tools.json
> +}
Это не лишнее? Что-то связанное с Entity Framework?

2022-09-23 13:28 UTC, Enzogord commented on Services/WebApi/DeliveryRulesService/Startup.cs
> +		}
По умолчанию CamelCase

2022-09-23 13:29 UTC, Enzogord commented on Services/WebApi/DeliveryRulesService/Startup.cs
> +		}
PascalCase надо, чтобы имена в JSON были такие же как и в коде

2022-09-23 13:31 UTC, Enzogord commented on Services/WebApi/DeliveryRulesService/.config/dotnet-tools.json
> +}
По умолчанию было создано

2022-09-23 13:32 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/Startup.cs
> +		}
Так оно вроде так и идет, когда реализовывал СБП, все паскалем шло, хотя может я чего попутал))

2022-09-23 13:42 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/Controllers/DeliveryRulesController.cs
> +			fastDeliveryAvailabilityHistory.District = _deliveryRepository.GetDistrict(uow, latitude, longitude);
Пропустил, сейчас же отключили это обращение к Яндексу, решили включить вновь?

2022-09-23 13:47 UTC, Druchik commented on Services/WebApi/DeliveryRulesService/Controllers/DeliveryRulesController.cs
> +			fastDeliveryAvailabilityHistory.District = _deliveryRepository.GetDistrict(uow, latitude, longitude);
И если он останется, не лучше ли дефолтную реализацию клиента сделать?

2022-11-01 06:55 UTC, Enzogord commented on Services/WebApi/DeliveryRulesService/DTO/DeliveryInfoDTO.cs
> +        public IList<WeekDayDeliveryInfoDTO> WeekDayDeliveryInfos { get; set; }
Исправлено

2022-11-01 06:55 UTC, Enzogord commented on Services/WebApi/DeliveryRulesService/DTO/DeliveryRuleDTO.cs
> +		public string Price { get; set; }
Исправлено

2022-11-01 06:55 UTC, Enzogord commented on Services/WebApi/DeliveryRulesService/DTO/DeliveryRulesDTO.cs
> +		public IList<WeekDayDeliveryRuleDTO> WeekDayDeliveryRules { get; set; }
тоже

2022-11-01 10:11 UTC, Art8m approved these changes

2022-11-02 07:01 UTC, Druchik approved these changes

2022-11-02 07:33 UTC, merged