Реализация оплаты по QR коду для Робоатс
VodovozOrganization/Vodovoz pull request #1728
Opened 2022-10-11 13:40 UTC by Enzogord

2022-12-22 11:40 UTC, efimov90 requested changes

2022-12-22 11:40 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/Sms.Internal.Service/Startup.cs
> +	public class Startup
Табы/пробелы

2022-12-22 11:40 UTC, efimov90 commented on Source/Libraries/Core/Business/Vodovoz.Settings.Database/Setting.cs
> +        public virtual bool IsExpired {
У нас разве не было закреплено, что скобки с новой строки?

2022-12-22 11:40 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/FastPaymentSender.cs
> +        {
Табы пробелы

2022-12-22 12:22 UTC, Enzogord commented on Source/Libraries/Core/Business/Vodovoz.Settings.Database/Setting.cs
> +        public virtual bool IsExpired {
Не однострочные

2022-12-22 12:38 UTC, efimov90 requested changes

2022-12-22 12:38 UTC, efimov90 commented on Source/Libraries/Core/Business/Vodovoz.Settings.Database/Setting.cs
> +        public virtual bool IsExpired {
как раз IsExpired не однострочный

2022-12-23 04:01 UTC, Enzogord commented
https://github.com/VodovozOrganization/Vodovoz/pull/1728/commits/daaa1f02c19c81c5d289c91031683430c2b3f4ca#diff-bd82bd91ea95bec3469156fdabe68e018b790daa76a3414b56e3fa779e5c1342

2022-12-23 07:05 UTC, efimov90 approved these changes

2022-12-23 07:10 UTC, merged