4140 TrueMarkApi
VodovozOrganization/Vodovoz pull request #1795
Opened 2022-11-15 12:27 UTC by Art8m

2022-11-15 13:41 UTC, Enzogord requested changes

2022-11-15 13:41 UTC, Enzogord commented on Source/Applications/Backend/WebAPI/TrueApi/Dto/Documents/GtinReceiptDocumentDto.cs
> +	public class Product
Его лучше вынести в свой файл

2022-11-15 13:41 UTC, Enzogord commented on Source/Vodovoz.sln
> +		{3960779C-8E5E-48EC-84D5-9D2FA0B027E1}.WinDesktop|x86.Build.0 = Debug|Any CPU
Перепроверь конфиг, у тебя эта служба похоже включена во всех сборках

2022-11-15 13:42 UTC, Enzogord commented
И название для API надо более точное дать, а то True ни о чем не говорит

2022-11-16 06:33 UTC, Art8m commented on Source/Applications/Backend/WebAPI/TrueApi/Dto/Documents/GtinReceiptDocumentDto.cs
> +	public class Product
Вынем

2022-11-16 06:33 UTC, Art8m commented on Source/Vodovoz.sln
> +		{3960779C-8E5E-48EC-84D5-9D2FA0B027E1}.WinDesktop|x86.Build.0 = Debug|Any CPU
Убрал

2022-11-16 06:33 UTC, Art8m commented
> И название для API надо более точное дать, а то True ни о чем не говорит

Поменял

2022-11-16 06:43 UTC, Enzogord approved these changes

2022-11-16 06:44 UTC, merged