4230 Печать группы путевых листов
VodovozOrganization/Vodovoz pull request #1970
Opened 2023-01-31 13:48 UTC by N-Sem

Тестирование необходимо производить с обновленной моделью базы данных https://github.com/VodovozOrganization/Vodovoz/pull/1967

В этой модели добавлен столбец address в таблице Subdivisions. Также для того, чтобы адрес отображался в групповом отчете, необходимо для подразделений внести значение адреса в БД.

2023-01-31 14:05 UTC, Druchik requested changes

2023-01-31 14:05 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Subdivisions/SubdivisionMap.cs
> +			Map(x => x.Address).Column("address");
Надо бы Map к Map подкинуть, а не в конец размещать

2023-01-31 14:05 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> +  </widget>
Это скорее всего мусор

2023-01-31 14:05 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Widget.cs
> +}
Мусор?

2023-01-31 14:05 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Vodovoz.csproj
> +    <Compile Include="gtk-gui\Vodovoz.ReportsParameters.Widget.cs" />
Мусор?

2023-01-31 14:12 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Subdivisions/SubdivisionRepository.cs
> +			return availableSubdivisions;
Чего-то мне кажется, что запрос неверный. Как минимум надо выбирать действующие версии авто, скорее всего. Да и подразделения возможно выдернуть в этом же запросе, чтобы линком не прогонять коллекцию, но это не точно)

2023-01-31 14:24 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/MainWindow.cs
>  		);
Делалось по аналогии с имеющимся отчетом

2023-01-31 14:24 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/WayBillReportGroupPrint.cs
> +			enumcheckCarOwnTypeOneDayGroupReport.CheckStateChanged += EnumcheckCarOwnTypeOneDayGroupReport_CheckStateChanged;
Исправлю

2023-01-31 14:24 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/WayBillReportGroupPrint.cs
> +				MessageDialogHelper.RunErrorDialog("Недостаточно данных для отчета");
Исправлю

2023-01-31 14:24 UTC, N-Sem commented on Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Subdivisions/SubdivisionMap.cs
> +			Map(x => x.Address).Column("address");
Исправлю

2023-01-31 14:24 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> +  </widget>
Мусор, удалю

2023-01-31 14:25 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Widget.cs
> +}
Мусор, удалю

2023-01-31 14:25 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/Vodovoz.csproj
> +    <Compile Include="gtk-gui\Vodovoz.ReportsParameters.Widget.cs" />
Мусор, удалю

2023-01-31 14:30 UTC, N-Sem commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Subdivisions/SubdivisionRepository.cs
> +			return availableSubdivisions;
Действующая версия авто, имеется в виду, что не в архиве? Если да, то такая проверка есть !car.IsArchive
и выбирается из списка типов и принадлежностей.
.WhereRestrictionOn(() => carModel.CarTypeOfUse).IsIn(carTypeOfUses)
.WhereRestrictionOn(() => carVersion.CarOwnType).IsIn(carOwnTypes)

Что касается выдернуть из подразделения в том же запросе, тут тогда еще подумаю.

2023-01-31 14:45 UTC, Druchik commented
Ах да, отвлекся и забыл написать. Там в самом начале стетика изменения не мусор ли тоже?

2023-01-31 14:48 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Subdivisions/SubdivisionRepository.cs
> +			return availableSubdivisions;
не, имеется в виду, что у версии нет EndDate

2023-02-01 06:03 UTC, Druchik approved these changes

2023-02-01 06:03 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/WayBillReportGroupPrint.cs
> +				_interactiveService.ShowMessage(ImportanceLevel.Info, info, "Ошибка формирования отчета");
Там был Warning, а ты поставил Info: ImportanceLevel.Info, не критично, но лучше исправить

2023-02-01 06:16 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/WayBillReportGroupPrint.cs
> +			enumcheckCarOwnTypeOneDayGroupReport.CheckStateChanged += EnumcheckCarOwnTypeOneDayGroupReport_CheckStateChanged;
Исправил

2023-02-01 06:16 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/WayBillReportGroupPrint.cs
> +				MessageDialogHelper.RunErrorDialog("Недостаточно данных для отчета");
Исправил

2023-02-01 06:17 UTC, N-Sem commented on Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Subdivisions/SubdivisionMap.cs
> +			Map(x => x.Address).Column("address");
Исправил

2023-02-01 06:17 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> +  </widget>
Удалил

2023-02-01 06:17 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Widget.cs
> +}
Удалил

2023-02-01 06:20 UTC, N-Sem commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Subdivisions/SubdivisionRepository.cs
> +			return availableSubdivisions;
Добавил проверку EndDate.
У меня не получилось выдергивать прямо из запроса именно объект Subdivisions без второго прогона по новой коллекции.

2023-02-01 06:23 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/WayBillReportGroupPrint.cs
> +				_interactiveService.ShowMessage(ImportanceLevel.Info, info, "Ошибка формирования отчета");
Исправил

2023-02-01 10:58 UTC, merged