4246 Отображение количества зарезервированных остатков
VodovozOrganization/Vodovoz pull request #1980
Opened 2023-02-02 09:37 UTC by N-Sem

2023-02-02 09:48 UTC, efimov90 requested changes

2023-02-02 09:48 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> -                <property name="Active">True</property>
точно?

2023-02-02 09:48 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> +                            <property name="Active">True</property>
точно?

2023-02-02 09:48 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> +				.Where(() => orderAlias.OrderStatus == OrderStatus.Accepted
в переменную и через проекцию In

2023-02-02 11:52 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> -                <property name="Active">True</property>
Поправил

2023-02-02 11:52 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/gtk-gui/gui.stetic
> +                            <property name="Active">True</property>
Поправил

2023-02-02 12:44 UTC, efimov90 approved these changes

2023-02-03 06:11 UTC, efimov90 requested changes

2023-02-03 06:11 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> +			//Флаг типа отчета для экспорта в Эксель. Если выполнять проверку по ShowReserve,
Такого в принципе не должно происходить, отчет не должен генерироваться на основе UI, только на значениях которые передаются при генерации

2023-02-03 06:11 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> +			//Флаг типа отчета для экспорта в Эксель. Если выполнять проверку по ShowReserve,
ActionGenerateReportAsync должен принимать параметры на основе которых генерируется отчет

2023-02-03 06:55 UTC, efimov90 approved these changes

2023-02-03 12:11 UTC, merged