4227 Изменение правил для цен доставки
VodovozOrganization/Vodovoz pull request #2006
Opened 2023-02-16 04:36 UTC by N-Sem

Удален старый журнал и диалог для правил цен доставки и созданы новые .
Теперь в правилах цен доставки можно отдельно указывать количество бутылей объемом менее 19 литров, раньше их количество рассчитывалось с использованием коэффициентов относительно 19 литровых бутылей.
Удалены из интерфейса вывод и возможность ввода правила доставки для бутылей объемом 0,6 л.

2023-02-16 06:53 UTC, efimov90 requested changes

2023-02-16 06:53 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Sale/District.cs
> +					//result.AppendLine("минимум 0,6л: " + weekRules.Select(x => x.DeliveryPriceRule.Water600mlCount).Min());
Если не нужно - удалить

2023-02-16 06:53 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Sale/District.cs
> +					//result.AppendLine("минимум 0,6л: " + ObservableCommonDistrictRuleItems
Если не нужно - удалить

2023-02-16 07:23 UTC, efimov90 approved these changes

2023-02-16 07:40 UTC, Druchik requested changes

2023-02-16 07:40 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Views/Logistic/DistrictsSetView.cs
>  				Tab.TabParent.AddSlaveTab(this.Tab, selectRules);
Здесь же есть вью модель, если я не ошибаюсь. Можно вынести этот код в отдельную команду там.
Tab.TabParent.AddSlaveTab(this.Tab, selectRules) - это лишнее ты же открываешь вкладку через навигатор;
Также здесь открывается вкладка как подчиненная страница asSlave, значит в навигаторе надо указать тоже самое, т.е. в параметрах будет указана ViewModel и OpenPageOptions.AsSlave

2023-02-16 07:40 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Views/Logistic/DistrictsSetView.cs
>  				Tab.TabParent.AddSlaveTab(this.Tab, selectRules);
аналогично

2023-02-16 07:40 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Sale/DeliveryPriceRuleJournalViewModel.cs
> +		public int Water19LCount { get; set; }
Забыл Title определить из родительского класса. Иначе будет падать в Entry. Тут либо Name либо Description, а может что-то другое, тебе должно быть виднее

2023-02-16 07:40 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Sale/DeliveryPriceRule.cs
> +				//sb.Append($" или 600мл б. < {water600mlCount}шт.");
Забыл удалить?

2023-02-16 07:40 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Sale/DeliveryPriceRuleViewModel.cs
> +		}
Зачем здесь все эти свойства и ниже которые? Ты же во вьюхе напрямую к Entity забиндился

2023-02-17 12:35 UTC, N-Sem commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Sale/DeliveryPriceRuleViewModel.cs
> +		private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
К сожалению, через NavigationManager не получится.

2023-02-17 12:47 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/Views/Logistic/DistrictsSetView.cs
>  				Tab.TabParent.AddSlaveTab(this.Tab, selectRules);
Исправил

2023-02-17 12:47 UTC, N-Sem commented on Source/Applications/Desktop/Vodovoz/Views/Logistic/DistrictsSetView.cs
>  				Tab.TabParent.AddSlaveTab(this.Tab, selectRules);
Исправил

2023-02-17 12:47 UTC, N-Sem commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Sale/DeliveryPriceRuleJournalViewModel.cs
> +		public int Water19LCount { get; set; }
Добавил

2023-02-17 12:47 UTC, N-Sem commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Sale/DeliveryPriceRule.cs
> +				//sb.Append($" или 600мл б. < {water600mlCount}шт.");
Удалил

2023-02-17 12:47 UTC, N-Sem commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Sale/DeliveryPriceRuleViewModel.cs
> +		}
Удалил

2023-02-17 14:12 UTC, Druchik approved these changes

2023-03-09 14:28 UTC, merged