4072 Операции со свободными остатками МЛ
VodovozOrganization/Vodovoz pull request #2047
Opened 2023-03-02 09:51 UTC by Art8m

2023-03-10 06:27 UTC, efimov90 requested changes
В основном стиль
И пара вопросов по логике
Во всех маппингах, которые правил - проверить табуляцию через табы, LF, пустая строка в конце

2023-03-10 06:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
> +
Лишнее?

2023-03-10 06:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/CarUnloadDocumentDlg.cs
> +			returnsreceptionview.Sensitive =
Лишний пробел?

2023-03-10 06:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/CarUnloadDocumentDlg.cs
> +					if(item.DeliveryFreeBalanceOperation != null && item.DeliveryFreeBalanceOperation.Amount != -tempItem.Amount)
Скобки

2023-03-10 06:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
> +using Order = Vodovoz.Domain.Orders.Order;
Для студии Ctrl+R, G

2023-03-10 06:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
> +		decimal amount;
модификатор доступа, нарушение имени

2023-03-10 06:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
> +		decimal expectedAmount;
тоже самое

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Controllers/AddressTransferDocumentController.cs
> +	        }
либо скобки лишние либо отступ, не понятно по куску кода

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Discrepancy.cs
>  	public class Discrepancy
оно точно не должно быть INotifyPropertyChanged?

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteList.cs
> +			var allGoodsTransferedToAnotherDrivers = _routeListRepository.AllGoodsTransferredToAnotherDrivers(UoW, this, Nomenclature.GetCategoriesForShipment(), AddressTransferType.FromDriverToDriver);
Студия - "свернуть все параметры и добавить отступы к ним"

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Delivery/DeliveryRepository.cs
> +					.SelectSum(()=> freeBalanceOperation.Amount).WithAlias(() => ordersAmountAlias.Amount))
пробел перед стрелкой

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.Where(r => !r.WasTransfered || r.AddressTransferType.IsIn(new[] { AddressTransferType.NeedToReload, AddressTransferType.FromFreeBalance }))
Если это осмысленный список - вынести куда-нибудь

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.Where(r => !r.WasTransfered || r.AddressTransferType.IsIn(new[] { AddressTransferType.NeedToReload, AddressTransferType.FromFreeBalance }))
тот же список

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.Where(r => !r.WasTransfered || r.AddressTransferType.IsIn(new[] { AddressTransferType.NeedToReload, AddressTransferType.FromFreeBalance }))
тот же список

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.WhereRestrictionOn(() => addressAlias.Status).Not.IsIn(new[] { RouteListItemStatus.Transfered});
пробел в конце

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.WhereRestrictionOn(() => addressAlias.Status).Not.IsIn(new[] { RouteListItemStatus.Transfered})
пробел в конце

2023-03-10 06:27 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				item.Amount <= freeBalance.SingleOrDefault(b => b.NomenclatureId == item.NomenclatureId)?.Amount);
не будет nullref? не должно быть значения по умолчанию 0 в конце?

2023-03-10 08:07 UTC, Art8m commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Discrepancy.cs
>  	public class Discrepancy
Пока не нужно было

2023-03-10 09:20 UTC, Art8m commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				item.Amount <= freeBalance.SingleOrDefault(b => b.NomenclatureId == item.NomenclatureId)?.Amount);
- nullref не будет, тут amount не nullable, вернётся default 0
- по логике всё нормально, когда null, то вернётся false (нет остатков по тмц)

2023-03-10 10:53 UTC, Art8m commented
> В основном стиль И пара вопросов по логике Во всех маппингах, которые правил - проверить табуляцию через табы, LF, пустая строка в конце

Поправил

2023-03-22 12:15 UTC, efimov90 requested changes

2023-03-22 12:15 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
> +        void YtreeviewRLTo_OnSelectionChanged(object sender, EventArgs e)
табы

2023-03-22 12:19 UTC, Art8m commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
> +        void YtreeviewRLTo_OnSelectionChanged(object sender, EventArgs e)
поправил

2023-03-22 12:21 UTC, merged