4298 Комбобокс в фильтрах изменить на выбор из справочника
VodovozOrganization/Vodovoz pull request #2101
Opened 2023-03-20 11:20 UTC by N-Sem

Комбобоксы выбора подразделения в фильтре журнала недовозов и журнала рекламаций, комбобокс выбора типа рекламации в журнале рекламаций заменены на выбор из справочников.

2023-03-21 06:44 UTC, efimov90 approved these changes

2023-03-21 06:51 UTC, Druchik requested changes

2023-03-21 06:51 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Filters/GtkViews/ComplaintFilterView.cs
> +			entityentryCurrentSubdivision.Binding.AddBinding(ViewModel, vm => vm.CanChangeSubdivision, w => w.Sensitive).InitializeFromSource();
не надо два раза на один элемент вызывать инициализацию биндинга. Накидай все биндинги, а в конце вызови один раз InitializeFromSource()

Т.е. как-то так:
entityentryCurrentSubdivision.Binding
.AddBinding(ViewModel, vm => vm.CurrentUserSubdivision, w => w.Subject)
.AddBinding(ViewModel, vm => vm.CanChangeSubdivision, w => w.Sensitive)
.InitializeFromSource();

Или если источник один, можно так:
entityentryCurrentSubdivision.Binding
.AddSource(ViewModel)
.AddBinding(vm => vm.CurrentUserSubdivision, w => w.Subject)
.AddBinding(vm => vm.CanChangeSubdivision, w => w.Sensitive)
.InitializeFromSource();

2023-03-21 06:51 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Views/Complaints/GuiltyItemView.cs
> +			entityentrySubdivision.Binding.AddBinding(ViewModel, vm => vm.CanChooseSubdivision, w => w.Visible).InitializeFromSource();
Аналогично

2023-03-27 06:18 UTC, Druchik approved these changes

2023-03-28 11:21 UTC, merged