4309 Hotfix Индивидуальный радиус для автомобиля доставки за час
VodovozOrganization/Vodovoz pull request #2158
Opened 2023-04-06 09:00 UTC by N-Sem

Радиус доставки за час для каждого маршрутного листа можно задавать индивидуально.

2023-04-06 12:39 UTC, Druchik approved these changes

2023-04-10 02:23 UTC, efimov90 requested changes

2023-04-10 02:23 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Logistic/RouteListFastDeliveryMaxDistanceViewModel.cs
> +		private static NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();
ILogger<RouteListFastDeliveryMaxDistanceViewModel>

2023-04-10 02:23 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Tools/Logistic/DistanceCalculator.cs
> +		public static double CalculateCoveragePercent(ICollection<Geometry> districtsBorders, ICollection<DriverPositionWithFastDeliveryRadius> drivers)
Почему ICollection, а не IEnumerable?

2023-04-10 02:23 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Logistic/CarsMonitoringViewModel.cs
> +				query.Where(rl => rl.Status == RouteListStatus.EnRoute);
Лишние табы в конце строки

2023-04-10 09:12 UTC, efimov90 requested changes

2023-04-10 09:12 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Logistic/RouteListFastDeliveryMaxDistanceViewModel.cs
> +		private static ILogger _logger = NLog.LogManager.GetCurrentClassLogger();
private readonly ILogger<RouteListFastDeliveryMaxDistanceViewModel>
и иньекцию через конструктор

2023-04-10 09:43 UTC, efimov90 approved these changes

2023-04-12 07:25 UTC, merged