4327 добавил разделение по чекам у заказов с 128+ маркировками
VodovozOrganization/Vodovoz pull request #2204
Opened 2023-04-19 07:28 UTC by Druchik

- добавил разделение по чекам у больших заказов с маркировкой
- добавил обработчик для доставляемых заказов, чтобы отлавливать заказы закрытые не через вод приложение

2023-04-19 09:45 UTC, efimov90 requested changes

2023-04-19 09:45 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +				Logger.LogError(ex, $"Ошибка создания чека для заказа самовывоза {OrderId}.");
строка формата

2023-04-19 09:46 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +			var codesInReceipt = default(int);
лучше int codesInReceipt = default;
хотя это вкусовщина

2023-04-19 09:47 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +			//ошибка пула кода не важна для основной работы
тоже самое

2023-04-19 09:48 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +				Logger.LogError(ex, "Ошибка отката пула кодов.");
Сомнительный подходи с ошибками, если оно не так важно

2023-04-19 09:49 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreatorFactory.cs
> +			var creator = new SelfdeliveryReceiptCreator(
очень опасно у сервиса должен быть свой логгер а не из этого класса, почему не резолвится тут вместо new?

2023-04-19 09:51 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/ReceiptPreparer.cs
> +			var codesToSkip = (CashReceipt.MaxMarkCodesInReceipt * receipt.InnerNumber ?? 0) - CashReceipt.MaxMarkCodesInReceipt;
будет nullref

2023-04-19 09:54 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/ReceiptPreparer.cs
> +			var receiptNumber = receipt.InnerNumber ?? 0;
nullref

2023-04-20 06:02 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/ReceiptPreparer.cs
> +			var receiptNumber = receipt.InnerNumber ?? 0;
не должно

2023-04-20 06:02 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/ReceiptPreparerFactory.cs
> +				_logger, _uowFactory, codePool, _codeChecker, _cashReceiptRepository, _organizationRepository, _cashReceiptFactory,
также не погружался

2023-04-20 06:02 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/ReceiptPreparer.cs
> +			var codesToSkip = (CashReceipt.MaxMarkCodesInReceipt * receipt.InnerNumber ?? 0) - CashReceipt.MaxMarkCodesInReceipt;
не должно

2023-04-20 06:03 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreatorFactory.cs
> +			var creator = new SelfdeliveryReceiptCreator(
не лез в архитектуру

2023-04-20 06:03 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +				Logger.LogError(ex, "Ошибка отката пула кодов.");
не мое, сюда не лез

2023-04-20 06:03 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +			var codesInReceipt = default(int);
оставил

2023-04-20 06:03 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
> +				Logger.LogError(ex, $"Ошибка создания чека для заказа самовывоза {OrderId}.");
поправил

2023-04-20 06:17 UTC, efimov90 approved these changes

2023-04-20 06:17 UTC, merged