4305 Api для обработки запросов поиска кодов УПД от ЕАрхива
VodovozOrganization/Vodovoz pull request #2289
Opened 2023-05-16 07:58 UTC by N-Sem

API обрабатывает GRPC запросы:
- поиска контрагентов по подстроке в названии контрагента
- поиска точек доставки выбранного контрагента
- поиска кодов УПД для выбранного контрагента и точки доставки

2023-05-17 07:54 UTC, Enzogord requested changes

2023-05-17 07:54 UTC, Enzogord commented on Source/Applications/Backend/WebAPI/EarchiveApi/Protos/earchive_upd.proto
> +}
Имена свойств поправь по стандартам C#

2023-05-17 07:54 UTC, Enzogord commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +				var end_date =	request.EndDate.ToDateTime().Year < 1971
camelCase

2023-05-17 07:54 UTC, Enzogord commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +	}
Потом править эти запросы будет большая боль.
Используй лучше 
@"
    Any code here
"

2023-05-17 07:54 UTC, Enzogord commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +			_connectionString = connectionStringBuilder.GetConnectionString(true);
Это лучше вынести в Startup а сюда передавать уже сконфигурированную строку подключения или уже провайдер/фабрику подключений если есть.

2023-05-18 12:17 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/EarchiveApi/Startup.cs
> +			connectionStringBuilder.DefaultCommandTimeout = 5;
В конфигурацию

2023-05-18 12:52 UTC, efimov90 requested changes

2023-05-18 12:52 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +				_logger.LogError(ex, $"Ошибка при выполнении поиска кода УПД. Параметры запроса: Id контрагента = {request.CounterpartyId}, Id точки доставки = {request.DeliveryPointId}, дата начала = {request.S
структурные логи

2023-05-18 12:52 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +					.WaitAndRetryAsync(1, (_) => TimeSpan.FromSeconds(1));
из конфигурации таймаута БД

2023-05-18 12:52 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +					.WaitAndRetryAsync(1, (_) => TimeSpan.FromSeconds(1));
таймаут из конфигурации БД

2023-05-18 12:52 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +					.WaitAndRetryAsync(1, (_) => TimeSpan.FromSeconds(1));
из конфигурации таймаут

2023-05-18 12:52 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/EarchiveApi/Services/EarchiveUpdService.cs
> +				_logger.LogInformation($"Запрос поиска контрагента не выполнен. Получен либо пустой запрос, либо кол-во симоволов меньше {minNameSubstringLength}");
в методе логгера - нельзя использовать интерполяцию, только строку формата

2023-05-29 06:45 UTC, efimov90 approved these changes

2023-06-06 08:27 UTC, Enzogord requested changes

2023-06-06 08:27 UTC, Enzogord commented on Source/Applications/Backend/WebAPI/EarchiveApi/Dockerfile
> +EXPOSE 7101
Думаю что expose порта тут не нужен. И его лучше определить в стеке

2023-06-06 08:27 UTC, Enzogord commented on Source/Vodovoz.sln
>  	EndGlobalSection
Убери сборку этого проекта, там где он не нужен

2023-06-06 08:57 UTC, Enzogord approved these changes

2023-06-06 10:22 UTC, merged