4189 Поэкземплярный учет
VodovozOrganization/Vodovoz pull request #2311
Opened 2023-05-25 09:52 UTC by Druchik

2023-05-25 11:43 UTC, efimov90 requested changes

2023-05-25 11:43 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +				() => FluentColumnsConfig<InventoryInstancesJournalNode>.Create()
в Registrar

2023-05-25 11:43 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Views/Warehouse/Documents/InventoryDocumentView.cs
> +			/*ychkSortNomenclaturesByTitle.Binding
ненужный код

2023-05-25 11:43 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseJournalViewModel.cs
> +		private void CreateFilter(Action<WarehouseJournalFilterViewModel> filterParams)
Возвращать VM и вернуть readonly

2023-05-25 11:43 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseJournalViewModel.cs
> +	public class WarehouseJournalFilterViewModel : FilterViewModelBase<WarehouseJournalFilterViewModel>, IJournalFilterViewModel
В новый файл

2023-05-25 11:43 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> +						var employeeName = CustomProjections.Concat_WS(
проекция под employee

2023-05-25 11:43 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
>  	public class BalanceSummaryRow
в другой файл

2023-05-25 12:06 UTC, Enzogord requested changes

2023-05-25 14:22 UTC, efimov90 requested changes

2023-05-25 14:22 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Documents/InventoryDocuments/InventoryDocumentItemMap.cs
> +			//Map(x => x.SumOfDamage).Column("sum_of_damage");
комментарий

2023-05-31 09:31 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Views/Warehouse/InventoryDocumentView.cs
> +		}
оставил как есть

2023-05-31 09:32 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Infrastructure/GdkColors.cs
> +		public static Color RedColor2 { get; } = new Color(0xfe, 0x5c, 0x5c);
Думал над другим именем, но ничего не пришло в голову. Если только код цвета сюда пихать

2023-05-31 10:08 UTC, Enzogord approved these changes

2023-05-31 10:24 UTC, efimov90 requested changes

2023-05-31 10:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseJournalViewModel.cs
> +		private WarehouseJournalFilterViewModel _filterViewModel;
лучше вернуть ридонли

2023-05-31 10:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/BalanceSummaryRow.cs
> +	public class BalanceSummaryRow
Это не нода? Не должен быть INotifyPropertyChanged? или это отчет?

2023-05-31 10:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/NomenclatureStorageIds.cs
> +		public NomenclatureStorageIds(int nomenclatureId, int storageId)
не лучше тогда заприватить конструктор и сделать фабричный метод?
и это точно структура?

2023-05-31 10:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> +				bulkBalanceByWarehousesQuery?.WhereRestrictionOn(() => nomAlias.ProductGroup.Id).IsIn(groupsIds);
тут нуллрефа не будет от nomAlias.ProductGroup*

2023-05-31 10:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Warehouses/Documents/InventoryDocumentViewModel.cs
> +		private readonly StoreDocumentHelper _storeDocumentHelper;
почему не интерфейс?

2023-05-31 10:30 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/CreateProjectParam.cs
> +			builder.RegisterType<UserSettingsGetter>().AsImplementedInterfaces();
поправил

2023-05-31 10:30 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/CarUnloadDocumentDlg.cs
> +				var item = Entity.Items.FirstOrDefault(x => x.GoodsAccountingOperation.Id > 0 && x.GoodsAccountingOperation.Id == tempItem.MovementOperationId);
нет

2023-05-31 10:32 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/TransferOperationDocumentItemView.cs
> +			var vm = MainClass.MainWin.NavigationManager
этот код не используется

2023-05-31 10:32 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/ExternalCounterpartiesMatchingJournalRegistrar.cs
> +					.AddTextRenderer(node => node.Created.ToString("g"))
нулл рефа не будет оно не Nullable

2023-05-31 10:32 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/InventoryNomenclaturesJournalRegistrar.cs
> +					.AddTextRenderer(node => node.Category.GetEnumTitle())
нет

2023-05-31 10:33 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +							var color = GdkColors.WhiteColor;
нужно думать

2023-05-31 10:33 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseJournalViewModel.cs
> +		private WarehouseJournalFilterViewModel _filterViewModel;
не хочу тратить время

2023-05-31 10:35 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/NomenclatureStorageIds.cs
> +		public NomenclatureStorageIds(int nomenclatureId, int storageId)
Точно структура. Пока не буду менять

2023-05-31 10:35 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Warehouses/InventoryDocumentViewModel.cs
> +			if(Entity.InstanceItems.Any() && Entity.InventoryDocumentStatus != InventoryDocumentStatus.Confirmed)
нет

2023-05-31 10:38 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> +				bulkBalanceByWarehousesQuery?.WhereRestrictionOn(() => nomAlias.ProductGroup.Id).IsIn(groupsIds);
нет

2023-05-31 10:42 UTC, efimov90 approved these changes

2023-05-31 10:44 UTC, merged