4409 Интеграция цен и остатков
VodovozOrganization/Vodovoz pull request #2660
Opened 2023-09-07 06:46 UTC by Druchik

2023-09-07 11:53 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +		[Route("GetNomenclaturesPricesAndStocks")]
не помню почему так пошло, но разве нельзя объединять в HttpGet("GetNomenclaturesPricesAndStocks")?

2023-09-07 11:55 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +					_logger.LogInformation("Превышен интервал обращений для источника {Source}", sourceName);
А точно тут не должно быть кэширование для этого?

2023-09-07 11:55 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +				var passedTime = lastRequestTime == now ? 0d : (now - lastRequestTime).TotalMinutes;
нейминг не отражает сути

2023-09-07 11:55 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +				var passedTime = lastRequestTime == now ? 0d : (now - lastRequestTime).TotalMinutes;
и почему не оперировать спанами?

2023-09-07 11:58 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/NomenclatureFactory.cs
> +			return parametersData.NomenclatureOnlineParametersNodes.Select(parametersNode => new NomenclaturePricesAndStockDto
Конвертер или метод расширения не лучше?

2023-09-07 11:59 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/NomenclatureFactory.cs
> +			return new NomenclaturesPricesAndStockDto
Напрашивается метод расширения для маппинга

2023-09-07 11:59 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/NomenclatureFactory.cs
> +		private IList<NomenclaturePricesDto> CreateNomenclaturePricesDto(
тут точно нужен лист? не пойдет IEnumerable?

2023-09-07 12:00 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Middleware/ResponseLoggingMiddleware.cs
> +			_logger = loggerFactory.CreateLogger<ResponseLoggingMiddleware>();
А это что за прикол? почему не иньектится логгер?

2023-09-07 12:02 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Middleware/ResponseLoggingMiddleware.cs
> +		public async Task Invoke(HttpContext context)
Могу ошибаться но тут вроде должен быть  HttpContextAccessor

2023-09-07 12:03 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Models/NomenclatureModel.cs
> +		private readonly IUnitOfWork _uow;
нормальный нейминг пожалуйста

2023-09-07 12:03 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Models/NomenclatureModel.cs
> +			IUnitOfWork uow,
нормальный нейминг пожалуйста

2023-09-07 12:03 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
> +		private const string _nLogSectionName = "NLog";
nameof(Nlog)

2023-09-07 12:05 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
>  			services.AddSingleton<IEmailRepository, EmailRepository>();
Вот это вот все в файл DependencyInjection в метод IServiceCollection AddCustomerAppsApi(this IServiceCollection services)

2023-09-07 12:06 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Infrastructure/Converters/NullableDecimalToStringConverter.cs
> +}
нет пустой строки в конце

2023-09-07 12:07 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/JournalViewModels/WaterJournalViewModel.cs
> +				userRepository, new StringHandler());
в приватное поле, без создания на месте

2023-09-07 12:07 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ViewModels/Suppliers/RequestToSupplierViewModel.cs
> +							counterpartySelectorFactory, nomenclatureRepository, userRepository, new StringHandler()));
тоже самое

2023-09-07 12:08 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Views/Goods/NomenclatureView.cs
>  				.AddBinding(ViewModel.Entity, e => e.BottleCapColor, w => w.Color, new ColorTextToGdkColorConverter())
в поле, без создания на месте

2023-09-07 12:09 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Views/Goods/NomenclatureView.cs
> +			alternativePricesView.Sensitive = ViewModel.CanCreateAndArcNomenclatures && ViewModel.CanEditAlternativeNomenclaturePrices &&
если переносить - то все, это плохо читается

2023-09-07 12:18 UTC, efimov90 requested changes
По уже отправленным комментариям

2023-09-07 12:22 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +					_logger.LogInformation("Превышен интервал обращений для источника {Source}", sourceName);
так и есть, только локальное. Не вижу смысла делать что-то другое

2023-09-07 12:25 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +				var passedTime = lastRequestTime == now ? 0d : (now - lastRequestTime).TotalMinutes;
какой нейминг, вроде все корректно. Не уверен, но на стыке дней спаны не подойдут

2023-09-11 08:57 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +		[Route("GetNomenclaturesPricesAndStocks")]
оставим

2023-09-11 08:59 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +				var passedTime = lastRequestTime == now ? 0d : (now - lastRequestTime).TotalMinutes;
поправил

2023-09-11 09:00 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/NomenclatureFactory.cs
> +			return parametersData.NomenclatureOnlineParametersNodes.Select(parametersNode => new NomenclaturePricesAndStockDto
может в будущем

2023-09-11 09:00 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/NomenclatureFactory.cs
> +			return new NomenclaturesPricesAndStockDto
не сейчас

2023-09-11 09:01 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/NomenclatureFactory.cs
> +		private IList<NomenclaturePricesDto> CreateNomenclaturePricesDto(
да

2023-09-11 09:01 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
>  			services.AddSingleton<IEmailRepository, EmailRepository>();
может позже

2023-09-11 09:02 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Middleware/ResponseLoggingMiddleware.cs
> +			_logger = loggerFactory.CreateLogger<ResponseLoggingMiddleware>();
позже проверю, сейчас не хочу тратить на это время

2023-09-11 09:11 UTC, efimov90 approved these changes

2023-09-13 06:10 UTC, merged