4509 - Удаление комментария предыдущей точки доставки
VodovozOrganization/Vodovoz pull request #2701
Opened 2023-09-19 08:04 UTC by efimov90

2023-09-19 08:05 UTC, N-Sem approved these changes

2023-09-19 08:08 UTC, Druchik requested changes

2023-09-19 08:08 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			}
А это здесь зачем? Оно не обязательно к заполнению

2023-09-19 08:10 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			}
Обязательно

2023-09-19 08:25 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			}
Исправлено

2023-09-19 08:26 UTC, Druchik approved these changes

2023-09-22 11:31 UTC, efimov90 commented
Было залито хотфиксом, не актуально

2023-09-22 11:31 UTC, closed without merging