4585 - Улучшить поиск дома в создании точки доставки
VodovozOrganization/Vodovoz pull request #2842
Opened 2023-11-07 11:52 UTC by efimov90

2023-11-08 07:28 UTC, Druchik requested changes

2023-11-08 07:28 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/SidePanel/InfoViews/DeliveryPointPanelView.cs
>  		}
если не ошибаюсь, то автоматически у вьюх Dispose не вызывается, надо все прописывать в Destroy, чтобы ручками не добавлять эти вызовы

2023-11-08 07:28 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/TempAdapters/DeliveryPointJournalFactory.cs
> +		private readonly ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
а это почему так? Все же повиснет в памяти

2023-11-08 07:28 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/TempAdapters/FixedPricesDialogOpener.cs
> +		private readonly ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
аналогично

2023-11-09 08:34 UTC, Druchik requested changes
Главное добавить пропущенные Dispose для scope, остальное по желанию

2023-11-09 08:34 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/CallTaskDlg.cs
> +		private ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
а где освобождение ресурсов? Или я проглядел?

2023-11-09 08:34 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/Client/ProxyDlg.cs
> +		private ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
аналогично

2023-11-09 08:34 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
> +                filter.RestrictHideService = true;
чего-то все уплыло

2023-11-09 08:34 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/TempAdapters/OrderSelectorFactory.cs
> +			var routeListItemRepository = _lifetimeScope.Resolve<IRouteListItemRepository>();
странное решение, вместо резолва вью моделей, ты резолвишь отдельно все зависимости

2023-11-09 08:34 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/toolbars/ToolbarActions.cs
> +		var reportViewDlg = new QSReport.ReportViewDlg(report);
а здесь освободить?

2023-11-09 09:19 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Client/ProxyDlg.cs
> +		private ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
добавил

2023-11-09 09:19 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
> +                filter.RestrictHideService = true;
поправил

2023-11-09 10:00 UTC, Druchik approved these changes

2023-11-14 10:16 UTC, merged