4609 - Расчет рентабельности при формировании мл
VodovozOrganization/Vodovoz pull request #2847
Opened 2023-11-10 07:15 UTC by efimov90

2023-11-14 07:58 UTC, Art8m approved these changes

2023-11-14 08:05 UTC, Druchik requested changes

2023-11-14 08:05 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
> +		}
ты же вроде нигде это не используешь или я проглядел?

2023-11-15 15:18 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
> +
убрал

2023-11-15 15:18 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
> +		}
убрал

2023-11-22 21:06 UTC, Art8m commented on Source/Applications/Desktop/Vodovoz/Logistic/RouteListAddressesTransferringView.cs
> +	public partial class RouteListAddressesTransferringView : TabViewBase<RouteListTransferringViewModel>
Все эти действия с ViewModel-ью в конструкторе View разве нельзя осуществлять в самой ViewModel-и?

2023-11-22 21:08 UTC, Art8m commented on Source/Applications/Desktop/Vodovoz/Logistic/RouteListAddressesTransferringView.cs
> +				// && routeListItemNode.IsFromFreeBalance
коммент

2023-11-22 21:35 UTC, Art8m approved these changes

2023-11-23 06:46 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Logistic/RouteListAddressesTransferringView.cs
> +	public partial class RouteListAddressesTransferringView : TabViewBase<RouteListTransferringViewModel>
К сожалению нет

2023-12-11 13:16 UTC, Druchik approved these changes

2023-12-11 13:17 UTC, merged