4485 интеграция номенклатур
VodovozOrganization/Vodovoz pull request #2934
Opened 2023-12-06 10:01 UTC by Druchik

2023-12-06 11:52 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/NomenclatureController.cs
> +					_configuration.GetSection("NomenclatureRequestsMinutesLimits")
не лучше через Options?

2023-12-06 11:54 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/CreateProjectParam.cs
> +				.RegisterWidgetForTabViewModel<NomenclatureOnlineGroupViewModel, NomenclatureOnlineGroupView>()
Не лучше уже перейти на авто-регистрацию? Там ПР лежит, должен работать, единственное что смущает - он регистрирует больше чем у нас сейчас

2023-12-06 11:56 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/NomenclatureOnlineCategoriesJournalRegistrar.cs
> +	public class NomenclatureOnlineCategoriesJournalRegistrar
internal sealed

2023-12-06 11:57 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/NomenclatureOnlineGroupsJournalRegistrar.cs
> +	public class NomenclatureOnlineGroupsJournalRegistrar
тоже самое

2023-12-06 12:04 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Goods/NomenclatureOnlineCatalogViewModel.cs
> +			INavigationManager navigationManager) : base(uowFactory, commonServices?.InteractiveService, navigationManager)
зачем null check? должно падать

2023-12-06 12:06 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/NomenclaturesDto.cs
> +		public string ErrorMessage { get; set; }
не особо понимаю почему тут это находится, по хорошему должны быть ProblemDetails

2023-12-06 12:07 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/OnlineNomenclatureDto.cs
> +		public static OnlineNomenclatureDto Create(OnlineNomenclatureNode node)
Если уж делать закрытие изменения  - то поля должны быть private set

2023-12-06 12:09 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Services/INomenclatureOnlineParametersProvider.cs
> +	public interface INomenclatureOnlineParametersProvider
Вроде бы уже все переносим на Settings, почему новый провайдер?

2023-12-06 12:10 UTC, efimov90 requested changes
internal sealed - точно нужно править

2023-12-07 08:52 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/CreateProjectParam.cs
> +				.RegisterWidgetForTabViewModel<NomenclatureOnlineGroupViewModel, NomenclatureOnlineGroupView>()
полетит фиксом, так что оставим так

2023-12-07 08:53 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/NomenclatureOnlineCategoriesJournalRegistrar.cs
> +	public class NomenclatureOnlineCategoriesJournalRegistrar
исправил

2023-12-07 08:54 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Goods/NomenclatureOnlineCatalogViewModel.cs
> +			INavigationManager navigationManager) : base(uowFactory, commonServices?.InteractiveService, navigationManager)
без нулл чека будет безымянная ошибка, а так пойдет null в интерэктив сервис и там отработает проверка

2023-12-07 08:54 UTC, Druchik commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/NomenclaturesDto.cs
> +		public string ErrorMessage { get; set; }
оставлю, т.к. разрабы уже все запилили, но в целом согласен

2023-12-07 08:54 UTC, Druchik commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/OnlineNomenclatureDto.cs
> +		public static OnlineNomenclatureDto Create(OnlineNomenclatureNode node)
оставлю

2023-12-07 08:55 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Services/INomenclatureOnlineParametersProvider.cs
> +	public interface INomenclatureOnlineParametersProvider
так он и использует SettingsController, а не ParametersProvider

2023-12-07 09:30 UTC, efimov90 approved these changes

2023-12-11 08:52 UTC, merged