4546 События нахождения водителя на складе
VodovozOrganization/Vodovoz pull request #2936
Opened 2023-12-06 14:42 UTC by Druchik

2023-12-07 11:05 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +				var qrPlacer = new EventsQrPlacer(
очень сомнительное решение, почему не через иньекцию?

2023-12-07 11:06 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
> +			_eventsQrPlacer = _lifetimeScope.Resolve<IEventsQrPlacer>();
а тут через нее

2023-12-07 11:08 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/MainWindow.cs
> -	private static Logger _logger = LogManager.GetCurrentClassLogger();
тпбы поехали

2023-12-07 11:12 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Logistic/CompletedDriverWarehouseEventViewModel.cs
> +		{
пустая, так и должно быть?

2023-12-07 11:16 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/CompletedDriverWarehouseEventRepository.cs
> +			return uow.Session.QueryOver<CompletedDriverWarehouseEvent>()
если нет потребности QueryOver лучше через IQueryable

2023-12-07 11:19 UTC, efimov90 commented on Source/Libraries/Core/Infrastructure/Vodovoz.RDL/GeneratedElements/List.cs
> +		//[XmlElement("ReportItems", typeof(ReportItems))]
комментарий

2023-12-07 11:21 UTC, efimov90 commented on Source/Libraries/Core/Infrastructure/VodovozInfrastructure/Services/ParsedCoordinatesResult.cs
> +	public struct ParsedCoordinatesResult
уже есть класс Result

2023-12-07 11:22 UTC, efimov90 requested changes
по комментариям

2023-12-08 13:35 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Logistic/CompletedDriverWarehouseEventViewModel.cs
> +		{
удалил

2023-12-08 13:35 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Views/Reports/DriversWarehousesEventsReportView.cs
> +        {
поправил

2023-12-08 13:35 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/MainWindow.cs
> -	private static Logger _logger = LogManager.GetCurrentClassLogger();
исправил

2023-12-08 13:35 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
> +			_eventsQrPlacer = _lifetimeScope.Resolve<IEventsQrPlacer>();
оставил

2023-12-08 13:36 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +				var qrPlacer = new EventsQrPlacer(
оставил

2023-12-08 13:36 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/CompletedDriverWarehouseEventRepository.cs
> +			return uow.Session.QueryOver<CompletedDriverWarehouseEvent>()
переписал

2023-12-08 13:36 UTC, Druchik commented on Source/Libraries/Core/Infrastructure/Vodovoz.RDL/GeneratedElements/List.cs
> +		//[XmlElement("ReportItems", typeof(ReportItems))]
удалил

2023-12-12 06:29 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz.Presentation.Reports/Factories/CustomReportFactory.cs
> +			string left, string top, string qrString, string height = "80pt", string width = "80pt")
повторяющаяся статика - в константы

2023-12-12 06:30 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz.Presentation.Reports/Factories/ICustomReportFactory.cs
> +			string left, string top, string qrString, string height = "80pt", string width = "80pt");
тоже самое

2023-12-12 06:32 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/EventsQrPlacer.cs
> +			var leftLeftQr = 0m;
тут точно корректный нейминг?

2023-12-12 06:36 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/MainWindow.cs
тут пробелы почему то появились лишние

2023-12-12 06:39 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Program.cs
> +						.AddScoped<IEventsQrPlacer, EventsQrPlacer>()
Если это в Presentation.Report - лучше через метод расширения (см. DependencyInjection.cs)

2023-12-12 06:44 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Logistics/DriversWarehousesEventsReportViewModel.cs
> +			ReportNodes.Clear();
Чревато проблемами с изменением значений в контролах

2023-12-12 06:47 UTC, efimov90 approved these changes
Мелочи и генерация отчета смущает, в остальном вроде порядок

2023-12-13 06:46 UTC, merged