Функция удаления списка работающих водителей
VodovozOrganization/Vodovoz pull request #294
Opened 2021-04-01 13:49 UTC by Mokrynskiy

2021-04-01 18:29 UTC, ShubArseniy requested changes

2021-04-01 18:29 UTC, ShubArseniy commented on Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
> +        }
SensItive. И вообще тут только одна кнопка, лучше переименовать поточней. И скобки добавить { }

2021-04-01 18:29 UTC, ShubArseniy commented on Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
> +            {
отчищен хотито

2021-04-01 18:29 UTC, ShubArseniy commented on Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
> +        }
Лучше не так: driversAtDay.Count < 1, а вот так: !driversAtDay.Any(). Читаемей

2021-04-01 18:29 UTC, ShubArseniy commented on Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
> +        }
ydateAtWorks.Date.Date - зачем 2 раза?

2021-04-01 18:29 UTC, ShubArseniy commented on Vodovoz/gtk-gui/gui.stetic
>                        </widget>
Изменения во всех виджетах, которые ты не менял, отменяй

2021-04-06 07:40 UTC, Enzogord approved these changes

2021-04-06 07:50 UTC, Enzogord approved these changes

2021-04-06 07:51 UTC, ShubArseniy approved these changes

2021-04-06 08:17 UTC, merged