Хотфикс двух отчетов по рознице (Контрагенты и Качественный)
VodovozOrganization/Vodovoz pull request #299
Opened 2021-04-04 17:14 UTC by Iamposox

2021-04-05 06:35 UTC, ShubArseniy commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
>  	AND (@sales_channel_id = 0 OR sales_channels.id = @sales_channel_id)
Разве RDL умеет работать с такими символами (>=)? Он их вроде как на &gt; и &lt; заменяет

2021-04-05 09:18 UTC, ShubArseniy approved these changes

2021-04-06 06:30 UTC, ShubArseniy commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
>  	date(orders.create_date) AS first_order,
GET_PERSON_NAME_WITH_INITIALS используй

2021-04-06 06:31 UTC, ShubArseniy commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
> +    </ReportParameter>
Почему string а не boolean?

2021-04-14 06:35 UTC, ShubArseniy requested changes

2021-04-14 06:35 UTC, ShubArseniy commented on Vodovoz/CreateProjectParam.cs
> +
Это тут зачем?

2021-04-14 06:35 UTC, ShubArseniy commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
> +    AND (@create_date = '' OR orders.create_date &gt;= @create_date)
Зачем = 1? Можно же просто is_for_retail

2021-04-14 06:35 UTC, ShubArseniy commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
> +GROUP BY delivery_points.compiled_address, counterparty.full_name
Тут 1 это True? Так почему тогда True не поставить?

2021-04-14 06:35 UTC, ShubArseniy commented on Vodovoz/Reports/Retail/QualityReport.rdl
>  	orders.is_for_retail = 1
Тут тоже

2021-04-14 07:19 UTC, Iamposox commented on Vodovoz/CreateProjectParam.cs
> +
Потому что кнопка редактирование не работала, исправлял

2021-04-14 07:26 UTC, Iamposox commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
> +    AND (@create_date = '' OR orders.create_date &gt;= @create_date)
Исправил

2021-04-14 07:26 UTC, Iamposox commented on Vodovoz/Reports/Retail/QualityReport.rdl
>  	orders.is_for_retail = 1
Исправил

2021-04-14 07:33 UTC, Iamposox commented on Vodovoz/Reports/Retail/CounterpartyReport.rdl
> +GROUP BY delivery_points.compiled_address, counterparty.full_name
Исправил

2021-04-14 11:18 UTC, ShubArseniy commented on Vodovoz/CreateProjectParam.cs
> +
Решили пока оставить так

2021-04-14 11:19 UTC, ShubArseniy approved these changes

2021-04-14 11:19 UTC, merged