4518 интеграция промонаборов
VodovozOrganization/Vodovoz pull request #3005
Opened 2023-12-22 10:11 UTC by Druchik

2023-12-26 06:08 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/OrdersController.cs
> +	[ApiController]
Можно вынести общую часть из контроллера, см. DriverApi

2023-12-26 06:10 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/OrdersController.cs
> +		public bool CanCounterpartyOrderPromoSetForNewClients([FromQuery] Source source, int erpCounterpartyId)
точно работает? не нужны теги для обоих аргументов? И точно ли нужны теги для них?

2023-12-26 06:11 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +		private static readonly ConcurrentDictionary<Source, DateTime> _requestTimes = new ConcurrentDictionary<Source, DateTime>();
это точно ен должно быть в контроллере

2023-12-26 06:12 UTC, efimov90 requested changes

2023-12-26 06:12 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +		private static readonly ConcurrentDictionary<Source, DateTime> _requestTimes = new ConcurrentDictionary<Source, DateTime>();
это точно ен должно быть в контроллере

2023-12-26 06:13 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +				.GetSection("RequestsMinutesLimits");
Вот это через биндинг или через Options<> не плохо было бы получать

2023-12-26 06:19 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +					&& passedTimeMinutes < _requestsLimitsSection.GetValue<int>("PromotionalSetsRequestFrequencyLimit"))
вероятно это не требуется, но можно запросить из контейнера снепшот настроек, прямо в этот метод, но нужно реализовывать Options

2023-12-26 06:20 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +				_requestTimes.TryUpdate(source, DateTime.Now, lastRequestTime);
Нет никаких проверок, TryUpdate возвращает true/false, вероятно приведет к ошибкам

2023-12-26 06:22 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Converters/SourceConverter.cs
>  				default:
если тут нет логгирования - то нет смысла в конвертере, используй метод расширения To*то во что*

2023-12-26 06:24 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/PromotionalSetFactory.cs
Тоже самое что выше - если нет логики в конвертации - ей место либо в методе расширения либо в фабричном методе в зависимости от ситуации

2023-12-26 06:25 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Models/NomenclatureModel.cs
Это сервис, а не модель

2023-12-26 06:30 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
> +			services.AddSingleton<IOrderRepository, OrderRepository>();
скорее всего тут не малая часть не принадлежит этому проекту, нужно вынести в файл библиотеки то, что принадлежит ей

2023-12-26 06:31 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
>  			services.AddSingleton<CounterpartyModelFactory>();
регистрация непосредственно типов должна быть сокращена по минимуму, извлечение интерфейса занимает не так много времени

2023-12-26 06:33 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			var otherFirstRealOrder = _orderRepository.HasCounterpartyOtherFirstRealOrder(UoW, Entity.Client, Entity.Id);
так это bool? или Order? поменять либо нейминг переменной либо метода

2023-12-26 06:39 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/NomenclaturePricesAndStockDto.cs
Нет докблоков в Dto

2023-12-26 06:43 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IPromotionalSetRepository.cs
> +		IList<PromotionalSetOnlineParametersNode> GetPromotionalSetsOnlineParametersForSend(
точно IList а не ICollection?

2023-12-26 06:44 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Permissions/Order.PromotionalSet.cs
> +			public static string CanChangeTypePromoSet => "can_change_the_type_of_promo_set";
Нед докблока с названием и описанием права

2023-12-26 06:46 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
> +			services.AddSingleton<IOrderRepository, OrderRepository>();
!! критично

2023-12-26 06:46 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			var otherFirstRealOrder = _orderRepository.HasCounterpartyOtherFirstRealOrder(UoW, Entity.Client, Entity.Id);
!! критично

2023-12-26 06:46 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/NomenclaturePricesAndStockDto.cs
!! критично

2023-12-26 06:46 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Permissions/Order.PromotionalSet.cs
> +			public static string CanChangeTypePromoSet => "can_change_the_type_of_promo_set";
!! критично

2023-12-27 06:37 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IPromotionalSetRepository.cs
> +		IList<PromotionalSetOnlineParametersNode> GetPromotionalSetsOnlineParametersForSend(
переделал

2023-12-27 06:38 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Permissions/Order.PromotionalSet.cs
> +			public static string CanChangeTypePromoSet => "can_change_the_type_of_promo_set";
добавил

2023-12-27 06:38 UTC, Druchik commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/NomenclaturePricesAndStockDto.cs
добавил

2023-12-27 06:38 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			var otherFirstRealOrder = _orderRepository.HasCounterpartyOtherFirstRealOrder(UoW, Entity.Client, Entity.Id);
поменял

2023-12-27 06:38 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
>  			services.AddSingleton<CounterpartyModelFactory>();
сделал

2023-12-27 06:38 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Startup.cs
> +			services.AddSingleton<IOrderRepository, OrderRepository>();
переместил

2023-12-27 06:39 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Models/NomenclatureModel.cs
оставил

2023-12-27 06:39 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Factories/PromotionalSetFactory.cs
оставил

2023-12-27 06:39 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Converters/SourceConverter.cs
>  				default:
оставил

2023-12-27 06:39 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +				_requestTimes.TryUpdate(source, DateTime.Now, lastRequestTime);
оставил

2023-12-27 06:39 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +					&& passedTimeMinutes < _requestsLimitsSection.GetValue<int>("PromotionalSetsRequestFrequencyLimit"))
оставил

2023-12-27 06:39 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +				.GetSection("RequestsMinutesLimits");
позже

2023-12-27 06:40 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/PromotionalSetController.cs
> +		private static readonly ConcurrentDictionary<Source, DateTime> _requestTimes = new ConcurrentDictionary<Source, DateTime>();
будет переделано в следующих задачах по интеграции

2023-12-27 06:40 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerAppsApi/Controllers/OrdersController.cs
> +	[ApiController]
не стал выносить, возможно в будущем

2023-12-27 07:20 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/DependencyInjection.cs
> +			services.AddSingleton<IRegisteredNaturalCounterpartyDtoFactory, RegisteredNaturalCounterpartyDtoFactory>();
лучше использовать цепной вызов

2023-12-27 07:21 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/OnlineNomenclatureDto.cs
>  		public int? LockerRefrigeratorVolume { get; set; }
Volume пропустил

2023-12-27 08:11 UTC, Druchik commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/OnlineNomenclatureDto.cs
>  		public int? LockerRefrigeratorVolume { get; set; }
добавил

2023-12-27 08:11 UTC, Druchik commented on Source/Libraries/Core/Backend/CustomerAppsApi.Library/DependencyInjection.cs
> +			services.AddSingleton<IRegisteredNaturalCounterpartyDtoFactory, RegisteredNaturalCounterpartyDtoFactory>();
сделал

2023-12-27 08:12 UTC, efimov90 approved these changes

2023-12-27 08:24 UTC, merged