Feature/3132 save delivery changes
VodovozOrganization/Vodovoz pull request #309
Opened 2021-04-06 08:38 UTC by Mokrynskiy

Выставление значения по умолчанию в поле статья дохода/расхода при добавлении приходного/расходного кассового ордера самовывоза

2021-04-06 15:34 UTC, Iamposox commented
Все фичи базируются от develop, хотфиксы в основном от мастера

2021-04-07 06:30 UTC, ShubArseniy requested changes

2021-04-07 06:30 UTC, ShubArseniy commented on Vodovoz/Dialogs/Cash/CashExpenseSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
Зачем так? У тебя же есть список когда ты заполняешь комбобокс, там из этого списка и бери первое попавшееся значение

2021-04-07 06:30 UTC, ShubArseniy commented on Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
Тут также

2021-04-07 07:04 UTC, Mokrynskiy commented on Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
ComboBox.ItemList от сюда (CategoryRepository.SelfDeliveryIncomeCategories(UoW)) и заполняется.
Если я буду данные брать из ComboBox.ItemList то получится жесткая привязка к элементу управления.

2021-04-07 07:08 UTC, ShubArseniy commented on Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
Так ты сохрани данные из CategoryRepository.SelfDeliveryIncomeCategories(UoW) в промежуточную коллекцию да и все

2021-04-07 07:14 UTC, Mokrynskiy commented on Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
Это же лишний код. Я вытяну данные из CategoryRepository.SelfDeliveryIncomeCategories(UoW) в какой нибудь ICollection, а потом из этой коллекции возьму первую запись и Entity.IncomCategory ее присвою. Зачем.

2021-04-07 07:23 UTC, ShubArseniy commented on Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
Затем что так будет на один запрос в базу меньше

2021-04-07 07:26 UTC, Mokrynskiy commented on Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
>  			if(Entity.Casher == null) {
Ок.

2021-04-07 08:47 UTC, efimov90 commented
Нужно поменять название ПР на человеко-понятное и изменить комментарий

2021-04-07 09:26 UTC, ShubArseniy commented on Vodovoz/Dialogs/Cash/CashExpenseSelfDeliveryDlg.cs
>  			new SelfDeliveryCashOrganisationDistributor(new SelfDeliveryCashDistributionDocumentRepository());
Приватные поля с маленькой буквы. Зачем тебе кстати отдельное поле нужно? Можно же локально коллекцию создать вида:
var collName = CategoryRepository.ExpenseSelfDeliveryCategories(UoW);
Entity.ExpenseCategory = collName.FirstOrDefault();
comboExpense.ItemsList = collName;

А проверка на то, что сущность новая делается проверкой Entity.Id == 0

Но это необязательно, если не хочешь исправь букву и смержи, аппрув кидаю

2021-04-07 09:27 UTC, ShubArseniy approved these changes
Кривовато конечно, но пойдёт

2021-04-07 10:03 UTC, merged