4843 Автоматизировать очистку истории проверок доставки за час
VodovozOrganization/Vodovoz pull request #3317
Opened 2024-04-03 12:23 UTC by N-Sem

Очистка истории проверок доступности доставки за час перенесена в воркер

2024-04-03 12:29 UTC, Art8m commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +		private const int _delayInMinutes = 120;
Вроде бы говорили раз в сутки

2024-04-03 12:35 UTC, Art8m approved these changes

2024-04-03 14:07 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +		private const int _delayInMinutes = 120;
Переместить в настройки

2024-04-03 14:08 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +				_logger.LogInformation("Воркер очистки истории проверок доставки за час запущен в: {time}", DateTimeOffset.Now);
Тег с большой буквы и осмысленное название

2024-04-03 14:09 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +					_logger.LogError(e, $"Ошибка при выполнении очистки истории проверок доставки за час {DateTime.Today:dd-MM-yyyy}");
в строку формата, без интерполяции

2024-04-03 14:09 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +				_logger.LogInformation($"Воркер очистки истории проверок доставки за час ожидает {_delayInMinutes}мин перед следующим запуском");
тоже самое

2024-04-03 14:09 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +				await Task.Delay(1000 * 60 * _delayInMinutes, stoppingToken);
для этого есть TimeSpan

2024-04-03 14:10 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/FastDeliveryAvailabilityHistoryModel.cs
> +							.SetTimeout(600)
так же в настройки, если есть перегрузка - то сразу передавать TimeSpan, если нет, брать от него нужное Total<нужное>

2024-04-03 14:11 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/FastDeliveryAvailabilityHistoryModel.cs
> +				@"DELETE
где-то был пример как названия таблиц в этом использовать

2024-04-03 14:15 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/MonitoringArchivingWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +		private const int _delayInMinutes = 120;
смотри SmsInformerOptions, там используется настройка через TimeSpan

2024-04-03 14:15 UTC, efimov90 requested changes
См. комментарии

2024-04-04 08:34 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/DatabaseServiceWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +				"Воркер ClearFastDeliveryAvailabilityHistoryWorker запущен в: {time}",
осмысленное название и с большой буквы

2024-04-04 08:34 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/DatabaseServiceWorker/ClearFastDeliveryAvailabilityHistoryWorker.cs
> +				"Воркер ClearFastDeliveryAvailabilityHistoryWorker завершил работу в: {time}",
тоже самое

2024-04-04 08:35 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/DatabaseServiceWorker/DependencyInjection.cs
> +			;
точку с запятой на предыдущую строку

2024-04-04 08:37 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Models/IFastDeliveryAvailabilityHistoryModel.cs
> +
лишняя строка

2024-04-04 08:37 UTC, efimov90 requested changes
по комментариям

2024-04-04 09:27 UTC, efimov90 approved these changes

2024-04-04 09:48 UTC, merged