4755 автоматизация создания заказов из ИПЗ
VodovozOrganization/Vodovoz pull request #3460
Opened 2024-05-30 14:15 UTC by Druchik

2024-06-07 09:26 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerOrdersApi/Controllers/OrdersController.cs
> +				return Problem();
Details не требуются?

2024-06-07 09:27 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerOrdersApi/Dockerfile
Зачем, если есть публикация SDK?

2024-06-07 09:29 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/CustomerOrdersApi/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:37230",
порт 5001

2024-06-07 09:30 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Consumers/OnlineOrderConsumer.cs
> +		protected readonly ILogger<OnlineOrderConsumer> Logger;
_logger

2024-06-07 09:36 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Dockerfile
тот же вопрос есть SDK публикация

2024-06-07 09:37 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Factories/OnlineOrderFactory.cs
> +				var onlineOrderItem = OnlineOrderItem.Create(
выглядит сомнительно, почему в заказе нет метода добавления строки?

2024-06-07 09:38 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Factories/OnlineOrderFactory.cs
> +				onlineOrder.OnlineRentPackages.Add(onlineRentPackage);
тот же вопрос

2024-06-07 09:39 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Program.cs
> +						//.AddStaticHistoryTracker()
точно не надо?

2024-06-07 09:40 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Properties/PublishProfiles/FolderProfile.pubxml
SDK

2024-06-07 09:41 UTC, efimov90 commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersStatusUpdateNotifier/Contracts/OnlineOrderStatusUpdatedDto.cs
> +	public class OnlineOrderStatusUpdatedDto
Докблока нет у самого класса

2024-06-07 09:48 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Orders/OnlineOrdersJournalFilterViewModel.cs
> +					/*PaymentsFromVisibility = _restrictPaymentType == PaymentType.PaidOnline;
комментарии

2024-06-07 09:49 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Orders/OnlineOrdersJournalFilterViewModel.cs
> +					var builder = new CommonEEVMBuilderFactory<OnlineOrdersJournalFilterViewModel>(
очень плохая идея 1 билдер на 2 разных сущности и почему Common? есть билдер, не подходит?

2024-06-07 10:04 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Orders/OnlineOrderViewModel.cs
> +			var builder = new CommonEEVMBuilderFactory<OnlineOrder>(this, Entity, UoW, NavigationManager, _lifetimeScope);
есть билдер

2024-06-07 10:08 UTC, efimov90 commented on Source/Libraries/Core/Backend/CustomerOrdersApi.Library/Dto/Orders/OnlineOrderInfoDto.cs
> +		public bool FaultedMessage { get; set; }
докблок

2024-06-07 10:18 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
чтобы не было конфликта - вырезать все Compile Include

2024-06-07 10:24 UTC, efimov90 commented on Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderService.cs
> +			//TODO проверка возможности добавления промонаборов
TODO

2024-06-07 10:32 UTC, efimov90 requested changes
По комментариям, особенно TODO

2024-06-07 14:34 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Tools/Orders/ComparerDeliveryPrice.cs
> +						//&& x.DiscountReason?.IsPresent != true
да

2024-06-07 14:35 UTC, Druchik commented on Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderService.cs
> +			//TODO проверка возможности добавления промонаборов
убрал

2024-06-07 14:35 UTC, Druchik commented on Source/Libraries/Core/Backend/CustomerOrdersApi.Library/Dto/Orders/OnlineOrderInfoDto.cs
> +		public bool FaultedMessage { get; set; }
сделал

2024-06-07 14:35 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Orders/OnlineOrdersJournalFilterViewModel.cs
> +					/*PaymentsFromVisibility = _restrictPaymentType == PaymentType.PaidOnline;
убрал

2024-06-07 14:35 UTC, Druchik commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersStatusUpdateNotifier/Contracts/ExternalOrderStatus.cs
> +		[Display(Name = "Заказ оформляется")]
добавил

2024-06-10 05:28 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerOrdersApi/Controllers/OrdersController.cs
> +				return Problem();
нет

2024-06-10 05:29 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerOrdersApi/Dockerfile
добавил другой профиль

2024-06-10 05:29 UTC, Druchik commented on Source/Applications/Backend/WebAPI/CustomerOrdersApi/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:37230",
сменил

2024-06-10 05:29 UTC, Druchik commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Dockerfile
обновил

2024-06-10 05:30 UTC, Druchik commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Program.cs
> +						//.AddStaticHistoryTracker()
восстановил, пускай пишет

2024-06-10 05:30 UTC, Druchik commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Properties/PublishProfiles/FolderProfile.pubxml
добавил

2024-06-10 05:32 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Orders/OnlineOrdersJournalFilterViewModel.cs
> +					var builder = new CommonEEVMBuilderFactory<OnlineOrdersJournalFilterViewModel>(
пробовал его, но там что-то не работало, сейчас не помню что. Не было времени копаться и решил использовать старый. Не вижу критичного для использования одной фабрики, по крайней мере в данном случае

2024-06-10 05:32 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/Orders/OnlineOrderViewModel.cs
> +			var builder = new CommonEEVMBuilderFactory<OnlineOrder>(this, Entity, UoW, NavigationManager, _lifetimeScope);
ответил выше по билдеру

2024-06-10 05:35 UTC, Druchik commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Consumers/OnlineOrderConsumer.cs
> +		protected readonly ILogger<OnlineOrderConsumer> Logger;
надо это обсудить. Префикс мы специально добавляли, чтобы различать приватные поля от обычных. Здесь же протектед

2024-06-10 06:10 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
убрал

2024-06-10 11:07 UTC, Druchik commented on Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Factories/OnlineOrderFactory.cs
> +				var onlineOrderItem = OnlineOrderItem.Create(
оставляю

2024-06-10 11:47 UTC, efimov90 approved these changes

2024-06-10 11:47 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
Будет конфликт

2024-06-10 11:52 UTC, merged