3325 - Добавлен журнал План продаж для КЦ для отчёта по мотивации КЦ
VodovozOrganization/Vodovoz pull request #358
Opened 2021-04-21 03:30 UTC by Art8m

2021-04-23 10:57 UTC, ShubArseniy requested changes

2021-04-23 10:57 UTC, ShubArseniy commented on Vodovoz/Filters/GtkViews/NomenclaturePlanFilterView.cs
> +            ychkOnlyPlanned.Binding.AddBinding(ViewModel, vm => vm.IsOnlyPlanned, w => w.Active).InitializeFromSource();
filterViewModel.NomenclatureFilterViewModel.RefreshFilter(); для чего?

2021-04-23 10:57 UTC, ShubArseniy commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +                        .SetDataProperty(node => node.Category.GetEnumTitle())
Почему не AddTextRenderer?

2021-04-23 10:57 UTC, ShubArseniy commented on Vodovoz/JournalViewModels/NomenclaturesPlanJournalViewModel.cs
> +
Зачем переопределять сам NodeActionsList? Хватает же CreateNodeActions

2021-04-23 10:57 UTC, ShubArseniy commented on VodovozViewModels/Journals/FilterViewModels/Goods/NomenclatureFilterViewModel.cs
> +    }
Для чего это?

2021-04-23 10:57 UTC, ShubArseniy commented on VodovozViewModels/Journals/FilterViewModels/Order/NomenclaturePlanFilterViewModel.cs
> +
NomenclatureFilterViewModel_OnFiltered для чего?

2021-04-23 10:57 UTC, ShubArseniy commented on Vodovoz/ViewModels/Orders/NomenclaturePlanViewModel.cs
> +    }
Зачем отдельная команда если нет логики? Вызывай тогда просто метод базового класса Save

2021-04-23 11:18 UTC, ShubArseniy commented on Vodovoz/ViewModels/Orders/NomenclaturePlanViewModel.cs
> +    }
Лучше даже SaveAndClose

2021-04-27 00:10 UTC, Art8m commented on Vodovoz/Filters/GtkViews/NomenclaturePlanFilterView.cs
> +            ychkOnlyPlanned.Binding.AddBinding(ViewModel, vm => vm.IsOnlyPlanned, w => w.Active).InitializeFromSource();
В фильтре номенклатур, в зависимости от выбранной категории, должны скрываться/отображаться чекбоксы. Здесь в фильтр плана вставлен целиком фильтр номенклатур плюс добавлен признак "Только с планом" и при открытии журнала будут не скрыты ненужные чекбоксы в фильтре номенклатур, пока не перевыбрать категорию. Поэтому один раз при загрузке, чтобы скрыть лишние чекбоксы для первоначальной категории, вызывается событие OnPropertyChanged для категории.

2021-04-27 00:11 UTC, Art8m commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +                        .SetDataProperty(node => node.Category.GetEnumTitle())
Поправил

2021-04-27 00:11 UTC, Art8m commented on Vodovoz/JournalNodes/NomenclatureJournalNode.cs
>  		public bool CalculateQtyOnStock { get; set; } = true;
Сделал

2021-04-27 00:11 UTC, Art8m commented on Vodovoz/JournalViewModels/NomenclaturesPlanJournalViewModel.cs
> +
Поправил

2021-04-27 00:14 UTC, Art8m commented on VodovozViewModels/Journals/FilterViewModels/Order/NomenclaturePlanFilterViewModel.cs
> +
При смене в  фильтре номенклатур фильтруются данные в журнале.

2021-04-27 00:14 UTC, Art8m commented on Vodovoz/ViewModels/Orders/NomenclaturePlanViewModel.cs
> +    }
Поправил на SaveAndClose

2021-04-29 06:23 UTC, ShubArseniy commented on VodovozBusiness/Domain/Orders/SelectedNomenclaturePlan.cs
> +    }
Почему BusinessObjectBase?

2021-04-29 06:23 UTC, ShubArseniy commented on Vodovoz/Vodovoz.csproj
> +    <Compile Include="JournalViewModels\NomenclaturesPlanJournalViewModel.cs" />
Почему всё в проекте водовоза?

2021-04-29 14:54 UTC, Art8m commented on VodovozViewModels/Journals/FilterViewModels/Goods/NomenclatureFilterViewModel.cs
> +    }
Убрал, копировал из фильтра номенклатур

2021-04-29 14:55 UTC, Art8m commented on VodovozBusiness/Domain/Orders/SelectedNomenclaturePlan.cs
> +    }
Исправил

2021-04-29 14:55 UTC, Art8m commented on Vodovoz/Vodovoz.csproj
> +    <Compile Include="JournalViewModels\NomenclaturesPlanJournalViewModel.cs" />
Перенёс в VodovozViewModels

2021-04-30 06:48 UTC, ShubArseniy commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                }
На кажду номенклатуру Commit вызывать медленно будет. Сначала удали все и и сохрани, потом коммит

2021-04-30 06:48 UTC, ShubArseniy commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                );
Ты тут вообще все номенклатуры грузишь? Это долго очень, надо грузить по 100 и подгружать ещё если пользователь проскроллил до самого конца. Так сделано в журналах у нас и в фильтре в отчёте по продажам

2021-04-30 06:48 UTC, ShubArseniy commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                );
Сотрудников тоже не всех грузить

2021-04-30 06:48 UTC, ShubArseniy commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                .Finish();
Тут стоит id ещё показывать я думаю

2021-04-30 06:48 UTC, ShubArseniy commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +        }
Перед загрузкой таким образом надо сделать Fetch всех групп товаров, иначе долго будет грузится по LazyLoading
Прим: UoW.Session.QueryOver<ProductGroup>().Fetch(SelectMode.Fetch, x => x.Childs).List();

2021-04-30 06:48 UTC, ShubArseniy commented on VodovozBusiness/Domain/Orders/SelectedNomenclaturePlan.cs
> +    }
Почему тут NomenclatureId а не сама номенклатура? Так удобно вообще?

2021-05-03 08:58 UTC, Art8m commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                }
Поправил

2021-05-03 08:59 UTC, Art8m commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                );
Переделал на динамическую загрузку

2021-05-03 08:59 UTC, Art8m commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                );
Переделал

2021-05-03 08:59 UTC, Art8m commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                .Finish();
Добавил

2021-05-03 08:59 UTC, Art8m commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +        }
Добавил

2021-05-03 09:00 UTC, Art8m commented on VodovozBusiness/Domain/Orders/SelectedNomenclaturePlan.cs
> +    }
Поправил

2021-05-04 06:38 UTC, ShubArseniy commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                { "nomenclatures", nomenclatureIds },
Если стереть конечную или начальную дату то тут ошибка будет?

2021-05-04 06:41 UTC, ShubArseniy commented
Номер задачи в название ветки добавь

2021-05-04 06:44 UTC, Enzogord commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                { "nomenclatures", nomenclatureIds },
будет

2021-05-04 07:39 UTC, Art8m commented on Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
> +                { "nomenclatures", nomenclatureIds },
проверил, вроде бы ошибки нет, просто передаётся дата 01.01.0001 (она выводится в заголовке отчёта)

2021-05-04 07:43 UTC, ShubArseniy submitted a review, later dismissed

2021-05-04 14:31 UTC, ShubArseniy approved these changes

2021-05-04 14:32 UTC, merged