4881 Обновление роута для регистрации заказа по QR из МП
VodovozOrganization/Vodovoz pull request #3649
Opened 2024-08-14 12:36 UTC by Druchik

2024-08-14 13:04 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
> +						fastPayments.First().Ticket);
nullref??

2024-08-14 13:06 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
> +					paidOrderInfoDto.Status);
nullref?

2024-08-14 13:07 UTC, efimov90 commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/FastPaymentsApiExtensions.cs
> +		public static IServiceCollection AddDependencyGroup(this IServiceCollection services)
FastPaymentsApiLibrary тогда уж

2024-08-14 13:08 UTC, efimov90 commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/FastPaymentsApiExtensions.cs
> +				.AddSingleton(_ => new FastPaymentFileCache("/tmp/VodovozFastPaymentServiceTemp.txt"))
а в конфиг не лучше вынести статичную строку?

2024-08-14 13:08 UTC, efimov90 commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ErrorHandler.cs
> +				bankResponseDetails.ResponseMessage);
nullref?

2024-08-14 13:08 UTC, efimov90 commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ErrorHandler.cs
> +				bankResponseDetails.ResponseMessage);
nullref?

2024-08-14 13:09 UTC, efimov90 commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/FastPaymentProcessingStatusChecker.cs
> +						orderInfoResponseDto.ResponseMessage);
nullref?

2024-08-14 13:11 UTC, efimov90 commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ResponseStatusProcessingFromOnlineChecker.cs
> +				_logger.LogInformation("Отменяем платеж с сессией {Ticket}", fastPayment.Ticket);
nullref?

2024-08-14 13:14 UTC, efimov90 requested changes
```
<PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
 ```
 Забыл один из тегов добавить, не вижу у FastPaymentsApi.Contracts

2024-08-15 06:17 UTC, Druchik commented on Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
> +					paidOrderInfoDto.Status);
не должно быть. Будет просто пустой объект на крайний случай

2024-08-15 06:20 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ErrorHandler.cs
> +				bankResponseDetails.ResponseMessage);
не случится. От банка будет како-то ответ. А если нет - поймается внешним try catch

2024-08-15 06:20 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ErrorHandler.cs
> +				bankResponseDetails.ResponseMessage);
тоже самое

2024-08-15 06:25 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/FastPaymentProcessingStatusChecker.cs
> +						orderInfoResponseDto.ResponseMessage);
тоже отловится внешним try catch

2024-08-15 06:31 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ResponseStatusProcessingFromDesktopChecker.cs
> +				_logger.LogInformation("Отменяем платеж с сессией {Ticket}", fastPayment.Ticket);
не может быть по логике, начальным условием Any() отсечется

2024-08-15 06:31 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Managers/ResponseStatusProcessingFromOnlineChecker.cs
> +				_logger.LogInformation("Отменяем платеж с сессией {Ticket}", fastPayment.Ticket);
также

2024-08-15 08:58 UTC, Druchik commented on Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
> +						fastPayments.First().Ticket);
поправил

2024-08-15 08:59 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/FastPaymentsApiExtensions.cs
> +		public static IServiceCollection AddDependencyGroup(this IServiceCollection services)
там не только зависимости с библиотеки, название и так говорящее

2024-08-15 09:10 UTC, Druchik commented on Source/Libraries/Core/Backend/FastPaymentsAPI.Library/FastPaymentsApiExtensions.cs
> +				.AddSingleton(_ => new FastPaymentFileCache("/tmp/VodovozFastPaymentServiceTemp.txt"))
оставлю как есть. Вообще нужно перерабатывать на rabbit такие вещи или делать кэш, вместо файла

2024-08-15 09:19 UTC, Druchik commented
не уверен, что это нужно,это я про тэг. Будет любое предупреждение считаться, как ошибка

2024-08-15 09:22 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
> +					paidOrderInfoDto.Status);
если paidOrderInfoDto будет null то упадет на логировании, на логировании падать не должно

2024-08-15 12:37 UTC, efimov90 approved these changes

2024-08-16 08:35 UTC, merged