4934 Маркировка. Мобильное приложение склада
VodovozOrganization/Vodovoz pull request #3681
Opened 2024-08-27 14:46 UTC by N-Sem

API для нового приложения склада

2024-10-09 12:15 UTC, Enzogord requested changes

2024-10-09 12:15 UTC, Enzogord commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Errors/CarLoadDocumentProcessingErrorsChecker.cs
> +				.Where(x => x.OrderId != null && x.Nomenclature.Category == Vodovoz.Domain.Goods.NomenclatureCategory.water)
Считаю что лучше проверять не по воде, а по установленному флагу учета в честном знаке в номенклатуре и по gtin

2024-10-10 14:28 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Startup.cs
> +			//app.ConfigureHealthCheckApplicationBuilder();
комментарий

2024-10-10 15:33 UTC, efimov90 commented on Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Store/CarLoadDocumentRepository.cs
> +								  where action.CarLoadDocumentId == documentId
тут что то с отступами

2024-10-10 15:34 UTC, efimov90 commented on Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Orders/OrderRepository.cs
> +				orderIds.Contains((int)carLoadDocumentItem.OrderId)
форматирование, это не читаемо

2024-10-10 15:37 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Errors/ResultT.cs
> +		public TValue FailureValue => IsFailure
У провального варианта не может быть значения

2024-10-10 15:38 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Errors/Result.cs
> +		public static Result<TValue> Failure<TValue>(TValue value, Error error) =>
Результат не может одновременно содержать и ошибку и значение

2024-10-10 15:39 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Store/ICarLoadDocumentRepository.cs
> +		IQueryable<CarLoadDocumentEntity> GetCarLoadDocumentsById(IUnitOfWork uow, int carLoadDocumentId);
Нельзя возвращать IQueryable из репозитория

2024-10-10 15:39 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/TrueMark/ITrueMarkRepository.cs
> +		IQueryable<TrueMarkWaterIdentificationCode> GetTrueMarkCodeDuplicates(IUnitOfWork uow, string gtin, string serialNumber, string checkCode);
тоже самое

2024-10-10 15:40 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteListItem.cs
> -		public virtual int Id { get; set; }
Точно?

2024-10-10 15:47 UTC, efimov90 commented on Source/Libraries/Core/Business/Vodovoz.Core.Data/Interfaces/Employees/IEmployeeWithLoginRepository.cs
> +		IQueryable<EmployeeWithLogin> GetEmployeeWithLoginById(IUnitOfWork uow, int id);
Репозиторий не должен возвращать IQueryable

2024-10-10 15:48 UTC, efimov90 requested changes
Репозитории не должны возвращать IQueryable
Результат не может одновременно иметь данные о результате исполнения и информацию об ошибке, только что-то одно.

2024-10-21 10:05 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Controllers/CarLoadController.cs
> +		[HttpPost("StartLoad")]
если есть время убери роуты, добавь после главного роута [action] он вроде понимает названия методов

2024-10-21 10:06 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Controllers/CarLoadController.cs
> +		[HttpPost("StartLoad")]
вроде в DriverApi я все переделал на это если нет то посмотри api где нет роутов

2024-10-21 10:07 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Controllers/CarLoadController.cs
> +		/// <param name="requestData"></param>
лучше к ним добавлять see теги с указанием типа

2024-10-21 10:10 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Controllers/PushNotificationsController.cs
> +		[HttpPost]
а вот тут как раз роутов нет (см предыдущий комментарий)

2024-10-21 10:11 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Controllers/PushNotificationsController.cs
> +			_securityOptions = securityOptions ?? throw new System.ArgumentNullException(nameof(securityOptions));
using System и рефакторингом убрать префикс System. для всего файла

2024-10-21 10:13 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Controllers/PushNotificationsController.cs
> +				return Problem("Пользователь {Username} не найден, невозможно подписаться на пуш сообщения", User.Identity?.Name);
не уверен может ли быть тут nullref, возможно есть смысл ?? "" добавить, лучше проверить вызовом который сюда провалится и убедиться, что не падает

2024-10-21 10:15 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Filters/WarehouseErrorHandlingFilterAttribute.cs
> +	public class WarehouseErrorHandlingFilterAttribute : ExceptionFilterAttribute
лучше вынести в общий Api проект, но это не критично, можешь на это забить, возможно целесообразнее не делать, при учете, что будем на версионные переходить

2024-10-21 10:17 UTC, efimov90 commented on Source/Applications/Backend/WebAPI/WarehouseApi/Filters/WarehouseErrorHandlingFilterAttribute.cs
> +				.GetService<ILogger<WarehouseErrorHandlingFilterAttribute>>();
проверь, вероятно тут должен быть GetRequiredService и весь блок в try catch обернуть с обработкой, в целом не критично, можно пропустить

2024-10-21 10:20 UTC, efimov90 commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Common/RequestProcessingResultT.cs
> +		{
вот тут возможна проблема, лучше проверять, что сюда приходит успешный результат, в случае если нет - падать с ошибкой, проверь насколько актуально для твоей логики работы с этим

и добавь докблоки для этого и безтипового, чтобы потом не искать как с этим работать

2024-10-21 10:21 UTC, efimov90 commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Common/RequestProcessingResultT.cs
С первого взгляда решение хорошее как раз для таких случаев

2024-10-21 10:23 UTC, efimov90 commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Errors/CarLoadDocumentProcessingErrorsChecker.cs
> +				_logger.LogError(error.Message, ex);
точно не наоборот сигнатура? ex, error.Message?

2024-10-21 10:25 UTC, efimov90 commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Services/CarLoadService.cs
> +				currentLoadOperationState.GetEnumTitle(),
точно тут нужен GetEnumTitle?

2024-10-21 10:25 UTC, efimov90 commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Services/CarLoadService.cs
> +				RawCode = trueMarkCode.SourceCode.Substring(0, Math.Min(255, trueMarkCode.SourceCode.Length)),
при SourceCode null nullref не будет?

2024-10-21 10:26 UTC, efimov90 commented on Source/Libraries/Core/Backend/WarehouseApi.Library/Services/ICarLoadService.cs
> +	public interface ICarLoadService
нет докблоков, не критично, но лучше добавить

2024-10-21 10:28 UTC, efimov90 commented on Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Orders/OrderRepository.cs
> +				orderIds.Contains((int)carLoadDocumentItem.OrderId)
уточняю - я про отступы у условий where

2024-10-21 10:28 UTC, efimov90 commented on Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Store/CarLoadDocumentRepository.cs
> +									.JoinAlias(c => c.Items, () => carLoadDocumentItemAlias)
много как то отступов

2024-10-21 10:33 UTC, efimov90 approved these changes
В целом хорошо, посмотри комментарии

2024-12-03 08:09 UTC, Enzogord approved these changes

2024-12-03 08:16 UTC, merged