Добавлен журнал складов
VodovozOrganization/Vodovoz pull request #369
Opened 2021-04-23 08:50 UTC by kozlov-d

+ Разделение warehousedlg на отдельные V & VM
+ В фильтрах для диалогов Готовые к погрузке\разгрузке добавлен entryVMe, показ которого зависит от кол-ва складов с разрешением на их просмотр
+ Журнал складов
+ Фабрика, возвращающая журнал для eVMe
PS если в журнале реализовать вывод складов в виде дерева с подразделениями, как в текущем warehousesView, то от последнего можно отказаться

2021-04-23 12:04 UTC, ShubArseniy requested changes

2021-04-23 12:37 UTC, kozlov-d commented on VodovozViewModels/Journals/JournalNodes/WarehouseJournalNode.cs
> +    }
Нужен для работы entityViewModelEntry

2021-04-26 13:08 UTC, ShubArseniy requested changes

2021-04-26 13:08 UTC, ShubArseniy commented on Vodovoz/Properties/AssemblyInfo.cs
Это в ПР не надо

2021-04-26 13:08 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Warehouses/WarehouseViewModel.cs
> +        }
SubdivisionRepository надо прокинуть

2021-04-26 15:05 UTC, ShubArseniy approved these changes

2021-04-26 15:05 UTC, merged