Чиста стетика и замена кнопок
VodovozOrganization/Vodovoz pull request #3692
Opened 2024-09-02 06:48 UTC by Enzogord

2024-09-02 06:51 UTC, efimov90 requested changes
Точно нет, у меня объемная задача, обновление в среду, я не готов решать конфликты

2024-09-02 06:54 UTC, Enzogord commented
> Точно нет, у меня объемная задача, обновление в среду, я не готов решать конфликты

Ок, ждем твою задачу

2024-09-09 06:16 UTC, efimov90 commented
Нужно поправить конфликты, но насколько понял это просто замена кнопок

2024-09-09 12:05 UTC, Enzogord commented
Изменения перенесены в ПР [3710](https://github.com/VodovozOrganization/Vodovoz/pull/3710)

2024-09-09 12:05 UTC, closed without merging