Переключение отчетов на slave бд
VodovozOrganization/Vodovoz pull request #3710
Opened 2024-09-09 06:13 UTC by Enzogord

2024-10-31 10:07 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz.Presentation.Reports/ValidatableUoWReportViewModelBase.cs
> +			UoW = (uowFactory ?? throw new ArgumentNullException(nameof(uowFactory))).CreateWithoutRoot();
лучше разбить на явную проверку и заполнение UoW после

2024-10-31 10:07 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz.Presentation.Reports/ValidatableUoWReportViewModelBase.cs
> +		public virtual IUnitOfWork UoW { get; set; }
тут точно нужен доступ на запись?

2024-10-31 10:10 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/EventsQrPlacer.cs
> +			var reportInfo = _reportInfoFactory.Create();
Нейминг будет путать, ощущение, будто создается фабрика, лучше явно CreateReportInfo или хотя бы CreateInfo

2024-10-31 10:10 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/EventsQrPlacer.cs
> +			reportInfo.Parameters = new Dictionary<string, object> { { "id", documentId } };
Не лучше создавать словарь в фабричном методе а тут просто заполнять?

2024-10-31 10:12 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
>  				var qrPlacer = new EventsQrPlacer(
не проще его сразу резолвить? я не вижу тут вещей которые нельзя пихать в контейнер

2024-10-31 10:13 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:13 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:13 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:14 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:14 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:14 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:14 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:16 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Counterparties/CallTaskView.cs
> +					dependencies => dependencies.RegisterInstance(ViewModel.Entity.CreateReportInfoByClient(ViewModel.ReportInfoFactory)));
Это старый отчет? Вроде было что-то про перевод на MVVM

2024-10-31 10:16 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/ShiftChangeWarehouseDocumentDlg.cs
> +			reportInfo.Title = String.Format("Акт передачи склада №{0} от {1:d}", Entity.Id, Entity.TimeStamp);
в интерполированную строку не предлагает перевести?

2024-10-31 10:17 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/ShiftChangeWarehouseDocumentDlg.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:18 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Employees/CarProxyDlg.cs
> +			evmeDriver.SetEntityAutocompleteSelectorFactory(employeeFactory.CreateWorkingDriverEmployeeAutocompleteSelectorFactory(true));
вообще там давно есть вариант поменять на новую Entry, но я так понимаю это время дополнительное

2024-10-31 10:19 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Employees/EmployeeWorkChartDlg.cs
> +			ConfigureDlg(employeeJournalFactory);
через поле не лучше?

2024-10-31 10:20 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Employees/EmployeeWorkChartDlg.cs
> +			evmeEmployee.SetEntityAutocompleteSelectorFactory(employeeJournalFactory.CreateWorkingEmployeeAutocompleteSelectorFactory());
Тоже самое про Entry, я так понимаю их слишком много, да и пихать это все в этот ПР наверное не актуальный вопрос, может есть смысл задачу создать, я отмечу везде где увижу

2024-10-31 10:21 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
> +			evmeDriver.SetEntityAutocompleteSelectorFactory(
старая энтри

2024-10-31 10:21 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
> +			evmeForwarder.SetEntityAutocompleteSelectorFactory(
старая энтри

2024-10-31 10:21 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
> +			evmeLogistician.SetEntityAutocompleteSelectorFactory(employeeJournalFactory.CreateWorkingEmployeeAutocompleteSelectorFactory());
старая энтри

2024-10-31 10:22 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrganizationDlg.cs
> +		private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
его можно получить через конструктор, если он тут нужен и Generic а не Nlog

2024-10-31 10:23 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrganizationDlg.cs
> +		private ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
Scope тоже можно получить через конструктор, если он нужен

2024-10-31 10:23 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrganizationDlg.cs
> +		private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
не актуально, вижу старые конструкторы, которые не дадут это сделать

2024-10-31 10:24 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrganizationDlg.cs
> +		private ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
Вижу старые конструкторы, которые это не дадут сделать, не актуально

2024-10-31 10:26 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Filters/GtkViews/EmployeeFilterView.cs
> +			ViewModel.UpdateRestrictions.Execute();
Нет проверки CanExecute. И тут не понятно это Radio? Тогда нужна проверка, что это нужная кнопка

2024-10-31 10:28 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/MainWindow.Navigation.Reports.cs
> +				builder.Register(c => new EmployeeFilterViewModel
Action<EmployeeFilterViewModel> если не путаю, то этот фильтр или журнал поддерживают это

2024-10-31 10:29 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/MainWindow.Navigation.Reports.cs
> +				builder.Register(c => new EmployeeFilterViewModel
тоже самое Action<Filter>

2024-10-31 10:31 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/MainWindow.Navigation.Reports.cs
> +		var interactiveService = _autofacScope.Resolve<IInteractiveService>();
а где создание скоупа? Где его Dispose?

2024-10-31 10:40 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/CashFlow.cs
> +			var parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:41 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/DriversWageBalanceReport.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:41 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/Employees/EmployeesReport.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:43 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/Logistic/AddressesOverpaymentsReport.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:43 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/Logistic/GeneralSalaryInfoReport.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:45 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/Logistic/ShipmentReport.cs
> +			//Необходимо Заменить на новый entry
нужна задача

2024-10-31 10:46 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/OrderStatisticByWeekReport.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:46 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/Orders/OrderChangesReport.cs
> +			};
тут что-то поехало и тот же вопрос про инициализацию и заполнение

2024-10-31 10:47 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/ReportForBigClient.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:50 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/Retail/QualityReport.cs
>              IUnitOfWorkFactory unitOfWorkFactory,
тут точно что-то поехало

2024-10-31 10:50 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/ReportsParameters/RevisionBottlesAndDeposits.cs
> +			var parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:55 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Representations/DebtorsJournalViewModel.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию и заполнение

2024-10-31 10:58 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Views/Logistic/DeliveryPointResponsiblePersonsView.cs
> +	        _employeeJournalFactory = new EmployeeJournalFactory(_scope);
через конструктор не выйдет?

2024-10-31 11:26 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Reports.EmployeesFines.cs
> -			this.radioCatOffice.Toggled += new global::System.EventHandler(this.OnRadioCatAllToggled);
4 подписки удалены

2024-10-31 11:27 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Reports.Logistic.RoutesListRegisterReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:28 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Reports.WagesOperationsReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:28 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bookkeeping.CounterpartyCloseDeliveryReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
Удалена подписка

2024-10-31 11:29 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bottles.BottlesMovementReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:30 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bottles.ExtraBottleReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:30 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bottles.OrdersByCreationDateReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:31 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bottles.ProfitabilityBottlesByStockReport.cs
> -			this.buttonRun.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:32 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.CardPaymentsOrdersReport.cs
> -			this.buttonCreateRepot.Clicked += new global::System.EventHandler(this.OnButtonCreateRepotClicked);
удалена подписка

2024-10-31 11:32 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.CompanyTrucksReport.cs
> -			this.dateperiodpicker.PeriodChanged += new global::System.EventHandler(this.OnDateperiodpickerPeriodChanged);
удалены 2 подписки

2024-10-31 11:33 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.DriversToDistrictsAssignmentReport.cs
> -			this.dateperiodpicker.PeriodChanged += new global::System.EventHandler(this.OnDateperiodpickerPeriodChanged);
удалены 2 подписки

2024-10-31 11:33 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.EmployeesPremiums.cs
> -			this.dateperiodpicker1.PeriodChanged += new global::System.EventHandler(this.OnDateperiodpicker1PeriodChanged);
удалены 2 подписки

2024-10-31 11:33 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.IncomeBalanceReport.cs
> -			this.buttonCreateRepot.Clicked += new global::System.EventHandler(this.OnButtonCreateRepotClicked);
удалена подписка

2024-10-31 11:34 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.LastOrderByDeliveryPointReport.cs
> -			this.buttonCreateRepot.Clicked += new global::System.EventHandler(this.OnButtonCreateRepotClicked);
удалена подписка

2024-10-31 11:34 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.AnalyticsForUndeliveryReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:35 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.DrivingCallReport.cs
> -			this.dateperiodpicker.PeriodChanged += new global::System.EventHandler(this.OnDateperiodpickerPeriodChanged);
удалены подписки

2024-10-31 11:35 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.FuelConsumptionReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:36 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.OrdersByDistrictsAndDeliverySchedulesReport.cs
> -			this.buttonRun.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:37 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.RouteListsOnClosingReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:38 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.ShipmentReport.cs
> -			this.radioAll.Toggled += new global::System.EventHandler(this.OnRadioAllToggled);
удалено 5 подписок

2024-10-31 11:39 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.MastersVisitReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:39 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.NotDeliveredOrdersReport.cs
> -			this.buttonRun.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:40 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.OrderIncorrectPrices.cs
> -			this.checkbutton1.Toggled += new global::System.EventHandler(this.OnCheckbutton1Toggled);
удалено 2 подписки

2024-10-31 11:41 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.OrderRegistryReport.cs
> -			this.buttonCreateRepot.Clicked += new global::System.EventHandler(this.OnButtonCreateRepotClicked);
удалена подписка

2024-10-31 11:41 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Orders.FirstClientsReport.cs
> -			this.datePeriodPicker.PeriodChanged += new global::System.EventHandler(this.OnDatePeriodPickerPeriodChanged);
удалено 2 подписки

2024-10-31 11:43 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.OrdersByDistrictReport.cs
> -			this.buttonCreateReport.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 11:48 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.OrdersWithMinPriceLessThan.cs
> -			this.buttonCreateRepot.Clicked += new global::System.EventHandler(this.OnButtonCreateRepotClicked);
удалена подписка

2024-10-31 11:49 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.ReportDebtorsBottles.cs
> -			this.buttonRun.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:51 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.SelfDeliveryReport.cs
> -			this.buttonCreateRepot.Clicked += new global::System.EventHandler(this.OnButtonCreateRepotClicked);
удалена подписка

2024-10-31 11:52 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.TariffZoneDebts.cs
> -			this.buttonRun.Clicked += new global::System.EventHandler(this.OnButtonRunClicked);
удалена подписка

2024-10-31 11:52 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.ZeroDebtClientReport.cs
> -			this.button1.Clicked += new global::System.EventHandler(this.OnButtonCreateReportClicked);
удалена подписка

2024-10-31 12:14 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Cash/ExpenseSelfDeliveryViewModel.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию

2024-10-31 12:15 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Cash/ExpenseViewModel.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию

2024-10-31 12:15 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Cash/IncomeSelfDeliveryViewModel.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию

2024-10-31 12:16 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Cash/IncomeViewModel.cs
> +			reportInfo.Parameters = new Dictionary<string, object>
Тот же вопрос про инициализацию

2024-10-31 12:17 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Cash/Transfer/IncomeCashTransferDocumentViewModel.cs
> +				reportInfo.Parameters = new Dictionary<string, object> { { "transfer_document_id", Entity.Id } };
Тот же вопрос про инициализацию

2024-10-31 12:17 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Counterparties/CallTaskViewModel.cs
> +			ReportInfoFactory = lifetimeScope.Resolve<IReportInfoFactory>();
почему не через конструктор?

2024-10-31 12:19 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Dialogs/Fuel/FuelTransferDocumentViewModel.cs
> +					reportInfo.Parameters = new Dictionary<string, object> { { "transfer_document_id", Entity.Id } };
Тот же вопрос про инициализацию

2024-10-31 12:20 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Dialogs/Fuel/FuelWriteoffDocumentViewModel.cs
> +					reportInfo.Title = String.Format($"Акт выдачи топлива №{Entity.Id} от {Entity.Date:d}");
интерполяция

2024-10-31 12:20 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Dialogs/Fuel/FuelWriteoffDocumentViewModel.cs
> +					reportInfo.Parameters = new Dictionary<string, object> { { "document_id", Entity.Id } };
Тот же вопрос про инициализацию

2024-10-31 12:21 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Print/Store/ContorlCarLoadDocumentRdl.cs
> +			reportInfo.Parameters = new Dictionary<string, object> { { "id", _carLoadDocument.Id } };
Тот же вопрос про инициализацию

2024-10-31 12:21 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Print/Store/EquipmentCarLoadDocumentRdl.cs
> +			reportInfo.Parameters = new Dictionary<string, object> { { "id", _carLoadDocument.Id } };
Тот же вопрос про инициализацию

2024-10-31 12:22 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Print/Store/WaterCarLoadDocumentRdl.cs
> +			reportInfo.Parameters = new Dictionary<string, object> { { "id", _carLoadDocument.Id } };
Тот же вопрос про инициализацию

2024-10-31 12:23 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Bottles/BottlesMovementReportViewModel.cs
> +						{ "start_date", StartDate },
поехала разметка

2024-10-31 12:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Bottles/ExtraBottleReportViewModel.cs
> +					{
отступы

2024-10-31 12:24 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Bottles/ProfitabilityBottlesByStockReportViewModel.cs
> +					{
отступы

2024-10-31 12:25 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Bottles/ProfitabilityBottlesByStockReportViewModel.cs
> +			public string Name => string.Format("{0}%", Pct);
интерполяция

2024-10-31 12:26 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Bottles/ShortfallBattlesReportViewModel.cs
> +		public enum Drivers
1 файл 1 тип

2024-10-31 12:29 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Client/ZeroDebtClientReportViewModel.cs
> +					{
отступы

2024-10-31 12:30 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/AnalyticsForUndeliveryReportViewModel.cs
> +					{
отступы

2024-10-31 12:30 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/CashierCommentsReportViewModel.cs
> +					{
отступы

2024-10-31 12:31 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/CompanyTrucksReportViewModel.cs
> +					{
отступы

2024-10-31 12:31 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/DriverRoutesListRegisterReportViewModel.cs
> +					{
отступы

2024-10-31 12:32 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/DriversToDistrictsAssignmentReportViewModel.cs
> +					{
отступы

2024-10-31 12:32 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/DrivingCallReportViewModel.cs
> +					{
отступы

2024-10-31 12:33 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/FuelConsumptionReportViewModel.cs
> +					{
отступы

2024-10-31 12:33 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/NonClosedRLByPeriodReportViewModel.cs
> +					{
отступы

2024-10-31 12:33 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/NonClosedRLByPeriodReportViewModel.cs
> +						{ "end_date", EndDate?.Date.AddHours(23).AddMinutes(59).AddSeconds(59) },
LatestDateTime()

2024-10-31 12:34 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/OnLoadTimeAtDayReportViewModel.cs
> +					{
отступы

2024-10-31 12:36 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Logistics/ShipmentReportViewModel.cs
> +					{
отступы

2024-10-31 12:36 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/CardPaymentsOrdersReportViewModel.cs
> +					{
отступы

2024-10-31 12:37 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/EShopSalesReportViewModel.cs
> +					{
отступы

2024-10-31 12:38 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/FirstSecondClientReportViewModel.cs
> +					{
отступы

2024-10-31 12:38 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/LastOrderByDeliveryPointReportViewModel.cs
> +					{
отступы

2024-10-31 12:38 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/NotDeliveredOrdersReportViewModel.cs
> +					{
отступы

2024-10-31 12:39 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/OrderIncorrectPricesViewModel.cs
> +					{
отступы

2024-10-31 12:39 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/OrderRegistryReportViewModel.cs
> +					{
отступы

2024-10-31 12:40 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/OrdersByCreationDateReportViewModel.cs
> +					{
отступы

2024-10-31 12:40 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Orders/OrdersByCreationDateReportViewModel.cs
> +			if(StartDate == null )
лишний пробел

2024-10-31 12:41 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Payments/ChainStoreDelayReportViewModel.cs
> +					{
отступы

2024-10-31 12:44 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Payments/PaymentsFromAvangardReportViewModel.cs
> +					{
отступы

2024-10-31 12:44 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Payments/PaymentsFromBankClientFinDepartmentReportViewModel.cs
> +					{
отступы

2024-10-31 13:03 UTC, efimov90 requested changes
Форматирование, интерполяция, 1 файл 1 тип и остальное по комментариям

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/Torg2Document.cs
> +			reportInfo.Title = String.Format($"Торг-2 от {Order.DeliveryDate:d}");
интерполяция

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/Torg2Document.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/TransportInvoiceDocument.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/TransportInvoiceDocument.cs
> +			reportInfo.Title = String.Format($"Товарно-транспортная накладная от {Order.DeliveryDate:d}");
интерполяция

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/UPDDocument.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePayment.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForDebt.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForPayment.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/PrintableDocuments/IncomingInvoiceDocumentRDL.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-10-31 13:03 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/PrintableDocuments/MovementDocumentRDL.cs
> +			reportInfo.Parameters = new Dictionary<string, object> {
Тот же вопрос про инициализацию, скобка

2024-11-01 14:11 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Additions/EventsQrPlacer.cs
> +			var reportInfo = _reportInfoFactory.Create();
Нет, наоборот, повторять лишний раз не стоит имена из названия класса.

2024-11-01 14:13 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Additions/EventsQrPlacer.cs
> +			reportInfo.Parameters = new Dictionary<string, object> { { "id", documentId } };
В целом согласен, но такой стиль применен во всех отчетах, и менять его сейчас нет времени, а на функционал не влияет

2024-11-01 14:17 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
>  				var qrPlacer = new EventsQrPlacer(
Это статика, текущее решение оптимальное на данном этапе, и нужно менять саму статику будет

2024-11-01 14:19 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Counterparties/CallTaskView.cs
> +					dependencies => dependencies.RegisterInstance(ViewModel.Entity.CreateReportInfoByClient(ViewModel.ReportInfoFactory)));
Это не отчет, а печатная форма задачи на обзвон

2024-11-01 14:21 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Dialogs/Employees/EmployeeWorkChartDlg.cs
> +			ConfigureDlg(employeeJournalFactory);
Оно не сохраняется и нужно только в конструкторе

2024-11-01 14:26 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrganizationDlg.cs
> +		private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
Это старый диалог, вообще не важно, в VM уже нормально нужно будет получить при модернизации на MVVM

2024-11-01 14:28 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Dialogs/OrganizationDlg.cs
> +		private ILifetimeScope _lifetimeScope = Startup.AppDIContainer.BeginLifetimeScope();
Там старый конструктор с перегрузками, он не адаптирован к DI

2024-11-01 14:35 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/Filters/GtkViews/EmployeeFilterView.cs
> +			ViewModel.UpdateRestrictions.Execute();
Это checkbutton, у него нет биндинга на команду, и внутри команды есть проверка canExecute

2024-11-01 14:39 UTC, Enzogord commented on Source/Applications/Desktop/Vodovoz/MainWindow.Navigation.Reports.cs
> +		var interactiveService = _autofacScope.Resolve<IInteractiveService>();
Это mainwindow

2024-11-01 15:03 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Sales/IncomeBalanceReportViewModel.cs
> +		public DelegateCommand GenerateReportCommand;
{ get: }

2024-11-01 15:05 UTC, efimov90 approved these changes
последний комментарий посмотри только

2024-11-02 06:33 UTC, merged