Запрос на смену пароля при сбросе через журнал сотрудников
VodovozOrganization/Vodovoz pull request #389
Opened 2021-04-28 12:30 UTC by kozlov-d

Как мне кажется, логичнее менять пароль в БД в методе ResetPassword только после того, как успешно отослан пароль на почту (метод SendCredentialsToEmail юзает emailService).

2021-04-28 12:40 UTC, kozlov-d commented on Vodovoz/Additions/AuthorizationService.cs
> +                };
var user = new User { Id = employee.User.Id,  NeedPasswordChange = true };
Тут скорее должно быть что то такое

2021-04-28 12:44 UTC, efimov90 commented on Vodovoz/Additions/AuthorizationService.cs
> +                var user = new User
не понятно зачем создается новый пользователь

2021-04-28 12:44 UTC, efimov90 commented on Vodovoz/Additions/AuthorizationService.cs
> +            if (result)
что-то я сомневаюсь, что это правильная логика

2021-04-28 12:45 UTC, efimov90 commented
Либо надо перерабатывать все это полностью, либо ничего не трогать, в таком виде оно не применимо

2021-04-28 13:09 UTC, ShubArseniy commented on Vodovoz/Additions/AuthorizationService.cs
А коммит где? Или ниже где-то?

2021-04-28 13:11 UTC, kozlov-d commented on Vodovoz/Additions/AuthorizationService.cs
А разве нужен? В соседнем методе, который сохраняет таким же образом новосозданного юзера, нет ничего кроме uow.Save

2021-04-28 13:16 UTC, ShubArseniy commented on Vodovoz/Additions/AuthorizationService.cs
Ты про TryToSaveUser()? Он вызывается из Save() в EmployeeDlg, т.е там точно позже вызывается коммит

2021-04-28 13:20 UTC, ShubArseniy commented on Vodovoz/Additions/AuthorizationService.cs
Мне кажется надо создавать uow прямо на месте, @Enzogord что думаешь?

2021-04-28 14:00 UTC, Enzogord requested changes

2021-04-28 14:00 UTC, Enzogord commented on Vodovoz/Additions/AuthorizationService.cs
Я бы предложил не передавать туда Employee, передавать только логин. Информация о Employee не нужна там как я вижу.
По логину сбросить пароль, потом, в новом uow, по логину найти пользователя, если он найдется, то поставить ему принудительную смену пароля.

2021-04-29 13:28 UTC, ShubArseniy commented on Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
>  			{
User может быть нуловым? Есть где-то проверка?

2021-04-29 13:47 UTC, kozlov-d commented on Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
>  			{
Не может быть. Есть проверка и на не привязанного user, и на отсутствие логина

2021-04-29 14:16 UTC, ShubArseniy approved these changes

2021-04-29 14:55 UTC, Enzogord approved these changes

2021-04-29 14:55 UTC, merged