4728 - Пересортица MVVM
VodovozOrganization/Vodovoz pull request #3958
Opened 2024-12-17 06:06 UTC by efimov90

2024-12-17 07:34 UTC, Druchik requested changes

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +								nextViewModel.OnSelectResult += SelectNewNomenclature_ObjectSelected;
паскаль кейс SelectNewNomenclature_ObjectSelected

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +					viewModel.OnSelectResult += ChangeNewNomenclature_OnEntitySelectedResult;
паскаль кейс

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +						};
лучше тоже вынести во вьюмодель, чтобы там отписываться

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +			}
тут точно не ошибка? Может != 0, т.к. если id = 0, то ее и в базе нет еще и удалять нечего

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsTemplateJournalNode.cs
> +	}
док блоки

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsTemplateItemsViewModel.cs
> +		public RegradingOfGoodsTemplateViewModel ParentViewModel { get; set; }
надо разбить связь ParentViewModel и этой вью модели при Dispose

2024-12-17 07:34 UTC, Druchik commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +		}
также надо обнулить ссылку при Dispose. И занулять приватное поле, чтобы не было падений

2024-12-17 07:34 UTC, Druchik commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Documents/RegradingOfGoodsDocument.cs
>  		private GenericObservableList<RegradingOfGoodsDocumentItem> _observableItems;
забыл приватное поле удалить

2024-12-17 08:51 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Documents/RegradingOfGoodsDocument.cs
>  		private GenericObservableList<RegradingOfGoodsDocumentItem> _observableItems;
убрал

2024-12-17 08:51 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +		}
поправил

2024-12-17 08:51 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsTemplateJournalNode.cs
> +	}
поправил

2024-12-17 08:51 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +			}
как было в оригинале, не менял

2024-12-17 08:52 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsTemplateItemsView.cs
> +		}
убрал лишнее

2024-12-17 08:52 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsDocumentItemsView.cs
> +		}
убрал подписки на кнопки

2024-12-17 08:54 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsDocumentItemsView.cs
> +		}
убрал, забыл, видимо там что-то было

2024-12-17 09:08 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +						};
поправил все такие случаи

2024-12-17 09:09 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +					viewModel.OnSelectResult += ChangeNewNomenclature_OnEntitySelectedResult;
поправил

2024-12-17 09:09 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Store/RegradingOfGoodsDocumentItemsViewModel.cs
> +								nextViewModel.OnSelectResult += SelectNewNomenclature_ObjectSelected;
поправил

2024-12-19 06:47 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsTemplateItemsView.cs
> +		}
поправил

2024-12-19 06:47 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsDocumentItemsView.cs
> +		}
поправил

2024-12-20 07:03 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsDocumentItemsView.cs
> +			buttonDeleteFine.Binding.CleanSources();
это можно не вызывать. Я прописал это в кнопке

2024-12-20 07:04 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsTemplateItemsView.cs
> +			buttonDelete.Binding.CleanSources();
аналогично

2024-12-20 09:12 UTC, merged