2851 - Добавление матрицы прав на склады в подразделения
VodovozOrganization/Vodovoz pull request #418
Opened 2021-05-07 08:38 UTC by Iamposox

Добавление матриц прав на склады в подразделения

2021-09-01 11:01 UTC, Iamposox commented on Vodovoz/Vodovoz.csproj
>        <Name>RdlEngine</Name>
Не знаю :/

2021-09-01 11:24 UTC, Iamposox commented on Vodovoz/Core/CurrentPermissions.cs
> +		}
Не я называл так. Конструктор убрал

2021-09-10 09:22 UTC, ShubArseniy requested changes

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Organizations/SubdivisionViewModel.cs
> +
Это почему?

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Users/UsersJournalViewModel.cs
> +				.OrderByAlias(() => userAlias.Name).Asc
Тут вроде как селекты должны автоформатированием вправо двигаться

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozViewModels/Infrastructure/Services/WarehousePermissionValidatorFactory.cs
> +				subdivision = subdivision.ParentSubdivision;
Неужели их никак нельзя рекурсивно загрузить одним запросом? Где-то был такой код

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozViewModels/Dialogs/Users/UserViewModel.cs
> +						}
Как это работает с методом Save в базовом классе? Просто параллельно идёт? Сомневаюсь что это правильно

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozViewModels/Dialogs/Users/UserViewModel.cs
> +				}
Да и нафиг такие команды, ничего полезного, зато куча кода

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozBusiness/Domain/Permissions/Warehouses/WarehousePermissionBase.cs
> +
А для чего нужен вообще этот атрибут? Он и раньше был?

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozBusiness/Domain/Permissions/Warehouses/WarehousePermissionBase.cs
> +			get => _warehousePermissionTypeType;
TypeType

2021-09-10 09:22 UTC, ShubArseniy commented on VodovozBusiness/Domain/Permissions/Warehouses/UserWarehousePermissionModel.cs
> +			.List();
Вот зачем эти энумераторы? Опять же можно сохранять а не грузить каждый раз

2021-09-10 09:22 UTC, ShubArseniy commented on Vodovoz/Vodovoz.csproj
>        <Name>RdlEngine</Name>
Не знаешь - исправляй

2021-09-10 09:22 UTC, ShubArseniy commented on Vodovoz/Views/Users/UserView.cs
> +
Очень много пустого

2021-09-10 09:22 UTC, ShubArseniy commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +			TreeViewColumnsConfigFactory.Register<UsersJournalViewModel>(
Почему тут 2 одинаковых журнала?

2021-09-10 09:22 UTC, ShubArseniy commented on Vodovoz/Core/CurrentWarehousePermissions.cs
> +				{
А почему загрузка только true прав? А если у юзера явно стоит false? 
Также почему есть вот это условие || !permissions.Any()? Если у юзера есть только одно какое-то право, то права его подразделения не будут вообще проверяться?

2021-09-14 02:23 UTC, Iamposox commented on VodovozBusiness/Domain/Permissions/Warehouses/WarehousePermissionBase.cs
> +
И раньше был

2022-11-28 13:17 UTC, efimov90 requested changes

2022-11-28 13:17 UTC, efimov90 commented on Source/Applications/Desktop/Vodovoz/Views/Permissions/WarehousePermissionView.cs
> +		private IList<yLabel> _labels = new List<yLabel>();
документ к табам

2022-11-28 13:17 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Dialogs/Users/UserViewModel.cs
> +    {
документ к табам

2022-11-28 13:17 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Employees/SelectUserJournalViewModel.cs
> +            : base(filterViewModel, unitOfWorkFactory, commonServices)
документ к табам

2022-11-28 13:17 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseJournalViewModel.cs
> +            Warehouse warehouseAlias = null;
к табам

2022-11-28 13:17 UTC, efimov90 commented on Source/Applications/Desktop/VodovozViewModels/ViewModels/PermissionNode/PermissionTypeAllNodeViewModel.cs
> +using System;
документ к табам

2022-11-28 13:17 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Permissions/Warehouses/UserWarehousePermission.cs
> +using System.ComponentModel.DataAnnotations;
табы

2022-11-28 13:17 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/Domain/Permissions/Warehouses/WarehousePermissionModelBase.cs
> +
табы

2022-11-28 13:17 UTC, efimov90 commented on Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Permissions/WarehousePermissionMap.cs
> +            References(x => x.Warehouse).Column("warehouse_id");
табы

2022-11-29 06:09 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Core/Permissions/SubdivisionEntityPermissionWidget.cs
> +		public EntitySubdivisionPermissionViewModel ViewModel { get; set; }
нет, оно устанавливается не в конструкторе

2022-11-29 06:24 UTC, Druchik commented on Source/Applications/Desktop/Vodovoz/Additions/Store/StoreDocumentHelper.cs
> +		private CurrentWarehousePermissions WarehousePermissions { get; }
А зачем? Это и так свойство только на чтение

2022-11-29 06:35 UTC, efimov90 approved these changes

2022-11-30 06:42 UTC, merged