Feature/feature 2934
VodovozOrganization/Vodovoz pull request #58
Opened 2021-01-27 14:00 UTC by efimov90

Завершение задачи по генерации путевых листов

2021-01-27 14:30 UTC, ShubArseniy requested changes

2021-01-27 14:30 UTC, ShubArseniy commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +            //wayBillDocument.WayBillDocumentItems.Sort((x, y) => x.HoursFrom.CompareTo(y.HoursFrom));
Убирай комментарии + в WayBillDocumentParser куча закомменченных строк

2021-01-27 14:33 UTC, ShubArseniy commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                return;// TODO gavr тут нужно выводить сообщение или типа того
Если нужно так что не выводится?

2021-01-27 14:35 UTC, ShubArseniy commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                }
?

2021-01-27 14:38 UTC, ShubArseniy commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                employeeToCars[employeer] = carsStack.Pop();
А если стек пустой? + не employeer а employee

2021-01-27 14:41 UTC, ShubArseniy commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                    }
Это мелочь, но зачем так медленно, можно же currentDayOrders = currentDayOrders.Skip()

2021-01-27 14:46 UTC, ShubArseniy commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +			// ViewModel.EndDate = DateTime.Now + TimeSpan.FromDays(7) + TimeSpan.FromHours(23);
И тут комментарий

2021-01-27 14:48 UTC, ShubArseniy commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +            );
EntityAutocompleteSelectorFactory надо создавать где-то в MainWindow, и прокидывать во ViewModel под интерфейсом. А тут надо только её использовать

2021-01-27 14:49 UTC, ShubArseniy commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +		}
?

2021-01-27 14:51 UTC, ShubArseniy commented on VodovozBusiness/Domain/Documents/WayBillDocument.cs
> +
Почему репозиторий не прокидывается? Или нет возможности?

2021-01-28 06:56 UTC, efimov90 commented on VodovozBusiness/Domain/Documents/WayBillDocument.cs
> +
Статический метод

2021-01-28 06:57 UTC, efimov90 commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +		}
Убрал, это не нужно

2021-01-28 06:58 UTC, efimov90 commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +            );
Это View, не ViewModel

2021-01-28 06:58 UTC, efimov90 commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +			// ViewModel.EndDate = DateTime.Now + TimeSpan.FromDays(7) + TimeSpan.FromHours(23);
Убрал

2021-01-28 06:58 UTC, efimov90 commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                    }
Заменил

2021-01-28 06:59 UTC, efimov90 commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                employeeToCars[employeer] = carsStack.Pop();
если стек пустой - то сюда не зайдёт

2021-01-28 06:59 UTC, efimov90 commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                }
Добавил окно с ошибкой

2021-01-28 06:59 UTC, efimov90 commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +                return;// TODO gavr тут нужно выводить сообщение или типа того
Уже выводится

2021-01-28 06:59 UTC, efimov90 commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +            //wayBillDocument.WayBillDocumentItems.Sort((x, y) => x.HoursFrom.CompareTo(y.HoursFrom));
Уже почистил

2021-01-28 07:03 UTC, ShubArseniy commented on Vodovoz/Views/Accounting/WayBillGeneratorView.cs
> +            );
Ну так, AutocompleteSelectorFactory не должна создаваться на уровне View, тут она должна использовать  свойство, которое находится во ViewModel

2021-01-28 07:05 UTC, ShubArseniy commented on VodovozBusiness/DocTemplates/WayBillDocumentParser.cs
> +
А эти комментарии нужны что ли?

2021-01-28 08:23 UTC, ShubArseniy commented on Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> +        public event PropertyChangedEventHandler PropertyChanged;
Для чего это тут? Класс же наследуется от PropertyChangedBase

2021-01-28 09:40 UTC, ShubArseniy approved these changes

2021-01-28 09:40 UTC, merged