3565- Журнал премий переписан на мультипл, добавлено отображение автопремий, переписан журнал шаблонов премий
VodovozOrganization/Vodovoz pull request #590
Opened 2021-06-04 18:47 UTC by Art8m

На мультипл, отображать оба вида премий. В диалоге автопремий заблокировать редактирование. Создать 2 диалога для старой и новой премии. Также необходимо создать журнал PremiumTemplate, View и ViewModel к нему.

2021-06-07 07:35 UTC, ShubArseniy requested changes

2021-06-07 07:35 UTC, ShubArseniy commented on VodovozBusiness/Domain/Employees/PremiumRaskatGAZelle.cs
> +		}
Сделай лямбду и используй $""

2021-06-07 07:35 UTC, ShubArseniy commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +					.AddColumn("Тип").AddTextRenderer(node => node.ViewType)
В ноде Date не nullable или я что-то путаю?

2021-06-07 07:35 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalNodes/PremiumJournalNode.cs
> +		public string ViewType { get; set; }
PremiumSumm почему 2 mm?

2021-06-07 07:35 UTC, ShubArseniy commented on Vodovoz/Views/Employees/PremiumRaskatGAZelleView.cs
> +
Положи лучше Items.FirstOrDefault().Employee.FullName в VM

2021-06-07 07:35 UTC, ShubArseniy commented on Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.PremiumTemplateJournalFilterView.cs
> +}
Это что?

2021-06-07 07:35 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumTemplateJournalViewModel.cs
> +		{
Явно длиннее 140 символов, в другий местах тоже поправь

2021-06-07 07:35 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumTemplateJournalViewModel.cs
> +
Если Шаблоны премий в именительном падеже, то сделай так как-то Журнал 'Шаблоны премий'

2021-06-07 07:35 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +						var row = selectedItem;
Почему команды по-разному написаны? Внизу проверка на null другая

2021-06-07 07:35 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +				return false;
Скобки, а также надо сделать чтобы человек, у которого нет права на редактирование всё равно мог создать премию, если у него есть право на создание. Где-то были примеры, поищи

2021-06-07 10:01 UTC, Art8m commented
Всё поправил

2021-06-07 10:23 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +
Если не хочешь ошибки на Cast пиши OfType

2021-06-07 10:23 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +				));
А зачем тебе нужна SelectionChangedCommand если можно параметр прямо сюда передать? Я бы понял если бы ты в CanExecute сюда проверку поставил на selectedItem, а так не понимаю

2021-06-07 10:23 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumTemplateJournalViewModel.cs
> +					.Select(() => premiumTemplateAlias.PremiumMoney).WithAlias(() => resultAlias.PremiumMoney)
Зачем тут группировка? Она же ничего не делает

2021-06-07 10:23 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +
Неа

2021-06-07 10:23 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +						Projections.Constant("\n"))).WithAlias(() => resultAlias.EmployeesName)
Глянь на CustomProjections.GroupConcat. Попробуй на него заменить. И было бы классно туда и CONCAT_WS добавить

2021-06-09 06:29 UTC, ShubArseniy approved these changes

2021-06-09 06:46 UTC, Druchik commented on Vodovoz/Filters/GtkViews/PremiumJournalFilterView.cs
> +			dateperiodpickerPremiumDate.EndDateOrNull = DateTime.Today;
А чего не во вьюмодели?

2021-06-09 07:16 UTC, Druchik commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +					.AddColumn("Сумма премии").AddTextRenderer(node => node.PremiumSum.ToString())
Можно в numericRenderer выводить, чтобы ToString не вызывать

2021-06-09 07:21 UTC, Druchik commented on VodovozBusiness/Domain/Employees/PremiumTemplate.cs
>  			set { SetField(ref reason, value, () => Reason); }
Опять старый "формат". Убери лямбду везде

2021-06-09 07:38 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +						() => employeeAlias.LastName,
Поиск только по фамилии, почему не по ФИО?

2021-06-09 07:40 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					() => employeeAlias.LastName,
Аналогично

2021-06-09 07:43 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					).WithAlias(() => resultAlias.EmployeesName)
Это точно нужно? concat_ws оборачивается груп конкатом

2021-06-09 07:48 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumTemplateJournalViewModel.cs
> +		private readonly IUnitOfWorkFactory unitOfWorkFactory;
Разве его нет в родительском классе?

2021-06-09 07:50 UTC, Druchik commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +		private readonly IEmployeeService employeeService;
Вроде приватные поля договорились начинать с "подчеркивания"

2021-06-09 07:55 UTC, Druchik commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +		private void OnEmployee_Add(object sender, JournalSelectedNodesEventArgs e)
Методы должны быть без "подчеркивания" (PascalCase)

2021-06-09 07:55 UTC, Druchik commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +		private void OnPremiumTemplate_Select(object sender, JournalSelectedNodesEventArgs e)
оно же

2021-06-09 07:55 UTC, Druchik commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +		private void OnObservableItems_ListContentChanged(object sender, EventArgs e)
Туда же

2021-06-09 08:03 UTC, Druchik commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +			if(!GetAuthor(out author))
фигурные скобки

2021-06-09 08:47 UTC, Art8m commented on Vodovoz/Filters/GtkViews/PremiumJournalFilterView.cs
> +			dateperiodpickerPremiumDate.EndDateOrNull = DateTime.Today;
перенёс

2021-06-09 08:47 UTC, Art8m commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +					.AddColumn("Сумма премии").AddTextRenderer(node => node.PremiumSum.ToString())
поправил

2021-06-09 08:47 UTC, Art8m commented on VodovozBusiness/Domain/Employees/PremiumTemplate.cs
>  			set { SetField(ref reason, value, () => Reason); }
Его не я делал, я просто в него метод ToString добавил, но поправил и это

2021-06-09 08:48 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +						() => employeeAlias.LastName,
Сделал по ФИО

2021-06-09 08:49 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					).WithAlias(() => resultAlias.EmployeesName)
груп конкат - чтобы выводить в ФИО столбик для одной ячейки,  concat_ws - чтобы сформировать ФИО.
В одной ячейке таблицы несколько ФИО:
Иванов Иван Иванович
Петров Пётр Петрович
...

2021-06-09 08:50 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumTemplateJournalViewModel.cs
> +		private readonly IUnitOfWorkFactory unitOfWorkFactory;
исправил

2021-06-09 08:50 UTC, Art8m commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +		private readonly IEmployeeService employeeService;
Везде поправил

2021-06-09 08:50 UTC, Art8m commented on VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
> +		private void OnEmployee_Add(object sender, JournalSelectedNodesEventArgs e)
исправил

2021-06-09 08:56 UTC, ShubArseniy commented on Vodovoz/Filters/GtkViews/PremiumJournalFilterView.cs
> +
Почему не EntityViewModelEntry?

2021-06-09 09:17 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					).WithAlias(() => resultAlias.EmployeesName)
Проверял, нормально ищет?

2021-06-09 09:18 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +							),
Разве сюда нельзя подкинуть тот проджекшион по ФИО?

2021-06-09 09:19 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					).WithAlias(() => resultAlias.EmployeesName)
Тоже самое

2021-06-09 09:29 UTC, Druchik commented on Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
> +					.AddColumn("Номер").AddNumericRenderer(node => node.Id.ToString())
Поспешил

2021-06-09 09:39 UTC, Druchik commented on VodovozViewModels/Journals/FilterViewModels/Employees/PremiumJournalFilterViewModel.cs
> +			StartDate = EndDate = DateTime.Today;
Мне кажется лучше проинициализировать приватные поля, чтобы на старте лишний раз не обращаться к журналу по событию. Проверь, как будет работать

2021-06-09 10:12 UTC, Art8m commented on Vodovoz/Filters/GtkViews/PremiumJournalFilterView.cs
> +
исправил

2021-06-09 10:12 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					).WithAlias(() => resultAlias.EmployeesName)
Да, проверял, нормально

2021-06-09 10:17 UTC, Art8m commented on VodovozViewModels/Journals/FilterViewModels/Employees/PremiumJournalFilterViewModel.cs
> +			StartDate = EndDate = DateTime.Today;
Да, согласен, поправил, проверил, работает нормально

2021-06-09 10:34 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					.Select(CustomProjections.Concat_WS(" ", employeeProjection)).WithAlias(() => resultAlias.EmployeesName)
Сюда же просто продж идет, разве нет?

2021-06-09 11:03 UTC, Art8m commented on VodovozViewModels/Journals/JournalViewModels/Employees/PremiumJournalViewModel.cs
> +					.Select(CustomProjections.Concat_WS(" ", employeeProjection)).WithAlias(() => resultAlias.EmployeesName)
поправил

2021-06-09 11:53 UTC, ShubArseniy approved these changes

2021-06-09 11:58 UTC, merged