3587 - Для разовых водителей обязательное поле Водительское удостоверение, необязательное Главный документ
VodovozOrganization/Vodovoz pull request #598
Opened 2021-06-09 07:50 UTC by Art8m

Если при создании сотрудника-водителя стоит галочка на Разовый:
- сделать обязательным поле Водительское удостоверение
- убрать обязательность главного документа

2021-06-09 09:21 UTC, Enzogord commented on VodovozBusiness/Domain/Employees/Personnel.cs
> +			if(mainDocuments.Count <= 0 && !((Employee)this).IsDriverForOneDay)
А если Personnel будет не Employee?

2021-06-09 09:22 UTC, Enzogord commented on VodovozBusiness/Domain/Employees/Personnel.cs
> +			if(String.IsNullOrEmpty(DrivingLicense) && ((Employee)this).IsDriverForOneDay)
Тоже самое

2021-06-09 09:23 UTC, Enzogord requested changes
Валидацию Employee лучше перенести в Employee.

2021-06-09 12:45 UTC, Art8m commented
Перенёс валидацию Employee в Employee

2021-06-10 13:35 UTC, Enzogord requested changes

2021-06-10 13:35 UTC, Enzogord commented on VodovozBusiness/Domain/Employees/Employee.cs
> +			var employees = UoW.Session.QueryOver<Employee>()
А это лучше оставить в Personel, так как ФИО хранится именно в нем.
Но проверять по Employee не правильно. Попробуй написать запрос для Personel, должен работать.
Есть примеры для OrderDocument по такому же принципу.

2021-06-11 07:21 UTC, Enzogord approved these changes

2021-06-11 07:21 UTC, merged