3599 История печати маршрутных листов
VodovozOrganization/Vodovoz pull request #625
Opened 2021-06-18 09:25 UTC by kozlov-d

- Добавил таблицу истории печати документов
- Добавил в МЛ список с историей печати и метод для добавления
- Заменил использование былого PrintTime на последний элемент списка
- Удалил printTime из маппинга и МЛ
- Обнаружил, что при печати из некоторых диалогов PrintTime раньше выставлялся дважды, а после переделывания на историю печати - по два раза создается история. Пофиксил
- Выделил метод со статусами МЛ, который печатается как закрытый
С маппингами и созданием таблицы мог намудрить лишнего, так что желательно проверить еще скрипт, которым создается новая таблица

2021-06-21 07:21 UTC, Enzogord requested changes

2021-06-21 07:21 UTC, Enzogord commented on VodovozBusiness/Domain/Documents/DocumentsPrintHistory.cs
> +	public class DocumentsPrintHistory : PropertyChangedBase, IDomainObject
Переименуй пожалуйста в DocumentPrintHistory, тут работа с одним документом а не со списком

2021-06-21 07:21 UTC, Enzogord commented on VodovozBusiness/Domain/Logistic/RouteList.cs
> +					if(PrintsHistory?.Count > 0) {
В таких ситуациях лучше использовать .Any()
Ему достаточно посмотреть на первый элемент, а не считать все.

2021-06-21 09:55 UTC, kozlov-d commented on VodovozBusiness/Domain/Documents/DocumentsPrintHistory.cs
> +	public class DocumentsPrintHistory : PropertyChangedBase, IDomainObject
Переименовал

2021-06-21 09:56 UTC, kozlov-d commented on VodovozBusiness/Domain/Logistic/RouteList.cs
> +					if(PrintsHistory?.Count > 0) {
Заменил везде

2021-06-22 08:48 UTC, Enzogord approved these changes

2021-06-22 08:48 UTC, merged