3387 Исправил сброс пароля при добавлении email
VodovozOrganization/Vodovoz pull request #628
Opened 2021-06-18 15:15 UTC by kozlov-d

Проблема была в том, что UoW.GetById получал сущность без обновленного email, хотя в базе обновление происходило. Сначала просто сделал еще один вызов GetById через новый uowWithoutRoot, что сработало, но потом вспомнил про session.refresh

2021-06-18 15:18 UTC, efimov90 requested changes
Есть подписка на обновление, в журналах это не требуется, посмотри как в журнала МЛ это делается там вроде локальный UoW создается для перевода МЛ в другой статус.

2021-06-18 15:52 UTC, kozlov-d commented
@Enzogord призываю, чтобы ты разъяснил, как лучше, через refresh или новый uow и почему

2021-06-21 07:43 UTC, Enzogord requested changes

2021-06-21 07:43 UTC, Enzogord commented on Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
> +			NotifyConfiguration.Enable();
Не надо вызывать Enable, это глобальное включение подписок, и оно уже включено

2021-06-21 07:43 UTC, Enzogord commented on Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
> +			Refresh();
Просто рефреша не достаточно? Для чего понадобилась очистка сессии?

2021-06-21 07:44 UTC, Enzogord commented
> @Enzogord призываю, чтобы ты разъяснил, как лучше, через refresh или новый uow или вообще через отдельную подписку и почему

Обычно достаточно просто вызвать рефреш журнала.

2021-06-21 12:11 UTC, kozlov-d commented on Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
> +			Refresh();
Сейчас вообще происходит непонятная вещь. Собрал дев, т.е. без изменений этого ПР. Не удается воспроизвести момент, чтобы getById возвращал сотрудника с неактуальной почтой. В то же время, на свежем деве на удаленке проблема имеется.
Очистку добавил по совету Сергея, как и подписку через NotifyConfiguration, изначально просто рефреш не помог, сейчас же как раз хотел проверить, нужна ли была она, а проблема не воспроизводится. 
Если просто вызывать refresh, то на каком моменте? Перед uow.getById?
NotifyConfiguration.Enable() кстати есть в RouteListsVM.

2021-06-22 08:40 UTC, Enzogord commented on Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
> +			Refresh();
"NotifyConfiguration.Enable() кстати есть в RouteListsVM"
И там он не нужен

2021-06-22 08:47 UTC, Enzogord commented
Сделай получение Employee в новом UoW, там же от него нужны все лишь несколько полей, и сама сущность не взаимодействует с основным uow.

2021-06-23 06:37 UTC, Enzogord approved these changes

2021-06-25 12:58 UTC, efimov90 approved these changes

2021-06-25 13:05 UTC, merged