3597 - События ТС (доработки по уточнениям ТЗ)
VodovozOrganization/Vodovoz pull request #633
Opened 2021-06-21 14:38 UTC by Art8m

1. В журнале событий ТС, в столбце "Событие" представлено сокращенное название события, лучше указывать полное название, а не сокращенное. Также необходимо ограничить ширину столбца, если название события не входит, делать перенос текста (расширять вниз строку).
2. Тип авто: необходимо использовать сокращения: ЛК, ГК, для наемного транспорта ставить Н, для раската НРЛ (для наемных раскатных ларгусов), НРГ (для наемных раскатных газелей).
3. В требованиях указано наличие столбца "Софийская"/ Парнас, сейчас туда записывается информация о подразделении. Надо в этот столбец подтягивать  из карточки авто обслуживаемую часть города. (Север/Юг).
4. Фамилия Имя Отчество водителя сократить до Фамилия И.О.
5. Комментарий в журнале событий ТС, если очень длинный также реализовать ограничение на размер столбца, если комментарий не входит в одну строку, сделать перенос текста (расширять строку вниз), см п.1.
6. Фамилия Имя Отчество автора сократить до Фамилия И.О, как в п.3.
7. Не работает фильтр по дате создания. Исправить.
8. При редактировании названия события в справочнике событий и сохранении изменений, в журнале не актуализируется название события в уже созданных ранее записях. Будем иметь путаницу – в справочнике событий, событию изменили название, а в журнале указано старое, которого в справочнике нет. Поиск по нему  в справочнике ничего не будет выдавать.  - Исправить.

2021-06-22 08:33 UTC, Enzogord requested changes

2021-06-22 08:33 UTC, Enzogord commented on VodovozBusiness/Domain/Logistic/CarEvent.cs
> +				yield return new ValidationResult("Превышена максимальная длина комментария.",
Добавь инфу о допустимой длине

2021-06-22 08:33 UTC, Enzogord commented on VodovozBusiness/Domain/Logistic/CarEventType.cs
> +				yield return new ValidationResult("Превышена максимальная длина названия.",
Добавь инфу о допустимой длине

2021-06-22 08:33 UTC, Enzogord commented on VodovozBusiness/Domain/Logistic/CarEventType.cs
> +				yield return new ValidationResult("Превышена максимальная длина сокращённого названия.",
Добавь инфу о допустимой длине

2021-06-22 10:25 UTC, Art8m commented
Информацию о допустимой длине добавил.

2021-06-23 06:39 UTC, Enzogord approved these changes

2021-06-23 06:39 UTC, merged