Изменена проверка видимости поля сиатьи расхода
VodovozOrganization/Vodovoz pull request #72
Opened 2021-02-02 14:11 UTC by efimov90

Добавлено условие для сохранения - в случае если пользвоатель фининсист статья расхода должна быть заполнена
Исправлено сообщение об ошибке при добавлении суммы и не заполненной статье расхода

2021-02-02 15:01 UTC, Enzogord requested changes

2021-02-02 15:01 UTC, Enzogord commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +        public bool ExpenseCategorySensitive => (Entity.State == CashRequest.States.New
Это свойство не уведомляет о том что его состояние поменялось? Если нет то надо добавить, иначе ничего не обновится.

2021-02-03 05:47 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +        public bool ExpenseCategorySensitive => (Entity.State == CashRequest.States.New
Тогда нужно обновлять и свойство выше, так как это родилось как его копия с измененным содержанием.
Если это действительно нужно.

2021-02-03 10:33 UTC, Enzogord approved these changes

2021-02-03 10:33 UTC, merged