3494 - Классификация рекламаций (Объекты рекламаций)
VodovozOrganization/Vodovoz pull request #730
Opened 2021-07-12 22:26 UTC by Art8m

1. Добавлен журнал «Объекты рекламаций» (новый уровень вложенности для видов рекламаций). Сущности из этого справочника могут быть присвоены сущностям из справочника «Виды рекламаций».

2. При создании/редактировании рекламации, а также в фильтре журнала рекламаций добавлен выбор из журнала «Объекты рекламаций». При выборе определенного объекта рекламации, выпадающий список видов рекламаций будет соответствовать присвоенным данному объекту видам.

3. В справочнике «Виды рекламаций» добавлена возможность добавления "Подключаемых" отделов (добавлением в таблицу).

4. При редактировании рекламации в форме подключения подразделений добавлена кнопка «Подключить отделы по виду рекламации»

5. Добавлен журнал Видов рекламаций с фильтром по Объектам рекламаций.

2021-07-13 10:05 UTC, ShubArseniy requested changes
И где изменения печатной формы?

2021-07-13 10:05 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintObjectJournalViewModel.cs
> +			}
Что за нули?

2021-07-13 10:44 UTC, Art8m commented on Vodovoz/Filters/GtkViews/ComplaintObjectJournalFilterView.cs
> +				.InitializeFromSource();
В ТЗ, которое прикреплено к задаче, там п.3.1.2.1:
"А также следующих фильтров:
...
Показывать объекты в архиве – чекбокс, при установке галочки, на который отображаются заархивированные объекты. 
Дата архивации – поля периода архивации объекта. Появляется только если установлена галочка «Показывать объекты в архив»"

2021-07-13 10:51 UTC, Art8m commented on VodovozBusiness/Domain/Complaints/ComplaintObject.cs
> +		}
Это перепутал, она только в ComplaintKind должна быть, удалил.

2021-07-13 10:51 UTC, ShubArseniy commented on Vodovoz/Filters/GtkViews/ComplaintObjectJournalFilterView.cs
> +				.InitializeFromSource();
Нужно поднять вопрос об актуальности этих полей

2021-07-13 12:53 UTC, Art8m commented on Vodovoz/Filters/GtkViews/ComplaintObjectJournalFilterView.cs
> +				.InitializeFromSource();
Даша сказала убрать эту дату, убрал.

2021-07-13 12:56 UTC, Art8m commented
Всё исправил.

2021-07-14 06:28 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Complaints/CreateInnerComplaintViewModel.cs
> +
Ниже грузятся, только не архивные

2021-07-14 06:28 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Complaints/CreateComplaintViewModel.cs
> +
Тоже самое

2021-07-14 06:28 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
> +
И тут

2021-07-14 08:06 UTC, Art8m commented
Исправил. Также убрал добавление в список выбора архивного вида рекламаций в диалоге создания рекламации (при редактировании оставлено)

2021-07-14 08:41 UTC, ShubArseniy approved these changes

2021-07-14 08:42 UTC, merged