3600 Новый запрос в диалог талона погрузки
VodovozOrganization/Vodovoz pull request #745
Opened 2021-07-15 10:58 UTC by DobriyMisha

Добавлен новый тип с полями OwnType и ExpirationDate
Добавлен новый запрос к базе (заполнение талона погрузки, поиск уже погруженных в других талонах), разделяющий номенклатуры по принадлежности и ExpirationDate
Добавлена логика заполнения списка номенклатур с делением из запроса

2021-07-15 12:05 UTC, ShubArseniy requested changes

2021-07-15 12:05 UTC, ShubArseniy commented on VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.List<GoodsInRouteListResultToDivide>();
Сомневаюсь что это заработает правильно если вообще не группировать данные. Т.е. а если у тебя уже сформировано 2 талона с одинаковыми номенклатурами, то в что в третьем будет показываться?

Почему решил не использовать GoodsInRouteListResultWithSpecialRequirements? Также добавь пробелы в лямбды

2021-07-15 12:05 UTC, ShubArseniy commented on VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +	}
Пустая строка

2021-07-15 14:33 UTC, DobriyMisha commented on VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +				.List<GoodsInRouteListResultToDivide>();
Добавил группировку.
Не использовал другой тип потому, что там лишнее поле, для конкретики создал новый.

2021-07-15 14:33 UTC, DobriyMisha commented on VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +	}
исправлено

2021-07-15 14:33 UTC, DobriyMisha commented on VodovozBusiness/Domain/Documents/CarLoadDocument.cs
>  			}
изменено

2021-07-16 06:16 UTC, ShubArseniy approved these changes

2021-07-16 06:28 UTC, merged