Рефакторинг репозиториев
VodovozOrganization/Vodovoz pull request #818
Opened 2021-08-11 08:32 UTC by Druchik

Удалил статические репозитории;
Вместо них и синглтонов создал обычные;
Поменял везде вызовы и создание этих репозиториев;

2021-08-11 13:21 UTC, ShubArseniy approved these changes

2021-08-16 10:35 UTC, efimov90 requested changes

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Equipments/EquipmentKindRepository.cs
> +		public List<EquipmentKind> GetPaidRentEquipmentKinds (IUnitOfWork uow)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Equipments/EquipmentLocation.cs
> +						return $"У {Counterparty.Name}{(DeliveryPoint != null ? " на адресе " + DeliveryPoint.Title : string.Empty)}";
пробел между { и значением }

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Equipments/EquipmentLocation.cs
> +						return $"На складе: {Warehouse.Name}";
пробел между { и значением }

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Fuel/FuelRepository.cs
> +				//.Where(() => operationAlias.Fuel.Id == fuel.Id) - ибо хотят для чего то литры бензина суммировать с литрами дизеля о_О
это еще нужно?

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/IDeliveryShiftRepository.cs
> +		IList<DeliveryShift> ActiveShifts (IUnitOfWork uow);
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/DriverPosition.cs
> +		public int DriverId { get; set;}
пробелы после ;

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/DeliveryShiftRepository.cs
> +		public IList<DeliveryShift> ActiveShifts (IUnitOfWork uow)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/CachedDistanceRepository.cs
> +		public IList<CachedDistance> GetCache (IUnitOfWork uow, long[] hash)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/ICachedDistanceRepository.cs
> +		IList<CachedDistance> GetCache (IUnitOfWork uow, long[] hash);
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/IRouteColumnRepository.cs
> +		IList<RouteColumn> ActiveColumns (IUnitOfWork uow);
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Logistic/RouteColumnRepository.cs
> +		public IList<RouteColumn> ActiveColumns (IUnitOfWork uow)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Operations/IWagesMovementRepository.cs
> +		decimal GetCurrentEmployeeWageBalance (IUnitOfWork uow, int employeeId);
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Operations/WagesMovementRepository.cs
> +		public decimal GetCurrentEmployeeWageBalance (IUnitOfWork uow, int employeeId)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Organizations/OrganizationRepository.cs
> +			if (string.IsNullOrWhiteSpace(accountNumber))
пробел после if

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Organizations/OrganizationRepository.cs
> +			if (string.IsNullOrWhiteSpace(inn))
пробел после if

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/RentPackages/IRentPackageRepository.cs
> +		FreeRentPackage GetFreeRentPackage (IUnitOfWork uow, EquipmentKind equipmentKind);
пробел перед скобкой и ниже тоже самое

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/RentPackages/RentPackageRepository.cs
> +		public FreeRentPackage GetFreeRentPackage (IUnitOfWork uow, EquipmentKind equipmentKind)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/RentPackages/RentPackageRepository.cs
> +		public PaidRentPackage GetPaidRentPackage (IUnitOfWork uow, EquipmentKind equipmentKind)
пробел перед скобкой

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Undeliveries/UndeliveredOrderCommentsNode.cs
> +		public string MarkedupComment => String.Format(
в интерполяцию

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Undeliveries/UndeliveredOrderCommentsNode.cs
> +		public string UserDateAndName => String.Format(
в интерполяцию

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
>          #region Получение номенклатур воды
Мне это все не нравится =_=" может задачу на рефакторинг этой штуки сделать?

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/Parameters/ParametersProvider.cs
> +			if (_parameters.ContainsKey(parameterName))
пробел перед if

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/Parameters/ParametersProvider.cs
> +				if (_parameters.ContainsKey(parameterName))
пробел перед иф

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/Parameters/ParametersProvider.cs
> +					if (_parameters.ContainsKey(parameter.Name))
пробел перед иф

2021-08-16 10:35 UTC, efimov90 commented on VodovozBusiness/Parameters/ParametersProvider.cs
> +			if (_parameters.TryGetValue(name, out var oldParameter))
пробел перед иф

2021-08-16 10:35 UTC, efimov90 commented on VodovozViewModels/ViewModels/Complaints/CreateComplaintViewModel.cs
> +			var curClient = UoW.GetById<Counterparty>(client.Id);
currentClient

2021-08-16 14:16 UTC, Druchik commented on Vodovoz/Dialogs/Logistic/RoutesAtDayDlg.cs
>  				return true;
Логику вообще не проверял особо

2021-08-19 06:28 UTC, Druchik commented on Vodovoz/ViewModels/FuelDocuments/FuelDocumentViewModel.cs
> +				text.Add($"Расстояние по треку: {curTrack.TotalDistance:f1}({curTrack.Distance ?? 0:N1}+{curTrack.DistanceToBase ?? 0:N1}) км.");
С форматами не пойдет. Нельзя пробел ставить после него

2021-08-19 06:54 UTC, Druchik commented on VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
>          #region Получение номенклатур воды
Надо сначала это обсудить

2021-08-19 08:33 UTC, efimov90 approved these changes

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/Dialogs/Logistic/RouteListTrackDlg.cs
> +			if (_currentEmployee == null)
пробел перед скобкой

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/Dialogs/Logistic/RoutesAtDayDlg.cs
> +			foreach(var b in _geographicGroupRepository.GeographicGroupsWithCoordinates(UoW)) {
скобку на новую строку

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/Dialogs/Logistic/TrackOnMapWnd.cs
> +						_logger.Info ("В разрыве найдены выполенные адреса порядковый(е) номер(а) {0}", String.Join (", ", throughAddress.Select (x => x.IndexInRoute)));
пробел перед скобкой

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/Dialogs/Logistic/TrackOnMapWnd.cs
> +						_logger.Info ("В разрыве найдены выполенные адреса порядковый(е) номер(а) {0}", String.Join (", ", throughAddress.Select (x => x.IndexInRoute)));
и интерполяция

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/Dialogs/Logistic/TrackOnMapWnd.cs
> +					_logger.Info ("Найден разрыв в треке расстоянием в {0}", distance);
интерполяция

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			if(!EmailServiceSetting.SendingAllowed || _emailRepository.HaveSendedEmail(Entity.Id, OrderDocumentType.Bill)) {
скобка на новую строку

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ReportsParameters/Store/NomenclatureForShipment.cs
> +			foreach(var item in _filter.GetParameters()) {
скобка на новую строку

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ServiceDialogs/LoadFrom1cDlg.cs
> +					banks = BankRepository.ActiveBanks (_uow);
пробел перед скобкой

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ServiceDialogs/LoadFrom1cDlg.cs
> +			_uow.Commit ();
пробел перед скобкой

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ServiceDialogs/LoadFrom1cDlg.cs
> +			var ExistCouterpaties = _counterpartyRepository.GetCounterpartiesByCode1c (_uow, counterpartyCodes1c);
пробел перед скобкой

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ServiceDialogs/LoadFrom1cDlg.cs
> +					_uow.Save (loaded);
пробел

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ServiceDialogs/LoadFrom1cDlg.cs
> +					_uow.Save (loaded);
пробел

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ServiceDialogs/LoadFrom1cDlg.cs
> +					_uow.Save (order);
пробел

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ViewWidgets/UndeliveredOrderView.cs
> +			if(_undelivery.DriverCallType == DriverCallType.NoCall) {
скобка с новой строки

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ViewWidgets/UndeliveredOrderView.cs
> +			if(_undelivery.NewOrder == null) {
скобка с новой строки

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ViewWidgets/UndeliveredOrderView.cs
> +				if(_oldOrder.Id == selectedId) {
скобка

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ViewWidgets/UndeliveredOrderView.cs
> +				if ((_oldOrder.PaymentType == Domain.Client.PaymentType.ByCard) &&
пробел

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ViewWidgets/UndeliveredOrderView.cs
> +			if(_undelivery.Id == 0) {
скобка

2021-08-19 08:33 UTC, efimov90 commented on Vodovoz/ViewWidgets/UndeliveredOrderView.cs
> +			if(_undelivery.Id == 0) {
и ниже

2021-08-19 08:35 UTC, merged