3694 Заказы складской логистики
VodovozOrganization/Vodovoz pull request #823
Opened 2021-08-12 10:02 UTC by DobriyMisha

Добавлена в заказ галочка "Складская логистика" - заказы внутренних перемещений.
Добавлено новое enum-свойство в заказ - "Тип адреса доставки".
Добавлена логика авто-присвоения значения свойства в ситуациях сервисного заказа или сетевого контрагента.
Добавлена новая галочка "Складская логистика" в фильтр при создании МЛ на день. 
Изменен алгоритм фильтра в соответствии с новым enum.

2021-08-12 10:34 UTC, kozlov-d requested changes
Конкретно логику не смотрел, но по оформлению точно нужны правки

2021-08-12 10:34 UTC, kozlov-d commented on Vodovoz/gtk-gui/gui.stetic
> -                <property name="Active">True</property>
Залетел мусор

2021-08-12 10:34 UTC, kozlov-d commented on Vodovoz/gtk-gui/gui.stetic
> -                <property name="Active">True</property>
И так далее sensitive и active + widget hideForwaders

2021-08-12 10:34 UTC, kozlov-d commented on VodovozBusiness/Domain/Orders/Order.cs
> +		private OrderAddressType orderAddressType;
_prefix, наверх вроде не обязательно убирать, когда свойство + backing field

2021-08-12 10:34 UTC, kozlov-d commented on VodovozBusiness/Domain/Orders/Order.cs
> +		bool isStorageLogic;
private + _prefix

2021-08-12 10:34 UTC, kozlov-d commented on VodovozBusiness/HibernateMapping/Order/OrderMap.cs
> +			Map(x => x.OrderAddressType)				  .Column("order_address_type")
Этот отступ точно отображается на одном уровне с другими?

2021-08-12 10:34 UTC, kozlov-d commented on VodovozViewModels/Journals/JournalNodes/AddressType.cs
> +		[Display(Name = "Складская логика")]
Заголовок задачи "Складская логистика". StorageLogic тоже надо поменять.

2021-08-12 10:34 UTC, kozlov-d commented on Vodovoz/Representations/RouteListsVM.cs
> +			if( Filter.WithDeliveryAddresses &&  Filter.WithChainStoreAddresses && !Filter.WithServiceAddresses) {
Лишние пробелы, и не только в начале

2021-08-12 10:34 UTC, kozlov-d commented on VodovozViewModels/Journals/JournalNodes/AddressType.cs
> +		[Display(Name = "Складская логика")]
И связанные с этим другие поля также желательно поменять, типа IsStoreLogic. И виджеты тоже. Если конечно не обсуждалось, что название именно такое

2021-08-12 10:34 UTC, kozlov-d commented on Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
> +					//фильтрация от обратного: если не выбрано - удаляется
я может туплю, но почему нельзя было сделать прямую фильтрацию

2021-08-12 10:36 UTC, kozlov-d commented on Vodovoz/Representations/RouteListsVM.cs
> +			if( Filter.WithDeliveryAddresses &&  Filter.WithChainStoreAddresses && !Filter.WithServiceAddresses) {
+ новая строка для {

2021-08-12 11:10 UTC, Druchik commented
А где вся логика по работе с новым энамом в заказе? Если я правильно понимаю, то в текущей реализации мне ничего не мешает напихать в заказ сетевого контрагента сервисной номенклатуры и он сменится на сетевой заказ. Да и по остальным пунктам у меня сомнения. Например, сохранили с сервисной номенклатурой, а потом зашли и удалили ее. Заказ должен стать не сервисным. Хотя, может я чего упустил?

2021-08-12 11:11 UTC, DobriyMisha commented on Vodovoz/Representations/RouteListsVM.cs
> +			if( Filter.WithDeliveryAddresses &&  Filter.WithChainStoreAddresses && !Filter.WithServiceAddresses) {
пофиксил

2021-08-12 11:11 UTC, DobriyMisha commented on VodovozViewModels/Journals/JournalNodes/AddressType.cs
> +		[Display(Name = "Складская логика")]
Изменил всё на StorageLogistics

2021-08-12 11:11 UTC, DobriyMisha commented on VodovozBusiness/HibernateMapping/Order/OrderMap.cs
> +			Map(x => x.OrderAddressType)				  .Column("order_address_type")
Поправил

2021-08-12 11:12 UTC, DobriyMisha commented on VodovozBusiness/Domain/Orders/Order.cs
> +		bool isStorageLogic;
изменил

2021-08-12 11:12 UTC, DobriyMisha commented on VodovozBusiness/Domain/Orders/Order.cs
> +		private OrderAddressType orderAddressType;
изменил

2021-08-13 10:57 UTC, DobriyMisha commented on Vodovoz/gtk-gui/gui.stetic
> -                <property name="Active">True</property>
Мусор исправлен

2021-08-13 10:58 UTC, DobriyMisha commented
> А где вся логика по работе с новым энамом в заказе? Если я правильно понимаю, то в текущей реализации мне ничего не мешает напихать в заказ сетевого контрагента сервисной номенклатуры и он сменится на сетевой заказ. Да и по остальным пунктам у меня сомнения. Например, сохранили с сервисной номенклатурой, а потом зашли и удалили ее. Заказ должен стать не сервисным. Хотя, может я чего упустил?

Логику поправил

2021-08-13 11:08 UTC, kozlov-d approved these changes
Я кину аппрув, чтобы убрать реквест на изменения, но это чисто по коду, но есть мелочи по отступам. По остальному пускай Андрей смотрит

2021-08-13 11:12 UTC, ShubArseniy commented
У меня ещё пару вопросов, не мержите

2021-08-13 11:52 UTC, ShubArseniy requested changes

2021-08-13 11:52 UTC, ShubArseniy commented on VodovozBusiness/Domain/Employees/UserSettings.cs
>          /// Использовать отдел сотрудника
Зачем подвинул?

2021-08-13 11:52 UTC, ShubArseniy commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
>  				//при удалении номенклатуры выделение снимается и при последующем удалении exception
Что это?

2021-08-13 11:52 UTC, ShubArseniy commented on VodovozBusiness/Domain/Orders/Order.cs
IsService надо полностью выпилить из заказа

2021-08-13 11:52 UTC, ShubArseniy commented on VodovozBusiness/Domain/Orders/Order.cs
> +				);
Используй nameof()

2021-08-16 13:43 UTC, ShubArseniy reviewed
И отчёты ещё забыл

2021-08-16 13:43 UTC, ShubArseniy commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +				}
Убери из Save

2021-08-16 13:43 UTC, ShubArseniy commented on VodovozBusiness/Domain/Orders/Order.cs
> +			get => _isStorageLogistics;
Тоже вроде не нужно

2021-08-16 13:43 UTC, ShubArseniy commented on VodovozBusiness/Domain/Orders/Order.cs
2 лишних строки

2021-08-17 12:33 UTC, ShubArseniy approved these changes

2021-08-17 14:22 UTC, merged