Переписывание журналов аренды и "конвертация" диалогов в MVVM
VodovozOrganization/Vodovoz pull request #916
Opened 2021-08-31 09:14 UTC by Druchik

Добавил новые журналы бесплатной/платной аренд;
Создал вьюхи/вью модели под эту аренду
Поменял вызовы журналов из меню и карточки заказа

2021-08-31 11:03 UTC, Enzogord requested changes

2021-08-31 11:08 UTC, Druchik commented on Vodovoz/Views/Rent/FreeRentPackageView.cs
> +            referenceDepositService.SubjectType = typeof(Nomenclature);
Так это я перебрасываю из ветки по новым заказам. И чтобы не мучаться с GUI на тот момент, т.к. тогда глючила monodevelop, я не стал менять энтри

2021-08-31 11:10 UTC, Enzogord approved these changes

2021-08-31 11:15 UTC, Druchik commented
Рано)) Я еще буду накидывать

2021-08-31 13:41 UTC, efimov90 requested changes

2021-08-31 13:41 UTC, efimov90 commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			return selectedNode == null ? null : UoW.GetById<Nomenclature>(selectedNode.Id);
оберни лучше 3247 в if и если null - то его и возвращай
иначе возвращай результат GetById
в таком виде оно не читабельно

2021-08-31 13:41 UTC, efimov90 commented on Vodovoz/Views/Rent/PaidRentPackageView.cs
> +	        buttonSave.Clicked += (sender, args) => ViewModel.SaveAndClose();
полу табы полу пробелы

2021-08-31 13:41 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +        public decimal Available => InStock - Reserved.GetValueOrDefault();
тут nullref не будет если Default?

2021-08-31 13:41 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +            return string.Format("{0:F" + UnitDigits + "} {1}", value, UnitName);
в интерполяцию

2021-08-31 13:41 UTC, efimov90 commented on VodovozViewModels/Journals/JournalViewModels/Rent/NonSerialEquipmentsForRentJournalViewModel.cs
> +	        EquipmentKind equipmentKind,
полу табы полу пробелы

2021-08-31 13:41 UTC, efimov90 commented on VodovozViewModels/Journals/JournalViewModels/Rent/PaidRentPackagesJournalViewModel.cs
> +	    }
полу табы полу пробелы

2021-08-31 13:54 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +        public decimal Available => InStock - Reserved.GetValueOrDefault();
Там идет выборка Count, который не может быть null. Я логику вообще не отслеживал и думаю надо придерживаться правила: работает - не лезь)

2021-08-31 14:08 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +            return string.Format("{0:F" + UnitDigits + "} {1}", value, UnitName);
Не выйдет. Слишком мудреный формат

2021-08-31 14:09 UTC, Druchik commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			return selectedNode == null ? null : UoW.GetById<Nomenclature>(selectedNode.Id);
Не понял, как ты хочешь обернуть?

2021-08-31 14:09 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Rent/NonSerialEquipmentsForRentJournalViewModel.cs
> +	        EquipmentKind equipmentKind,
Изменил

2021-08-31 14:10 UTC, Druchik commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			return selectedNode == null ? null : UoW.GetById<Nomenclature>(selectedNode.Id);
Сделать через if else в смысле?

2021-08-31 14:59 UTC, efimov90 commented on Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> +			return selectedNode == null ? null : UoW.GetById<Nomenclature>(selectedNode.Id);
if(var selectedNode = e.GetSelected....)
{
return UoW.Get...
}
return null;

или типа того

2021-08-31 14:59 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +        public decimal Available => InStock - Reserved.GetValueOrDefault();
ок

2021-08-31 15:01 UTC, efimov90 commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +            return string.Format("{0:F" + UnitDigits + "} {1}", value, UnitName);
а.. из-за UnitDigits? точно?

2021-08-31 15:10 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Nodes/NomenclatureForRentNode.cs
> +            return string.Format("{0:F" + UnitDigits + "} {1}", value, UnitName);
Точно) Можешь попробовать - получится, милости просим)

2021-09-01 08:49 UTC, efimov90 approved these changes

2021-09-01 11:04 UTC, merged