VV-43, 3709 Заявка на оплату по безналу
VodovozOrganization/Vodovoz pull request #922
Opened 2021-09-02 07:55 UTC by kozlov-d

- Выделил базовый класс для заявок на выплаты
- Добавил наследников по двум типам заявок
- Добавил для новой заявки по безналу VM + V
- Изменил журнал заявок на multiple
- Изменил виджет выбора файла. Не обязательно при создании класса указывать имя файла. Имя файла можно передать при вызове метода, который открывает затем filePickerDialog. Виджет использовался по факту в двух журналах - статей прихода и расхода. Почему для разных открытий журнала задавались разные имена для выгрузок - так и не понял смысла. Кастомное имя задавалось в диалоге CashIncomeDlg и Expense, но при открытии статей расхода из этих диалогов журнал отображается без возможности выгрузить
- Добавил фабрику статей прихода и добавил метод в фабрику статей расхода для создания журнала по уровням. Заменил на фабрики те места где раньше фабрика на месте создавалась и убрал из зависимостей объекты для создания этих фабрик.
- Теперь вроде нигде не осталось создание на месте simple фабрик по статьям расхода и дохода

2021-09-03 06:07 UTC, efimov90 requested changes

2021-09-03 06:07 UTC, efimov90 commented on Vodovoz/Commons/FileChooser.cs
> +        private readonly string _fileName;
Такого быть не должно
filename не может быть readonly или это не filename

2021-09-03 06:31 UTC, efimov90 requested changes
Там где про биндинг - если нет времени можно не делать, все остальное надо исправить

2021-09-03 06:31 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
AcceptCommand может быть null

2021-09-03 06:31 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnGiveSummPartially.Sensitive =
лучше заменить там виджет на тот у которого есть binding, а это условие положить в функцию ViewModel

2021-09-03 06:31 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			yentryReasonForSendToReapproval.Visible = ViewModel.VisibleOnlyForStatusUpperThanCreated;
тоже лучше биндинг

2021-09-03 06:31 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			yentryCancelReason.Visible = ViewModel.VisibleOnlyForStatusUpperThanCreated;
тоже лучше биндинг

2021-09-03 06:31 UTC, efimov90 commented on Vodovoz/Views/Cash/CashlessRequestFilesView.cs
> +			if(ytreeviewFiles.GetSelectedObject() == null || ViewModel.ReadOnly)
поменять местами ReadOnly если там не функция будет выполняться быстрее

2021-09-03 06:31 UTC, efimov90 commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +					if(PayoutRequestState == PayoutRequestState.Agreed ||
|| - на новой строке

2021-09-03 06:31 UTC, efimov90 commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +					if(PayoutRequestState == PayoutRequestState.Submited ||
|| на новой строке

2021-09-03 06:31 UTC, efimov90 commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +					PayoutRequestState = Sums.All(x => x.Sum == x.ObservableExpenses.Sum(e => e.Money)) ? newState : PayoutRequestState.PartiallyClosed;
не превышение длины?

2021-09-03 06:31 UTC, efimov90 commented on VodovozBusiness/Domain/Cash/CashRequest/PayoutRequestBase.cs
> +
лишняя строка

2021-09-03 06:31 UTC, efimov90 commented on VodovozBusiness/HibernateMapping/Cash/PayoutRequestBaseMap.cs
> +			Map(x => x.PayoutRequestState).Column("state").CustomType<PayoutRequestBase.CashRequestStateStringType>();
если есть возможность запихать это в Using То лучше сделать а тут сократить

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/Journals/JournalSelectors/ExpenseCategorySelectorFactory.cs
> +	        ISubdivisionJournalFactory subdivisionJournalFactory, IExpenseCategorySelectorFactory expenseCategorySelectorFactory)
уже все с новой строки, перенеси на новую тоже

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
выровняй && с if

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +		public bool CanConfirmPossibilityNotToReconcilePayments => Entity.ObservableSums.Count > 1 &&
&& на новой строке

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +		public bool CanGiveSum => UserRole == PayoutRequestUserRole.Cashier &&
&& на новой строке

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +		public bool CanReturnToRenegotiation => Entity.PayoutRequestState == PayoutRequestState.Agreed ||
|| на новой строке

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +		public bool CanCancel => Entity.PayoutRequestState == PayoutRequestState.Submited ||
|| на новой строке

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +				if(Entity.PayoutRequestState == PayoutRequestState.Agreed && Entity.ExpenseCategory == null &&
&& на новой строке, все условия разделить по строкам раз 1 уже перенесено

2021-09-03 06:31 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
> +		public bool CanAccept => Entity.PayoutRequestState == PayoutRequestState.New ||
во всем файле || на новой строке как и && там где есть перенос условий на новую строку

2021-09-03 06:33 UTC, kozlov-d commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
CashRequest вообще не хотелось бы трогать. Я только местами там вроде поправил форматирование

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Cash/IncomeCategoryViewModel.cs
Проверки на null нет

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Cash/ExpenseCategoryViewModel.cs
И тут

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
> +			}
Это точно нужно?

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> -        public IEntityAutocompleteSelectorFactory ExpenseCategoryAutocompleteSelectorFactory { get; }
Почему весь файл красный? Заменил окончания строк?

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozBusiness/Domain/Cash/CashRequest/PayoutRequestBase.cs
> +        [Display(Name = "Состояние")]
Невыровнено

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozBusiness/Domain/Cash/CashRequest/PayoutRequestBase.cs
> +        private Subdivision subdivision;
Это что?

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozBusiness/Domain/Cash/CashRequest/CashlessRequestFile.cs
> +		}
() => Убирай

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozBusiness/Domain/Cash/CashRequest/CashlessRequest.cs
> +			if(Author == null)
Мне кажется стоит всю валидацию в самый низ файла перенести

2021-09-03 06:57 UTC, ShubArseniy commented on Vodovoz/Vodovoz.csproj
>        <Name>RdlEngine</Name>
Почему сменился?

2021-09-03 06:57 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Cash/CashRequestJournalViewModel.cs
> +	{
Если журнал стал мультипл, почему название осталось CashRequestJournalViewModel?

2021-09-03 07:43 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
> +			}
Для заявки нужен сотрудник, вроде так и надо, нет?

2021-09-03 07:44 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> -        public IEntityAutocompleteSelectorFactory ExpenseCategoryAutocompleteSelectorFactory { get; }
Там где то табы менял, отдельным коммитом старался, мб вместе с этим поменялись и окончания. На линуксе у меня вряд ли куда либо залетит crlf

2021-09-03 07:44 UTC, kozlov-d commented on VodovozBusiness/Domain/Cash/CashRequest/PayoutRequestBase.cs
> +        private Subdivision subdivision;
Уберу, осталось от гавра

2021-09-03 08:25 UTC, kozlov-d commented on Vodovoz/Commons/FileChooser.cs
> +        private readonly string _fileName;
Переименовал, убрал readonly, заменил на табы

2021-09-03 08:31 UTC, kozlov-d commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
![изображение](https://user-images.githubusercontent.com/35382406/131975610-98162db8-7360-4b70-807b-4e91e3c91397.png)
По сабжу. И так каждая команда

2021-09-03 08:59 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
![изображение](https://user-images.githubusercontent.com/35382406/131979265-bec02187-27dc-4c33-9730-6bab7cf38102.png)
![изображение](https://user-images.githubusercontent.com/35382406/131979319-236580b2-5078-4b90-8daf-704c48afe8fb.png)
Не знаю, как у тебя настроено автоформатирование. У меня ничего с if не равняется, только в некоторых случаях есть смысл переносить операторы сравнения. И в варианте на скринах имхо второй лучше

2021-09-03 09:00 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
У тебя ctrl+k+d не смещает потом это все?

2021-09-03 09:02 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
Крч такое форматирование надо обсуждать. И настраивать у всех ide чтобы формат выставлялся одинаковый при автоформатировании

2021-09-03 09:04 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
это не меняет факта, что во ViewModel эта команда может быть null

2021-09-03 09:05 UTC, efimov90 commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
2й вариант в разы хуже

2021-09-03 09:05 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
Я соглашусь, что местами оператор будет лучше виден, если расположен в начале, но не везде это обязательно

2021-09-03 09:09 UTC, kozlov-d commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
Все равно не понимаю, что тут не так. Разве если она будет null при вызове Execute, она предварительно не создастся при доступе к полю или что?

2021-09-03 09:12 UTC, ShubArseniy commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
> +			}
Так он везде нужен, где-то в базовом классе должна быть проверка

2021-09-03 09:21 UTC, kozlov-d commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
> +			}
Это есть в валидации обоих классов. В приниципе, общие для валидации поля стоит перенести в валидацию базы, но вкладку то все равно нельзя открывать без указанного сотрудника. В этом просто смысла нет. По ТЗ заявки на наличку поле автора должно быть неизменяемым. И текущий сотрудник нужен только для указания автора заявки. Кто создал, тот и автор.

2021-09-03 10:48 UTC, kozlov-d commented on VodovozViewModels/Journals/JournalViewModels/Cash/CashRequestJournalViewModel.cs
> +	{
Переименовал журнал

2021-09-03 10:48 UTC, kozlov-d commented on Vodovoz/Vodovoz.csproj
>        <Name>RdlEngine</Name>
Вернул, иногда залетает у меня почему то

2021-09-03 10:49 UTC, kozlov-d commented on VodovozBusiness/Domain/Cash/CashRequest/CashlessRequestFile.cs
> +		}
Убрал

2021-09-03 11:27 UTC, ShubArseniy commented on VodovozViewModels/Journals/JournalViewModels/Cash/PayoutRequestsJournalViewModel.cs
> +	{
А ноду и фильтр почему не переименовал? Они же тоже общие

2021-09-03 12:24 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
У тебя поле nullable, если там будет null - получишь nullref

2021-09-03 12:33 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> +			   && alreadyGiven > 0
Субъективно, 1 вариант лучше

2021-09-03 12:33 UTC, kozlov-d commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
nullable это про это про значимые типы. Понятно, конечно, что речь про ссылочный тип DelegateCommand и ссылка у него может быть null, но если _acceptCommand == null - то команда создается, присваивается и возвращается. Объясни, если это не так

2021-09-03 12:42 UTC, Druchik commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +					? PersonHelper.PersonNameWithInitials(
Разве tab не надо добавить?

2021-09-03 12:47 UTC, Druchik commented on Vodovoz/MainWindow.cs
> +	        (null, payoutRequestFilterViewModel, employeeJournalFactory, OpenPageOptions.IgnoreHash);
Зачем передавать фильтр, если он стандартный? Он сам отрезолвится

2021-09-03 12:56 UTC, Druchik commented on Vodovoz/TempAdapters/ExpenseCategorySelectorFactory.cs
> +					new CategoryRepository(new ParametersProvider()).ExpenseSelfDeliveryCategories(uow).Select(x => x.Id);
У тебя два раза это используется. Может лучше проинициализировать это в конструкторе и использовать в методах?

2021-09-03 12:59 UTC, Druchik commented on Vodovoz/TempAdapters/ExpenseCategorySelectorFactory.cs
> +			var expenseFactory = new ExpenseCategorySelectorFactory();
По идее фабрики тоже можно закэшировать. Наверно пока оставь, надо будет это обсудить

2021-09-03 13:01 UTC, Druchik commented on Vodovoz/ViewModels/Accounting/WayBillGeneratorViewModel.cs
> +                                                ?? throw new ArgumentNullException(nameof(employeeJournalFactory));
Ты же делаешь проверку на результат метода или я не прав?
Должно быть тогда (employeeJournalFactory ?? throw).Create..

2021-09-03 13:03 UTC, kozlov-d commented on Vodovoz/ViewModels/Accounting/WayBillGeneratorViewModel.cs
> +                                                ?? throw new ArgumentNullException(nameof(employeeJournalFactory));
Пропустил знак вопроса, исправлю

2021-09-03 13:05 UTC, kozlov-d commented on Vodovoz/TempAdapters/ExpenseCategorySelectorFactory.cs
> +					new CategoryRepository(new ParametersProvider()).ExpenseSelfDeliveryCategories(uow).Select(x => x.Id);
Исправил

2021-09-03 13:16 UTC, Druchik commented on Vodovoz/Views/Cash/CashlessRequestFilesView.cs
> +			menu.Popup();
А зачем нам постоянно создавать меню? Мы же можем один раз создать, а по нажатию его вызывать, разве нет?

2021-09-03 13:22 UTC, Druchik commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +	[HistoryTrace]
Права на документ не нужны?

2021-09-03 13:24 UTC, Druchik commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +					|| PayoutRequestState == PayoutRequestState.OnClarification
Прям под if их запихивать я думаю не надо. Нужно обсуждать

2021-09-03 13:26 UTC, Druchik commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +			&& Organization == null)
Двойное условие можно было и в одну строку. Хотя это дело вкуса)

2021-09-03 13:29 UTC, kozlov-d commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +					|| PayoutRequestState == PayoutRequestState.OnClarification
Ну менять я уже не буду, и так искал в райдере минут 40, где это настраивается

2021-09-03 13:30 UTC, kozlov-d commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +	[HistoryTrace]
Были в базовом классе, скорее всего будут некорректно работать, закинул на каждый класс

2021-09-03 13:36 UTC, efimov90 commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
Она у тебя на месте создается в твоей конкретной ViewModel, ты не можешь гарантировать, что она во View не будет null

2021-09-03 13:36 UTC, Druchik commented on VodovozViewModels/Journals/FilterViewModels/Cash/PayoutRequestJournalFilterViewModel.cs
> +				}
У тебя здесь не сто раз будет дергаться Update?

2021-09-03 13:40 UTC, Druchik commented on VodovozViewModels/Journals/JournalSelectors/ExpanceCategoryAutoCompleteSelectorFactory.cs
> +		ExpenseCategorySelectorFactory, IEntityAutocompleteSelectorFactory
Можно было сделать по аналогии с остальными фабриками, т.е. сделать фабрику фабрик селекторов. Да и не тянуть все эти зависимости в конструктор, а создавать их на месте

2021-09-03 13:42 UTC, kozlov-d commented on VodovozViewModels/Journals/JournalSelectors/ExpanceCategoryAutoCompleteSelectorFactory.cs
> +		ExpenseCategorySelectorFactory, IEntityAutocompleteSelectorFactory
Была такая мысль, но показалось быстрее будет заюзать то, что уже есть. Это не я писал если что, на income такая же история

2021-09-03 13:42 UTC, Druchik commented on VodovozViewModels/Journals/JournalSelectors/ExpenseCategorySelectorFactory.cs
> +		public ExpenseCategorySelectorFactory(ICommonServices commonServices,
Тоже самое, если это будет удобнее

2021-09-03 13:45 UTC, Druchik commented on VodovozViewModels/Journals/JournalSelectors/ExpenseCategorySelectorFactory.cs
> +		public ExpenseCategorySelectorFactory(ICommonServices commonServices,
Запихнуть в предыдущую переделанную фабрику, если будет переделываться

2021-09-03 13:46 UTC, Druchik commented on VodovozViewModels/Journals/JournalSelectors/IncomeCategoryAutocompleteSelectorFactory.cs
> +		IncomeCategorySelectorFactory, IEntityAutocompleteSelectorFactory
Аналогично Экспенсам

2021-09-03 13:46 UTC, kozlov-d commented on VodovozViewModels/Journals/FilterViewModels/Cash/PayoutRequestJournalFilterViewModel.cs
> +				}
В каких случаях это может быть? Вроде не дергается, все ок, фильтрация работает

2021-09-03 13:50 UTC, Druchik commented on VodovozViewModels/Journals/JournalViewModels/Cash/FuelDocumentsJournalViewModel.cs
> +	        this._carJournalFactory = carJournalFactory ?? throw new ArgumentNullException(nameof(carJournalFactory));
this не убрал

2021-09-03 13:53 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/CashlessRequestFilesViewModel.cs
> +			set => SetField(ref _readOnly, value, () => ReadOnly);
Лямбду убери

2021-09-03 13:57 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
> +				counterpartyJournalFactory?.CreateCounterpartyAutocompleteSelectorFactory()
Вместо ? повесить проверку на нулл и делов

2021-09-03 13:58 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/ExpenseCategoryViewModel.cs
> +				expenseCategorySelectorFactory?.CreateDefaultExpenseCategoryAutocompleteSelectorFactory()
Аналогично

2021-09-03 13:59 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/IncomeCategoryViewModel.cs
> +				incomeCategorySelectorFactory?.CreateDefaultIncomeCategoryAutocompleteSelectorFactory()
Туда же

2021-09-03 13:59 UTC, efimov90 requested changes

2021-09-03 13:59 UTC, efimov90 commented on VodovozViewModels/Journals/FilterViewModels/Cash/PayoutRequestJournalFilterViewModel.cs
> +				}
А где проверка на != _documentType?

2021-09-03 14:06 UTC, kozlov-d commented
![изображение](https://user-images.githubusercontent.com/35382406/132018490-6fb230fd-95e1-4b36-af12-f3784e311b15.png)
Разве updateFilterField этого не делает?

2021-09-03 14:09 UTC, Druchik commented on VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
> +					|| PayoutRequestState == PayoutRequestState.OnClarification
Я и говорю обсудим этот момент)

2021-09-03 14:12 UTC, Druchik commented on VodovozViewModels/Journals/JournalSelectors/ExpanceCategoryAutoCompleteSelectorFactory.cs
> +		ExpenseCategorySelectorFactory, IEntityAutocompleteSelectorFactory
Я в курсе. Ладно, нет времени не правь. У меня в экшенах это исправлено, если их примут)

2021-09-03 14:13 UTC, Druchik commented on VodovozViewModels/Journals/FilterViewModels/Cash/PayoutRequestJournalFilterViewModel.cs
> +				}
У тебя же несколько присваиваний свойств. У каждого Update, точно только один раз вызывает?

2021-09-03 14:21 UTC, Druchik commented on Vodovoz/Dialogs/Cash/CashRequestView.cs
> +			ybtnAccept.Clicked += (sender, args) => { ViewModel.AcceptCommand.Execute(); };
Тоже не вкурил о чем ты))

2021-09-03 14:55 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
>  			_currentEmployee = employeeRepository?.GetEmployeeForCurrentUser(UoW)
Пропустил

2021-09-03 14:55 UTC, Druchik commented on VodovozViewModels/ViewModels/Cash/IncomeCategoryViewModel.cs
>  			var employeeAutocompleteSelector = employeeJournalFactory?.CreateEmployeeAutocompleteSelectorFactory()
Тоже

2021-09-06 07:32 UTC, Druchik approved these changes

2021-09-06 12:56 UTC, efimov90 requested changes

2021-09-06 12:56 UTC, efimov90 commented on Vodovoz/Views/Client/CounterpartyFilesView.cs
> +			if(ViewModel == null)
Add braces

2021-09-06 12:56 UTC, efimov90 commented on VodovozViewModels/ViewModels/Counterparty/CounterpartyFilesViewModel.cs
> +			this._filePicker = filePicker ?? throw new ArgumentNullException(nameof(filePicker));
this лишний

2021-09-09 14:35 UTC, efimov90 approved these changes

2021-09-09 15:33 UTC, kozlov-d commented
Ждем-с тестирования

2021-10-13 06:41 UTC, merged