3642 Удаление возвратного платежа при восстановлении заказа в работу
VodovozOrganization/Vodovoz pull request #961
Opened 2021-09-10 07:38 UTC by kozlov-d

При переводе адреса МЛ в статусы В пути и Выполнен из Недовоз или Доставка отменена, если ассоциированный с адресом заказ - заказ с оплатой по безналу, проверяется наличие возврата, который удаляется и заказ меняет статус оплаты

2021-09-10 10:11 UTC, Enzogord requested changes

2021-09-10 10:11 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
> +		public Payment GetRefundPaymentByRefundedPaymentId(IUnitOfWork uow, int refundedPaymentId)
Имя метода GetRefundPayment смотрится куда лучше

2021-09-10 10:11 UTC, Enzogord commented on VodovozBusiness/Domain/Orders/Order.cs
> +			if((previousStatus == OrderStatus.DeliveryCanceled || previousStatus == OrderStatus.NotDelivered)
А Canceled статус не надо учитывать?

2021-09-10 10:22 UTC, kozlov-d commented on VodovozBusiness/Domain/Orders/Order.cs
> +			if((previousStatus == OrderStatus.DeliveryCanceled || previousStatus == OrderStatus.NotDelivered)
У заказа нет такого статуса, есть Closed. В closed заказ падает только в случае самовывоза или если закрывается МЛ. Не думаю, что надо его тут учитывать

2021-09-10 10:38 UTC, kozlov-d commented on VodovozBusiness/Domain/Orders/Order.cs
> +			if((previousStatus == OrderStatus.DeliveryCanceled || previousStatus == OrderStatus.NotDelivered)
Ошибся, есть такой статус

2021-09-13 06:05 UTC, Druchik commented on VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
> +				.FirstOrDefault();
Можно же просто FirstOrDefault(), не?

2021-09-13 06:06 UTC, Druchik commented on VodovozBusiness/Domain/Orders/Order.cs
> +				var totalPayed = paymentItems.Select(pi => pi.Sum).Sum();
Можно же условие в Sum запихнуть, если я не ошибаюсь

2021-09-13 06:26 UTC, kozlov-d commented on VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
> +				.FirstOrDefault();
Изменил на single or default, fod нет у queryOver, а sod не принимает лямбду, потому where оставил

2021-09-13 06:26 UTC, kozlov-d commented on VodovozBusiness/Domain/Orders/Order.cs
> +				var totalPayed = paymentItems.Select(pi => pi.Sum).Sum();
Изменил

2021-09-13 06:45 UTC, merged