3669 Изменение запрета на удаление МЛ
VodovozOrganization/Vodovoz pull request #973
Opened 2021-09-14 16:01 UTC by DobriyMisha

Необходимо было запретить удаление МЛ, если с ним уже происходили какие-либо изменения
По комментарию к задаче, требовалось:
-разрешить удаление МЛ только из статуса "Новый";
-разрешить удаление, если не было Критичного изменения (выдачи топлива).

2021-09-14 16:06 UTC, Enzogord requested changes

2021-09-14 16:06 UTC, Enzogord commented on Vodovoz/Representations/RouteListsVM.cs
> +				}
Предлагаю убрать это в репозиторий

2021-09-19 19:10 UTC, DobriyMisha commented on Vodovoz/Representations/RouteListsVM.cs
> +				}
Ну, смотря в какой. Если РутЛист репозиторий , его прокидывать надо

2021-09-21 12:13 UTC, DobriyMisha commented on Vodovoz/Representations/RouteListsVM.cs
> +				}
Перенес

2021-09-24 12:19 UTC, Enzogord requested changes

2021-09-24 12:19 UTC, Enzogord commented on VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +		public bool CanDeleteRouteListIfNoFuelGiven(IUnitOfWork uow, int id)
Метод просто возвращает наличие выданного топлива, он может использоваться не только для удаления МЛ.
Название не подходящее

2021-09-24 13:04 UTC, DobriyMisha commented on VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
> +		public bool CanDeleteRouteListIfNoFuelGiven(IUnitOfWork uow, int id)
Поменял

2021-09-24 13:05 UTC, Enzogord approved these changes

2021-09-24 13:34 UTC, merged